### ISSUE TITLE
[RFC] Initial package

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#1]
As I see from @1dot75cm [package list](https://github.com/1dot75cm/repo/blob/21b23b2e3ebac843b2d04989cdef146f8d75088b/package_list.md) I have some concern:
1. Is Sougou Pinyin compatible with the guideline?
2. IMO fcitx-sunpinyin, sunpinyin lies in the official repo of Fedora. So is it still essential? Although I never can use it properly.
3. And the same concern for the vendor-specified software. Are they compatible with the guideline?
4. Drivers can be a specified class, instead of just being in 'misc'

**Comment by sztsian** [comment]
And, I advise for having drivers for Tencent Wifi (Xiaodu Wifi/360 Wifi/Xiaomi Wifi etc.) as it is really cheap and great opportunity one have it for various reasons. But the driver is not in mainstream kernel. The only bad issue is that the official driver works only on 2.\* kernel. There is a GPL one on [github](https://github.com/eywalink/mt7601u), but both of the two(official, and github one) are badly scripted in Makefile. So we need to re-write the makefile to make it work as a dkms kernel model.

**Comment by tvvocold** [comment]
1, 搜狗输入法这个我们可以看能否和搜狗方面进行沟通。[1]
2, +1
3, +1
4, +1 

是否可以参考 archlinuxcn 的 [repo](https://github.com/archlinuxcn/repo) ?
BTW, 具体（优先）打包什么软件，这方面我们可以采用 http://feathub.com/ 来进行表决。（需要 owner 组开通 FZUG/repo 的 feathub.)

[1] http://pinyin.sogou.com/bbs/forum.php?mod=viewthread&tid=2615805&extra=page%3D1

**Comment by alick** [comment]
This is why I think a voice meeting is necessary at first. mosquito's list is quite long and needs some time for audit.

IRC is fine, but I doubt we can deal with them once in one meeting.

**Comment by alick** [comment]
archlinuxcn's list is a poor example to us, since they do not need license audit.

**Comment by 1dot75cm** [comment]
el7 不包含 fcitx-\* rpms，另外更新官方源 rpm 的部分代码。
基于以上两个原因，打包了 fcitx。

**Comment by cheese** [comment]
要维护 el7 的 fcitx，建议通 epel 的途径，建议基于 Fedora 的 fcitx

**Comment by 1dot75cm** [comment]
https://copr.fdzh.org/coprs/mosquito/FZUG/  
已完成部分软件包打包及测试，并提交 PR。  
fcitx for el7 之前在 myrepo 已完成打包测试，但后期维护量巨大。[搁置]

**Comment by 1dot75cm** [comment]
> _1. Is Sougou Pinyin compatible with the guideline?

Sogou Pinyin 是部分开源的免费软件

> _2. IMO fcitx-sunpinyin, sunpinyin lies in the official repo of Fedora. So is it still essential? Although I never can use it properly.

修正 fcitx-sunpinyin 依赖关系/更新字典，另外考虑在为 el7 提供 fcitx 前完善 spec (基于 fedora)

> _3. And the same concern for the vendor-specified software. Are they compatible with the guideline?

目前已打包的均为开源软件（除 sogou），之后会注明协议方便审查

> _4. Drivers can be a specified class, instead of just being in 'misc'

后期再重新分类，驱动相关的由于需要大量测试，因此较少打包

> And, I advise for having drivers for Tencent Wifi (Xiaodu Wifi/360 Wifi/Xiaomi Wifi etc.) as it is really cheap and great opportunity one have it for various reasons. But the driver is not in mainstream kernel. The only bad issue is that the official driver works only on 2.\* kernel. There is a GPL one on github, but both of the two(official, and github one) are badly scripted in Makefile. So we need to re-write the makefile to make it work as a dkms kernel model.

需要相应设备测试，目前我没有。如果有设备，可以尝试打包驱动

---

感谢各位的关注，希望有更多人参与打包，使 fedora 圈更活跃

**Comment by sztsian** [comment]
> 需要相应设备测试，目前我没有。如果有设备，可以尝试打包驱动

I have bought one Tencent WiFi to packaging drivers and I also have my own spec files. So if you are familiar with makefile, you can pick it up offline and try to fix the makefile.

**Comment by 1dot75cm** [comment]
> I have bought one Tencent WiFi to packaging drivers and I also have my own spec files. So if you are familiar with makefile, you can pick it up offline and try to fix the makefile.

可以试试看

**Comment by ghost** [comment]
*\* (bcloud-gui:25671): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3.4/site-packages/bcloud/App.py", line 37, in <module>
    from bcloud.FileWatcher import WatchFileChange
  File "/usr/lib/python3.4/site-packages/bcloud/FileWatcher.py", line 8, in <module>
    import pyinotify
ImportError: No module named 'pyinotify'
最新的3.7.1.1的bcloud无法启动，之前的3.6版本就没有问题。
系统环境是：Fedora 22 x86_64 XFCE，这个不会跟桌面环境有关吧...google无果

**Comment by sztsian** [comment]
@tvvocold LEGAL ISSUE:
Currently I see this is still not approved. However, I saw many packages are already in http://repo.fdzh.org/

Among them, Chrome, opera and many others are Proprietary software or have legal issue for redistribution.

Besides, the Android mascot in the background image is also registered by Google, so these really should not be there.

@alick ideas?

https://github.com/FZUG/repo/issues/5

**Comment by sztsian** [comment]
@SeAL80s 这个issue是审阅初始包列表的，请另开issue报这个问题。否则恐怕没有人会回复。

**Comment by alick** [comment]
2015-05-26 20:12 GMT+08:00 Zamir SUN notifications@github.com:

> @tvvocold https://github.com/tvvocold LEGAL ISSUE:
> Currently I see this is still not approved. However, I saw many packages
> are already in http://repo.fdzh.org/
> 
> Among them, Chrome, opera and many others are Proprietary software or have
> legal issue for redistribution.
> 
> Besides, the Android mascot in the background image is also registered by
> Google, so these really should not be there.
> 
> @alick https://github.com/alick ideas?

I agree. They should not be there without review and approval.

**Comment by 1dot75cm** [comment]
- 应提高开源软件的审查效率  https://github.com/FZUG/repo/pull/4
- 闭源软件，则应当在取得 版权人“书面”许可的情况下分发 rpm 包（许可附加在 PR）

**Comment by alick** [comment]
What is this issue about? Can it be closed?

**Comment by sztsian** [comment]
Close the issue as this is focus on initialing the repo with basic essential packages. And the repo is already working
