### ISSUE TITLE
能否坐下wine qq的整合

### ISSUE THREAD

**Issue by love4taylor** [FZUG/repo#10]

**Comment by alick** [comment]
嘛意思？“坐下”？

**Comment by Endle** [comment]
我并不乐观
1. wine qq 可能会导入 windows 的 native dll. 我们是否可以重分发？
2. 我们将 QQ 安装后解压出的文件重分发，是否违反了腾讯的规定？

相比之下，我建议我们考虑一下整合 [https://github.com/hillwoodroc/winetricks-zh](https://github.com/hillwoodroc/winetricks-zh)

**Comment by sztsian** [comment]
[QQ软件许可及服务协议](http://kiss.3g.qq.com/activeQQ/agreement/index.html)不符合[中文社区Copr打包分类指南](https://github.com/FZUG/Copr/wiki/%E4%B8%AD%E6%96%87%E7%A4%BE%E5%8C%BA-Copr-%E6%89%93%E5%8C%85%E5%88%86%E7%B1%BB%E6%8C%87%E5%8D%97)的约束，因此不会在Copr中打包。又因其以下协议内容

> 通过非腾讯开发、授权的第三方软件、插件、外挂、系统，登录或使用腾讯软件及服务，或制作、发布、传播上述工具；

使其在Wine中运行的合法性具有不确定性。所以看起来不会对制作Wine QQ的整合。

**Comment by 1dot75cm** [comment]
> 相比之下，我建议我们考虑一下整合 https://github.com/hillwoodroc/winetricks-zh

这个确实不错，可以考虑打包整合。

**Comment by Endle** [comment]
>  相比之下，我建议我们考虑一下整合 https://github.com/hillwoodroc/winetricks-zh

在刚才的 IRC 会议上，我们进行了讨论，认为 winetricks-zh 符合我们的要求
请问有人愿意打包吗？

**Comment by 1dot75cm** [comment]
> 在刚才的 IRC 会议上，我们进行了讨论，认为 winetricks-zh 符合我们的要求
> 请问有人愿意打包吗？

https://github.com/FZUG/repo/blob/master/rpms/SPECS/winetricks/winetricks.spec

**Comment by 1dot75cm** [comment]
如果各位有什么要向 winetricks-zh 提交的包，可以到 https://github.com/FZUG/winetricks-zh 开 issue/PR。稳定的 ×.verb 软件将向 winetricks-zh 提交，并合并至 winetricks.spec

**Comment by tvvocold** [comment]
赞👍

**Comment by alick** [comment]
+1

2015-07-04 13:00 GMT+08:00 1dot75cm notifications@github.com:

**Comment by Endle** [comment]
如果这样，我们是不是考虑关闭这个 issue 了？

另外，@1dot75cm  
在 spec 里，我看到了

> Source0: https://github.com/Winetricks/winetricks/archive/%{_commit}/%{repo}-%{_shortcommit}.tar.gz
> Source1: https://github.com/hillwoodroc/winetricks-zh/archive/%{zh_commit}/%{zh_repo}-%{zh_scommit}.tar.gz

请问，能解释一下 Source0 Source1 的含义吗？

**Comment by 1dot75cm** [comment]
Source0是官方 winetricks 源码，Source1是 winetricks-zh 修改的源码。
目前 winetricks-zh 中的额外汉化还没有合并（看看重要与否），另外 winetricks-zh 中额外添加的软件只测了 163music，qq什么的没测试。各位可以安装看看。

**Comment by Endle** [comment]
> 目前 winetricks-zh 中的额外汉化还没有合并（看看重要与否）

我认为应当合并，这很影响用户体验

> 另外 winetricks-zh 中额外添加的软件只测了 163music，qq什么的没测试。各位可以安装看看。

我们有义务逐一测试这些软件吗？我觉得没有必要

不过，我们的确要正视可能的风险: https://bugzilla.redhat.com/show_bug.cgi?id=1147271
winetricks-zh 应该是针对原有的 wine (请求确认 @hillwoodroc )  而非 wine-staging。所以，如果有用户使用中遇到 bug，我们要引导他们到https://github.com/FZUG/winetricks-zh 而非 https://github.com/hillwoodroc/winetricks-zh 反馈问题

**Comment by hillwoodroc** [comment]
不管是 winetricks 还是 winetricks-zh，因为他们调用的 wine 执行文件都是 /usr/bin 下面的，所以 winetricks 和 winetricks-zh 在实际使用中具体是针对哪个版本，取决于 /usr/bin 下的 wine 可执行文件是哪个版本。不管是上游版本还是本人的修改版都没有考虑针对某一个版本做特别的优化（即使这样做了实际上也无意义），甚至还考虑了向前兼容。
所以，winetricks-zh 没有针对某一个特别的版本，只是我的测试绝大部分情况是在原有 wine 上进行的，用在 wine-staging 也没什么问题（很显然的），就是这样。

**Comment by Endle** [comment]
[**@hillwoodroc**](https://github.com/hillwoodroc) commented on [6 Jul 2015, 10:21 GMT+8](https://github.com/FZUG/repo/issues/10#issuecomment-118693854):

> 不管是 winetricks 还是 winetricks-zh，因为他们调用的 wine 执行文件都是 /usr/bin 下面的，所以 winetricks 和 winetricks-zh 在实际使用中具体是针对哪个版本，取决于 /usr/bin 下的 wine 可执行文件是哪个版本。不管是上游版本还是本人的修改版都没有考虑针对某一个版本做特别的优化（即使这样做了实际上也无意义），甚至还考虑了向前兼容。
> 所以，winetricks-zh 没有针对某一个特别的版本，只是我的测试绝大部分情况是在原有 wine 上进行的，用在 wine-staging 也没什么问题（很显然的），就是这样。

是的。我的意思是，wine-staging 可能会引入一些新的问题，因此当用户报告 fedora下的 bug，你可能无法在其他发行版重现

**Comment by hillwoodroc** [comment]
呵呵，其实我同时安装有 wine 和 wine-staging，只要报告者说明是 wine-staging 的运行状况，我也会在 wine-staging 下尝试去重现的。当然，fedora 的用户先把 bug 报到 fedora 这边我也是赞成的。

**Comment by Endle** [comment]
[**@hillwoodroc**](https://github.com/hillwoodroc) commented on [6 Jul 2015, 14:07 GMT+8](https://github.com/FZUG/repo/issues/10#issuecomment-118736111):

> 呵呵，其实我同时安装有 wine 和 wine-staging，只要报告者说明是 wine-staging 的运行状况，我也会在 wine-staging 下尝试去重现的。当然，fedora 的用户先把 bug 报到 fedora 这边我也是赞成的。

好敬业啊，辛苦了
那我就先把这个 Issue 关掉了
