### ISSUE TITLE
请移除xware-desktop

### ISSUE THREAD

**Issue by el-psy-k** [FZUG/repo#101]
作者已放弃维护，并且使用权限已过期，详见:[https://github.com/Xinkai/XwareDesktop/issues/273](https://github.com/Xinkai/XwareDesktop/issues/273)

**Comment by ghost** [comment]
@1dot75cm Here is a request of removing `xware-desktop-0.13-3.gitb77d20b` from repo.

<br>
BTW, the build status for `xware-desktop-0.13-3.gitb77d20b` package is:

> | Package Name | x86_64 | i686 |
> | --- | --- | --- |
> | xware-desktop-0.13-3.gitb77d20b.fc24.src.rpm | ![](https://img.shields.io/badge/build-failing-red.svg) | ![](https://img.shields.io/badge/build-failing-red.svg) |

**Comment by sztsian** [comment]
是直接移除SPEC么，有办法让它标记为obsolete从而让用户在dnf update时自动删除么？
（Solaris的pkg是有obsolete机制的。。发现我对dnf还不如Solaris的pkg了解）

**Comment by ghost** [comment]
@sztsian 想到個簡單粗暴的方法。 更新 FZUG release repo package，標記 obsolete 。(笑

**Comment by alick** [comment]
或者出个更新的版本，但内容是空的。版本号可能要设个巨大的，比如 0.999999

Changelog 和 description 写清楚原因。

**Comment by ghost** [comment]
> 版本号可能要设个巨大的，比如 0.999999

 Gentoo masked package 即视感 233333

话说而且这样的话，版本应该是 9999 不是 0.999999 吧 。

<br>

> 或者出个更新的版本，但内容是空的。

作为强迫症，感觉有点儿受不了这样空的包存在 (,,•́ . •̀,,)

**Comment by alick** [comment]
2016-05-14 22:07 GMT-05:00 nrechn notifications@github.com:

> 版本号可能要设个巨大的，比如 0.999999
> 
> Gentoo masked package 即视感 233333
> 
> 话说而且这样的话，版本应该是 9999 不是 0.999999 吧 。
> 
> 嗯
> 
> 或者出个更新的版本，但内容是空的。
> 
> 作为强迫症，感觉有点儿受不了这样空的包存在 (,,•́ . •̀,,)

可以放个 README 233
