### ISSUE TITLE
JDK打包是否合规？

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#104]
rpms/jdk/jdk.spec 我的理解是，jdk包是在打包过程中下载Oracle JDK的。我觉得这个似乎与指南有悖。我认为RPM包内不应当包含违反打包指南的文件，而不仅仅是src的指向。

我的提议是，如果有保留Oracle JDK的必要（我认为似乎是有的），能否让RPM中不含Oracle JDK，而是通过post脚本（或者RPM包中包含一个安装脚本，安装RPM后提醒用户手动运行脚本）来安装Oracle JDK？
@1dot75cm

**Comment by 1dot75cm** [comment]
`rpms/jdk/jdk.spec` 属于 net 包，在 `%install` 部分下载 JDK 是为了记录包的文件列表 (用于卸载)，实际这部分文件并不会包含在生成的 `rpm` 中（使用 `%ghost` 标记）。

安装时，通过 `%pre/post` 脚本下载 JDK 并进行安装，这与单独写 `install.sh` 脚本是一样的。您可以看下 [oracle-jdk8-1.8.0.92-1.net.x86_64.rpm](https://repo.fdzh.org/FZUG/testing/24/x86_64/oracle-jdk8-1.8.0.92-1.net.x86_64.rpm)。

另外， net rpm 包还有一个优点就是，可以通过包管理器完全卸载，不会有残留。

综上所述， net.rpm 包与执行脚本安装 JDK 的效果是一致的，且不包含违反指南的文件。@sztsian

**Comment by sztsian** [comment]
明白了～
