### ISSUE TITLE
广州教育网安装不了。

### ISSUE THREAD

**Issue by yylogo** [FZUG/repo#11]
Fedora 22, x86_64, LXDE桌面，广州五山区的教育网。

dnf install sogoupinyin -y
下载到一半就会失败。
直接在http://repo.fdzh.org/FZUG/找到文件之后wget也会下载到一半就失败。
最后是找到百度网盘里的rpm包单独安装sogou和opencc才装好的。

能解决这个问题嘛，不关掉FZUG的源就不能更新了。

**Comment by alick** [comment]
请提供一下 ping+traceroute （或者 mtr）到 repo.fdzh.org 的结果。另请 @Ray 关注一下。

在 2015年7月5日 下午1:09，张青阳 notifications@github.com 写道：

**Comment by yylogo** [comment]
貌似不能ping，我用的舍友热点发出来的WIFI，网关好像不能ping

$ traceroute baidu.com
traceroute to baidu.com (123.125.114.144), 30 hops max, 60 byte packets
 1  \* \* *
 2  \* \* *
 3  \* \* *
 4  \* \* *
 5  \* \* *
 6  \* \* *
 7  \* \* *
 8  \* \* *
 9  \* \* *
10  \* \* *

等我同学玩完游戏我用他的ping一下

**Comment by tvvocold** [comment]
@yylogo 
你的本地网络有问题，先更换 DNS 为 8.8.8.8 试试。
也可以尝试用 Axel 多线程下载 rpm 包后 `$ su -c "dnf  localinstall  --nogpgcheck {/path/to/whatever.rpm} -y"`

**Comment by yylogo** [comment]
任何网站和IP都不能ping，但都可以正常访问的。
把DNS修改成8.8.8.8还是不能，修改之后的ping和tracert没有区别。
舍友是Win7的系统，下面是用舍友电脑的情况：
可以正常访问repo.fdzh.org。

ping：

正在 Ping repo.fdzh.org [23.91.97.105] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

23.91.97.105 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

tracert:

通过最多 30 个跃点跟踪
到 repo.fdzh.org [23.91.97.105] 的路由:

  1    <1 毫秒    1 ms     1 ms  125.217.254.254 
  2    34 ms     1 ms    <1 毫秒 192.168.66.89 
  3    <1 毫秒   <1 毫秒   <1 毫秒 192.168.66.245 
  4    <1 毫秒   <1 毫秒   <1 毫秒 192.168.66.241 
  5     \*        \*        \*     请求超时。
  6     4 ms     3 ms     3 ms  14.18.144.169 
  7     1 ms     1 ms     1 ms  119.145.81.93 
  8     3 ms     3 ms     3 ms  61.144.3.10 
  9     \*        \*        \*     请求超时。
 10     3 ms     3 ms     3 ms  202.97.60.82 
 11    13 ms    10 ms    11 ms  202.97.61.18 
 12     8 ms     7 ms     7 ms  202.97.121.118 
 13    11 ms    12 ms    10 ms  110.79.255.198 
 14    29 ms    14 ms    12 ms  110.79.15.34 
 15     \*        \*        \*     请求超时。
 16     \*        \*        \*     请求超时。
 17     \*        \*        \*     请求超时。
 18     \*        \*        \*     请求超时。
 19     \*        \*        \*     请求超时。
 20     \*        \*        \*     请求超时。
 21     \*        \*        \*     请求超时。
 22     \*        \*        \*     请求超时。
 23     \*        \*        \*     请求超时。
 24     \*        \*        \*     请求超时。
 25     \*        \*        \*     请求超时。
 26     \*        \*        \*     请求超时。
 27     \*        \*        \*     请求超时。
 28     \*        \*        \*     请求超时。
 29     \*        \*        \*     请求超时。
 30     \*        \*        \*     请求超时。

跟踪完成。

**Comment by yylogo** [comment]
用axel下载前50%还挺好的，到50%左右它就基本没速度了，刚刚回来看下完了。

**Comment by tvvocold** [comment]
repo服务器做了处理，是禁止ping的

**Comment by tvvocold** [comment]
抱歉，经测试确定 repo 服务器满足不了高并发的问题，@1dot75cm 正在处理。

**Comment by tvvocold** [comment]
See https://github.com/FZUG/repo/issues/12
