### ISSUE TITLE
Atom spell-check issues

### ISSUE THREAD

**Issue by lucascosti** [FZUG/repo#110]
See https://github.com/atom/spell-check/issues/134#issuecomment-221451864

Apparently Atom spell-check issues are being cause by the packaging of Atom in the mosquito copr repo.

I'm currently experiencing this issue.

**Comment by 1dot75cm** [comment]
Thanks report. @lucascosti 
I get source code of atom, and build it. Spell check is work. I think I deleted some necessary files. Repair later.

**Comment by 1dot75cm** [comment]
Please try to use [atom-1.7.3-2.git1b3da6b.fc24](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/317348/) package. @lucascosti 
1. `(LANG=en-US atom)`
2. Ctrl+Shift+P, enter `spell`, select `Spell Check: Toggle`

**Comment by lucascosti** [comment]
Yep, confirmed as fixed in atom-1.7.3-2.git1b3da6b.fc24. Thanks for the quick fix, @1dot75cm . Much appreciated!  :D
