### ISSUE TITLE
网易云音乐官方的deb包重新打rpm包

### ISSUE THREAD

**Issue by godcrying** [FZUG/repo#111]
辛苦你们啦

**Comment by 1dot75cm** [comment]
已打包好（未上传），正在测试。 @godcrying

**Comment by sztsian** [comment]
@1dot75cm 看到现在我们并没有收录官方deb打包的网易云音乐。在网易云音乐官方网站我也没有查到其许可证。网易云音乐Linux版有明确的许可证声明么？

**Comment by Endle** [comment]
> @1dot75cm 看到现在我们并没有收录官方deb打包的网易云音乐。在网易云音乐官方网站我也没有查到其许可证。网易云音乐Linux版有明确的许可证声明么？

在广州LUG的微信群里，一位负责移植工作的Deepin工程师说可以
但我觉得，他的声明并不具有法律效力

问问Arch的朋友们是如何解决的？

**Comment by 1dot75cm** [comment]
许可证在 DEB 包里，似乎没有改完。以下是全文： @sztsian 
（如果协议不行，我做成 net 包）

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: netease-cloud-music
Source: <url://example.com>

Files: *
Copyright: <years> <put author's name and email here>
           <years> <likewise for another author>
License: <special license>
 <Put the license of the package here indented by 1 space>
 <This follows the format of Description: lines in control file>
 .
 <Including paragraphs>

# If you want to use GPL v2 or later for the /debian/* files use 
# the following clauses, or change it to suit. Delete these two lines
Files: debian/*
Copyright: 2015 Deepin Packages Builder <packages@linuxdeepin.com>
License: GPL-2+
 This package is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.
 .
 This package is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 .
 You should have received a copy of the GNU General Public License
 along with this program. If not, see <https://www.gnu.org/licenses/>
 .
 On Debian systems, the complete text of the GNU General
 Public License version 2 can be found in "/usr/share/common-licenses/GPL-2".

# Please also look if there are files or directories which have a
# different copyright/license attached and list them here.
# Please avoid picking licenses with terms that are more restrictive than the
# packaged work, as it may make Debian's contributions unacceptable upstream.
```

> 问问Arch的朋友们是如何解决的？ @Endle 

AUR “没有”版权要求，由于是分发 PKGBUILD，所以只要 PKGBUILD 本身符合协议要求即可，至于其分发的内容没有什么限制。

**Comment by simon-ding** [comment]
期待啊！

**Comment by alick** [comment]
@1dot75cm 看起来 GPL-2 只是覆盖了 debian/\* 即打包脚本。

需要联系网易上游问清楚。

**Comment by sztsian** [comment]
@1dot75cm 建议邮件咨询网易。至少我们需要确定它是否有分发限制。只有当没有分发限制时，才可以做net包的。

**Comment by 1dot75cm** [comment]
看起来需要咨询 @xushaohua 。 @sztsian 

```
netease-cloud-music (0.9.0-1) stable; urgency=medium
  * Pre stable release.

 -- Xu Shaohua <xushaohua@linuxdeepin.com>  Wed, 25 May 2016 04:13:11 +0800
```

请问 @xushaohua ，netease-cloud-music 是否有分发限制？

**Comment by XuShaohua** [comment]
是可以自由分发的. 但里面的二进制文件是不允许反编译/修改等操作的, 即需要保持二进制文件的完整性.

关于版权声明, 这个问题之前没有考虑到, 给各位带来了困扰, 很抱歉.
现在有同事在处理这个事情, 在下个版本里, 会附带正式的版权声明的.

**Comment by sztsian** [comment]
@XuShaohua  感谢
@1dot75cm 做net包吧。辛苦啦

**Comment by 1dot75cm** [comment]
已打包，关闭该问题。

**Comment by Endle** [comment]
看到已经更新了 spec https://github.com/FZUG/repo/blob/master/rpms/netease-cloud-music/netease-cloud-music.spec
不过，还是无法安装

$ sudo dnf install netease-cloud-music
上次元数据过期检查：0:04:13 前，执行于 Fri Jun  3 06:50:17 2016。
没有可用软件包 netease-cloud-music。
错误：没有任何匹配

请问，能帮忙看一下吗？谢谢

**Comment by ghost** [comment]
> ``` shell
> $ sudo dnf install netease-cloud-music
> ```
> 
> 上次元数据过期检查：0:04:13 前，执行于 Fri Jun 3 06:50:17 2016。
> 没有可用软件包 netease-cloud-music。
> 错误：没有任何匹配

@Endle 请检查下 `/etc/yum.repos.conf` 目录的 FZUG.repo，确保里面有开启`[fzug-testing]`

> ``` shell
> [fzug-testing]
> name=FZUG fc$releasever - Testing
> baseurl=https://repo.fdzh.org/FZUG/testing/$releasever/$basearch/
> skip_if_unavailable=True
> metadata_expire=1d
> gpgcheck=0
> enabled=1
> ```

**Comment by Endle** [comment]
> @Endle 请检查下 /etc/yum.repos.conf 目录的 FZUG.repo，确保里面有开启[fzug-testing]

谢谢，能正常安装，完全可用

**Comment by 1dot75cm** [comment]
:-1:  之前看贴吧，有人说网络错误。检查发现，是我的依赖写错了。 @Endle

**Comment by kjartanjph** [comment]
fedora25下无法播放音乐，提示加载加载失败，网络错误，gstreamer还有各种解码器都已经确认安装，还是无法解决，求助
