### ISSUE TITLE
安装FZUG之后报错。

### ISSUE THREAD

**Issue by fun1355** [FZUG/repo#115]
https://repo.fdzh.org/FZUG/testing/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.

**Comment by fun1355** [comment]
７要改成２３才行。

**Comment by fun1355** [comment]
我知道了，我的操作系统是CENTOS7.

**Comment by alick** [comment]
我们没有支持 CentOS，抱歉
