### ISSUE TITLE
Atom Package Install Page Broken

### ISSUE THREAD

**Issue by lucascosti** [FZUG/repo#116]
Hi again,

After the fix for #114, it looks like there still might be some issues with the `Install` page of the Atom settings.

There is a large blank area, with the 'Featured Packages' shown below.

![atom install problem2016-05-31 16-22-44](https://cloud.githubusercontent.com/assets/4434330/15665124/592fe7b6-274c-11e6-8b64-7d397f7fa7f4.png)

If you search for packages, it overlaps under the 'Featured Packages':

![atom install problem2 2016-05-31 16-25-01](https://cloud.githubusercontent.com/assets/4434330/15665135/6cfd860e-274c-11e6-8cc2-60102a2bafa9.png)

Again, this doesn't occur when using the RPM package from https://atom.io/.

Is there a reason why there have been so many issues with the builds of Atom in this copr repo? The https://copr.fedorainfracloud.org/coprs/helber/atom/ didn't have any of these type of issues.

**Comment by ghost** [comment]
Thanks for your report.

> Is there a reason why there have been so many issues with the builds of Atom in this copr repo? The https://copr.fedorainfracloud.org/coprs/helber/atom/ didn't have any of these type of issues.

As I known from @1dot75cm , our Atom package doesn't contain built-in Electron framework. Electron is split from Atom package in order to be able to share with other applications. I think that probably is the reason of these type of issues.

**Comment by 1dot75cm** [comment]
Thanks again. @lucascosti 
I have been fixed this error. Please test [atom-1.7.4-3.git6bed3e5](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/318268/) rpm package.

**Comment by lucascosti** [comment]
Yes, confirmed as fixed. Thanks :)
