### ISSUE TITLE
fcitx-googlepinyin无法启动

### ISSUE THREAD

**Issue by ghost** [FZUG/repo#117]
FZUG的fcitx-googlepinyin版本是fcitx-googlepinyin-0.1.6-2，导致fcitx下无法添加/调出Google拼音。
opensuse的fcitx-googlepinyin版本是fcitx-googlepinyin-0.1.6-7.5，就没有问题。

**Comment by 1dot75cm** [comment]
已经修复了， 见 https://github.com/FZUG/repo/issues/71#issuecomment-216835565 。 同一个问题，可以在之前的进行评论，而不用新开一个。 @SeAL80s
