### ISSUE TITLE
wps-office安装不了

### ISSUE THREAD

**Issue by simon-ding** [FZUG/repo#118]
```
sudo dnf install wps-office
上次元数据过期检查：0:02:29 前，执行于 Sat Jun  4 21:41:27 2016。
依赖关系解决。
==============================================================================================================
 Package                架构               版本                                仓库                      大小
==============================================================================================================
安装:
 wps-office             x86_64             10.1.0.5503-1.a20p2.net             fzug-nonfree             408 k

事务概要
==============================================================================================================
安装  1 软件包

总下载：408 k
安装大小：506 M
确定吗？[y/N]： y
下载软件包：
wps-office-10.1.0.5503-1.a20p2.net.x86_64.rpm                                  22 kB/s | 408 kB     00:18    
--------------------------------------------------------------------------------------------------------------
总计                                                                           22 kB/s | 408 kB     00:18     
运行事务检查
事务检查成功。
运行事务测试
事务测试成功。
运行事务
^C初始化下载: http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5503~a20p2_x86_64.tar.xz
HTTP/1.0 404 Not Found
初始化下载: http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5503~a20p2_x86_64.tar.xz
HTTP/1.1 404 Not Found
初始化下载: http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5503~a20p2_x86_64.tar.xz
HTTP/1.0 404 Not Found

错误：%prein(wps-office-10.1.0.5503-1.a20p2.net.x86_64) 脚本执行失败，捕捉到信号： 2
Error in PREIN scriptlet in rpm package wps-office
Error in PREIN scriptlet in rpm package wps-office
```

手动在浏览器打开这个网址也下不了，一样是404，是不是下载的网址变了？

**Comment by ghost** [comment]
Thanks for your report.

我刚才去 [wps community 官网](http://wps-community.org/downloads) 查了下：

> Due to some reasons, all of the old version of WPS Office for Linux Community is down, we will push a new version as soon as possible. (2016/06/02)

感觉意思是说现在无法下载安装了，只能等他们发布新版。

**Comment by simon-ding** [comment]
我也看到这个了，谢谢！

**Comment by 1dot75cm** [comment]
文件名先列在这：
[wps-office_10.1.0.5503~a20p2_i386.deb](http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5503~a20p2_i386.deb)
[wps-office_10.1.0.5503~a20p2_amd64.deb](http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5503~a20p2_amd64.deb)
[wps-office-10.1.0.5503-1.a20p2.x86_64.rpm](http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office-10.1.0.5503-1.a20p2.x86_64.rpm)
[wps-office-10.1.0.5503-1.a20p2.i686.rpm](http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office-10.1.0.5503-1.a20p2.i686.rpm)
[wps-office_10.1.0.5503~a20p2_x86_64.tar.xz](http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5503~a20p2_x86_64.tar.xz)
[wps-office_10.1.0.5503~a20p2_x86.tar.xz](http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5503~a20p2_x86.tar.xz)

**Comment by 1dot75cm** [comment]
已缓存文件至服务器， 可以下载了，修复该问题。 @cgh0st  @nrechn
