### ISSUE TITLE
配置了FZUG还是无法下载软件

### ISSUE THREAD

**Issue by feverrun** [FZUG/repo#12]
Error: package deepin-movie-2.2.2-1.git53adfc6.fc22.noarch requires qtav-qml-module, but none of the providers can be installed

**Comment by 1dot75cm** [comment]
清除一下 dnf 缓存，然后重试。

```
\$ sudo dnf clean all
```

另外，http://repo.fdzh.org/FZUG/22/ 直接下载包速率多少？

**Comment by tvvocold** [comment]
人多时还是慢，要不我们转移到七牛云 CDN？
Update:
七牛云那边未备案不好推进。目前已启用了 CF 的 cache everything 功能，即软件包由 CF 分发，虽然慢但可保证每个人的下载速度都在 60kbps + 。
Update:
由于七牛已提供赞助，已关闭 CF 加速。

**Comment by tvvocold** [comment]
Update:
目前可以通过七牛提供的国内镜像进行下载 http://dn-repo.qbox.me （速度不错，但需要手动修改地址）
@1dot75cm ，请把 chrome rewrite 到这个节点吧 ，减轻服务器压力：）

**Comment by tvvocold** [comment]
Thx to @1dot75cm , 转发成功。 chrome 下载转发到 qiniu 云储存后，服务器压力减轻不少。
