### ISSUE TITLE
atom/tree-view does not work

### ISSUE THREAD

**Issue by alex94cp** [FZUG/repo#120]
The tree-view component [fails](https://github.com/atom/tree-view/issues/863#issuecomment-224343109) with this version of atom. Maybe electron version is more recent than atom expects, could we have some help [here](https://github.com/atom/tree-view/issues/863#issuecomment-224343109) please?

**Comment by 1dot75cm** [comment]
Thanks report. This information is important. @alex94puchades

**Comment by alex94cp** [comment]
I just updated atom to v1.8.0, still same issue

**Comment by 1dot75cm** [comment]
Hi @alex94puchades 
How to reproduce this issue? I did not have this problem. Please list the plugin version.

```
$ uname -r
4.5.5-300.fc24.x86_64
$ atom -v
Atom    : 1.8.0
Electron: 1.2.2
Chrome  : 51.0.2704.84
Node    : 6.1.0
$ apm list|grep tree
tree-view@0.205.0
autohide-tree-view@0.25.1
tree-view-finder@0.2.1
tree-view-git-status@0.2.3
```

**Comment by alex94cp** [comment]
Ok, I reinstalled and its working now :sweat_smile: Thank you and sorry for the inconvenience!

**Comment by alex94cp** [comment]
This is driving me crazy! I just got the same issue again. Now it happens "sometimes" when I start atom. Here is an screenshot with the back trace shown:

![screenshot](http://s33.postimg.org/4dt3bkh1r/Captura_de_pantalla_de_2016_06_12_15_03_47.png)

Here is version info:

``` sh
$ uname -r
4.5.5-300.fc24.x86_64
$ atom -v
Atom    : 1.8.0
Electron: 1.2.2
Chrome  : 51.0.2704.84
Node    : 6.1.0
$ apm list|grep tree
├── tree-view@0.205.0
```

**Comment by 1dot75cm** [comment]
Please see https://github.com/FZUG/repo/issues/125  @alex94puchades
