### ISSUE TITLE
chromium安装失败

### ISSUE THREAD

**Issue by liuxiang94** [FZUG/repo#122]
Fedora23下的错误信息
warning: /var/cache/dnf/fedora-chromium-stable-fae8399dc26ced2e/packages/chromium-50.0.2661.94-6.fc23.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 93054260: NOKEY
Curl error (37): Couldn't read a file:// file for file:///etc/pki/rpm-gpg/spot.gpg [Couldn't open file /etc/pki/rpm-gpg/spot.gpg]
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.

**Comment by ghost** [comment]
这是因为 gpg key 挂了，或者你没有导入 spot.gpg 这个文件。
导入 gpg key ：

``` shell
$ sudo wget https://repos.fedorapeople.org/repos/spot/chromium-stable/spot.gpg -P /etc/pki/rpm-gpg/
```

然后重试安装。
<br>
或者直接：

``` shell
$ sudo dnf --nogpgcheck install chromium
```

**Comment by liuxiang94** [comment]
已解决
