### ISSUE TITLE
fcitx-googlepinyin 并不会出现在候选列表中

### ISSUE THREAD

**Issue by Endle** [FZUG/repo#123]
我安装了社区源的 `fcitx-googlepinyin`
![2016-06-14 08-58-38](https://cloud.githubusercontent.com/assets/3221521/16028226/e2d78e4c-320f-11e6-9d27-d9abcceae21b.png)
在添加输入法时，找不到google拼音

> $ ls /usr/share/fcitx/inputmethod
> pinyin.conf  shuangpin.conf
> $ cat /usr/share/fcitx/addon/fcitx-googlepinyin.conf 
> [Addon]
> Name=fcitx-googlepinyin
> GeneralName=Google Pinyin
> GeneralName[de]=Google Pinyin
> GeneralName[ja]=Google Pinyin
> GeneralName[zh_CN]=Google 拼音
> GeneralName[zh_TW]=Google 拼音
> GeneralName[vi]=Google Pinyin
> Comment=Wrapper of Google Pinyin on Android
> Comment[de]=Wrapper von Google Pinyin für Android
> Comment[ja]=Androidで動くGoogle Pinyinのラッパーです
> Comment[zh_CN]=Android 上的 Google 拼音的封装
> Comment[zh_TW]=Android 上的 Google 拼音的封裝
> Comment[vi]=Bộ Google Pinyin trên Android
> Category=InputMethod
> Enabled=True
> Library=fcitx-googlepinyin.so
> Type=SharedLibrary
> IMRegisterMethod=ConfigFile

看了一下 [spec](https://github.com/FZUG/repo/blob/master/rpms/fcitx/fcitx-googlepinyin.spec#L46)，有 `%{_datadir}/fcitx/inputmethod/*.conf`，那为什么没有装上呢？
谢谢

**Comment by 1dot75cm** [comment]
已修复该问题， 见 https://github.com/FZUG/repo/issues/71#issuecomment-216835565
