### ISSUE TITLE
请求打包 isatapd

### ISSUE THREAD

**Issue by Endle** [FZUG/repo#126]
在校园网，这是连ipv6的必要工具
我写的spec，希望能做一些参考
[isatapd.spec.txt](https://github.com/FZUG/repo/files/317744/isatapd.spec.txt)

**Comment by 1dot75cm** [comment]
怎么不直接提交 PR？ @Endle

**Comment by 1dot75cm** [comment]
Please test @Endle

**Comment by Endle** [comment]
2016-06-16 18:06 GMT+08:00 1dot75cm notifications@github.com:

> 怎么不直接提交 PR？

因为之前看到的所有提交都是你做的，所以我以为 workflow 是把 spec 给你，然后你统一 commit 上去

现在我装上了 fzug-testing 里的 isatapd，谢谢

## 

Have a nice day!
Zhenbo Li

**Comment by 1dot75cm** [comment]
只要注意一点：Source 字段要使用 URL，这样类似 [dnf-plugin-lait](https://github.com/1dot75cm/dnf-plugin-lait) 的工具可以直接下载源码，从 spec 构建 rpm @Endle

**Comment by Endle** [comment]
好的，谢谢提醒

2016-06-17 17:53 GMT+08:00 1dot75cm notifications@github.com:

> 只要注意一点：Source 字段要使用 URL，这样类似 dnf-plugin-lait
> https://github.com/1dot75cm/dnf-plugin-lait 的工具可以直接下载源码，从 spec 构建 rpm
> @Endle https://github.com/Endle
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/FZUG/repo/issues/126#issuecomment-226729241, or mute
> the thread
> https://github.com/notifications/unsubscribe/ADEoEZiN97hOHoyu8MoDJaY_AyjvP40Dks5qMm63gaJpZM4I3C58
> .

## 

Have a nice day!
Zhenbo Li
