### ISSUE TITLE
Cannot install wine-qq

### ISSUE THREAD

**Issue by tangbao** [FZUG/repo#128]
安装wineqq时卡死在运行事务上。。

运行事务检查
事务检查成功。
运行事务测试
事务测试成功。
运行事务
^C初始化下载: http://packages.deepin.com/deepin/pool/non-free/d/deepinwine-qqintl/wine-qqintl_0.1.3-2_i386.deb
HTTP/1.1 404 Not Found
初始化下载: http://packages.deepin.com/deepin/pool/non-free/d/deepinwine-qqintl/wine-qqintl_0.1.3-2_i386.deb
HTTP/1.1 404 Not Found
初始化下载: http://packages.deepin.com/deepin/pool/non-free/d/deepinwine-qqintl/wine-qqintl_0.1.3-2_i386.deb
HTTP/1.1 404 Not Found
错误：%prein(wine-qqintl-0.1.3-2.net.x86_64) 脚本执行失败，捕捉到信号： 2
Error in PREIN scriptlet in rpm package wine-qqintl
Error in PREIN scriptlet in rpm package wine-qqintl

**Comment by Endle** [comment]
这个包被deepin撤下了。。。
@1dot75cm 如果我们自己打包，而不是依赖深度的包呢？

**Comment by 1dot75cm** [comment]
之前已解决过该问题， 请查看 #102 。@Endle @tangbaobao

**Comment by 1dot75cm** [comment]
如有问题请回复。 Close issue. @tangbaobao
