### ISSUE TITLE
electron changes to dnf.conf broke distro upgrade from 23 to 24

### ISSUE THREAD

**Issue by muayyad-alsadi** [FZUG/repo#129]
hi,
the following line was added by your electron copr to `/etc/dnf/dnf.conf`

```
installonlypkgs=electron
```

which cased the following error

```
Error: The operation would result in removing the booted kernel: kernel-core-4.5.7-200.fc23.i686.
```

the reason is that kernel is not longer protected by `installonlypkgs`

**Comment by 1dot75cm** [comment]
It works. But i think direct change the main config file (`/etc/dnf/dnf.conf`), It's not a good idea.
However, I have no choice. @muayyad-alsadi 

```
installonlypkgs=kernel kernel-modules electron
```

The `installonlypkgs` option is defined in [dnf/const.py.in#L28](https://github.com/rpm-software-management/dnf/blob/master/dnf/const.py.in#L28).

java package is a smart solution. The `java-1.8.0-openjdk-1.8.0.92` and `java-1.7.0-openjdk-1.7.0` are different packages. But `electron-1.2.3-1` and `electron-0.37.8-1` are same packages.

**Comment by muayyad-alsadi** [comment]
I believe you should not use this option. Just like different versions and
providers of java

Just have a "provides" to the generic name and name you package differently
for example

electron-legacy provides electron
electron-1xx provides electron

**Comment by 1dot75cm** [comment]
The rpm has been updated in Copr([363700](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/363700/) and [363701](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/363701/)). Please test it. Thanks. @muayyad-alsadi 

PS: I just tested pass in Fedora 24.

**Comment by allanlewis** [comment]
~~@1dot75cm, can you please build these packages for Fedora 23 as well?~~ Sorry, I can see them now, forgot to update my cache.

**Comment by muayyad-alsadi** [comment]
I'm using fedora 24, and it works fine.

**Comment by 1dot75cm** [comment]
This package is build pass with Fedora 23 in `mosquito/atom` repository, but no test. If you have free time, please help me test. Thanks @allanlewis.

BTW, You may need to manually remove the following line in `dnf.conf` and `yum.conf`, because before the package edit them.

```
installonlypkgs=electron
```

**Comment by allanlewis** [comment]
@1dot75cm, I've installed `atom-1.8.0-2.gitf89b273.fc23` and it works fine; `dnf` doesn't report any conflicts. One issue I did notice is that if I install the upstream RPM and then "upgrade" to yours, the link in the Gnome menu isn't updated properly; I worked around this by reinstalling the upstream RPM, then uninstalling it, then installing your RPM. (This probably isn't related to the issue at hand.)
