### ISSUE TITLE
sogou pinyin

### ISSUE THREAD

**Issue by sunznx** [FZUG/repo#13]
how to install sogou pinyin in fedora22 T_T ...

**Comment by tvvocold** [comment]
See http://hack.fdzh.org/item?id=593
:smile:

**Comment by sunznx** [comment]
fail T_T

**Comment by sunznx** [comment]
成功了 dnf install sogoupinyin fcitx-qt5 im-chooser redhat-lsb dpkg -y

**Comment by tvvocold** [comment]
感谢反馈！

**Comment by Endle** [comment]
[**@tvvocold**](https://github.com/tvvocold) commented on [21 Jul 2015, 14:15 GMT+8](https://github.com/FZUG/repo/issues/13#issuecomment-123178948):

> 感谢反馈！

这是否暴露了包依赖的问题呢？

**Comment by tvvocold** [comment]
@1dot75cm

**Comment by sunznx** [comment]
有个 问题,  有道词典和 emacs中无法输入, 在虚拟终端下 
emacs &
youdao-dict&
才可以输入..

**Comment by 1dot75cm** [comment]
dnf install sogoupinyin fcitx-qt5 即可，其他的都不需要。如果不使用 qt5 程序，fcitx-qt5 也不需要。
