### ISSUE TITLE
push rpm to free repo from testing repo

### ISSUE THREAD

**Issue by 1dot75cm** [FZUG/repo#130]
根据 https://github.com/FZUG/repo/pull/121#issuecomment-227489920 的想法。昨天，测试了一下 [Hubot (GitHub robot)](https://hubot.github.com), 可以实现从 chat 控制服务器。 @Endle

现在构想的 karma 功能，包含两个方面：
- [x] 在 Gitter 投票， 需要申请 Gitter 权限； @sztsian  finish by https://github.com/1dot75cm/fzugbot/commit/5a1b3dbb7888378a6e6942f6a1a8ec6d4459085b
- [ ] 在 issue 投票， 通过 webhook 实现；
  
  > karma +1 PKGNAME @fzugbot
- [ ] testing 源一段时间没问题就推到 stable。

**Comment by sztsian** [comment]
Permission granted.

**Comment by 1dot75cm** [comment]
bot 已提交至 [1dot75cm/fzugbot](https://github.com/1dot75cm/fzugbot)，功能慢慢来。在 Gitter 使用 `/help` 查看帮助。

微软有小娜， teletram 有群组娘， 咱们叫什么名字好呢？ @FZUG/repo

**Comment by 1dot75cm** [comment]
Gitter 权限是不是应该允许所有人加入，这样才可以让更多人参与讨论。 机器人只提供 投票和一些查询功能。应该没什么问题。@sztsian

**Comment by 1dot75cm** [comment]
已实现 gitter 投票功能，各位有测试好的包，可以在 gitter 输入以下指令：

```
/karma <+1|-1> <pkgname>
```

2 票即可将包推送至 fzug-free 源。 @alick  @nrechn  @sztsian  @Endle

**Comment by 1dot75cm** [comment]
> 我觉得我们可以更懒一点：testing 里一周后没问题就推到 stable。事实上 Fedora Bodhi 也是这样做的。

确实这样更省事。 @alick

**Comment by ghost** [comment]
@1dot75cm 投票功能挺赞的说。话说是不是2票就能自动 move 进相应的 free 和 nonfree 目录？
<br>

> 我觉得我们可以更懒一点：testing 里一周后没问题就推到 stable。事实上 Fedora Bodhi 也是这样做的。

我觉得这个思路可以和投票同时使用，不过觉得一周时间可能有点短。看了下 [FZUG.repo](https://github.com/FZUG/repo/blob/master/repos/FZUG.repo) 默认是开 fzug-testing 的，所以倒是建议fzug-testing 里一个月没有问题的包自动推到 stable；在此期间自动把获得两票的包推到 stable。

**Comment by 1dot75cm** [comment]
> 话说是不是2票就能自动 move 进相应的 free 和 nonfree 目录？

目前是都移动到 `free` 源

> 我觉得这个思路可以和投票同时使用，不过觉得一周时间可能有点短。看了下 FZUG.repo 默认是开 fzug-testing 的，所以倒是建议fzug-testing 里一个月没有问题的包自动推到 stable；在此期间自动把获得两票的包推到 stable。

对，这个可以有。 我加上。@nrechn

**Comment by alick** [comment]
是不是已经完成了，可以关闭了？

**Comment by alick** [comment]
回头来看，是否本身就不必要单列一个 testing 仓库？目前其实区分 free/ nonfree/ 都是有 bug 的

**Comment by alick** [comment]
建议目前关闭，以后有需求时重开
