### ISSUE TITLE
bcloud blocks system upgrade from Fedora 23 to Fedora 24

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#134]
During sudo dnf system-upgrade download --releasever=24 , it reports as following.
Error: package bcloud-3.8.2-3.git4b54e0f.fc23.noarch requires python(abi) = 3.4, but none of the providers can be installed.

**Comment by ghost** [comment]
把 bloud 更新到 3.8.2-4 然后再试试？我在 Fedora 24 上直接安装 bcloud 3.8.2-4 没有任何问题。

话说你系统更新用的命令好奇怪呀。我系统更新下一个版本，一直用的这个：

``` shell
# rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-24-$(uname -i)
# dnf upgrade
# dnf clean all
# dnf --releasever=24 --setopt=deltarpm=false distro-sync
```

**Comment by sztsian** [comment]
https://fedoramagazine.org/upgrading-fedora-23-workstation-to-fedora-24/

第一步已经更新所有包拉，bcloud并没有更新（当然我没有使用fzug-testing）。

**Comment by ghost** [comment]
看来你需要开 fzug 的 testing 了 :worried: 。目前 FZUG 的 F24 版本的包都在 testing 里面，free 和 nonfree 的 F24 基本上还是空的。然后 F24 上用 FZUG 的 F23 的包也不妥当，毕竟跨版本了会有依赖问题。

**Comment by 1dot75cm** [comment]
@sztsian  如果24里面的包测试没问题了，就可以在gitter 用 karma 投票了，2票就可以发布到free 源。  另外，一般升级系统应该禁用第三方源， 所以解决该问题只要测试发布包就好了。

**Comment by alick** [comment]
其实我不太清楚：禁用第三方源后，原来从第三方源安装的软件（比如 bcloud）是不是仍会阻止升级，需要加 `--allowerasing` 允许删掉它？

**Comment by 1dot75cm** [comment]
我是用 dnf 直接升级的（方法见：[升级Fedora](https://github.com/FZUG/repo/wiki/%E5%8D%87%E7%BA%A7-Fedora#%E6%89%8B%E5%8A%A8%E5%8D%87%E7%BA%A7)）
禁用第三方源，该源的包就不会阻止升级；不过升级完成后，需要手动酌情处理这些包。 @alick

**Comment by alick** [comment]
@1dot75cm 怎么叫“手动酌情”？愿闻其详

**Comment by alick** [comment]
@sztsian 启用 testing 了是否就可以了？

**Comment by 1dot75cm** [comment]
> 怎么叫“手动酌情”？愿闻其详

即搜索过滤这些老版本的包，如果不能用，将其卸载 和/或 更新至新版本。 @alick

**Comment by alick** [comment]
所以解决方案是：
1. （首选）升级系统前禁用第三方软件源，包括 FZUG 的 copr 源。
2. 启用 FZUG testing 源。（不推荐）
