### ISSUE TITLE
Continue support Fedora 21?

### ISSUE THREAD

**Issue by hitzhangjie** [FZUG/repo#136]
Can FZUG continue support Fedora 21 ?

**Comment by hitzhangjie** [comment]
Now I use fzug for fedora 22 instead. It works.

**Comment by 1dot75cm** [comment]
Fedora 22 will officially enter End Of Life (EOL) status on July 19th, 2016. Please update system by `dnf system-upgrade`, See [升级 Fedora](https://github.com/FZUG/repo/wiki/%E5%8D%87%E7%BA%A7-Fedora) @hitzhangjie

**Comment by 1dot75cm** [comment]
Fedora 21 is End Of Life,  close this issue.
