### ISSUE TITLE
关于 rpmfusion_fzug 如何处理

### ISSUE THREAD

**Issue by ghost** [FZUG/repo#137]
当时 F24 快发布前就着手 rebuild for F24 了。那个时候 RPMFusion 尚未支持 F24，所以有对 RPMFusion 的 spec 打包文件进行修改然后重新打包从而形成了 rpmfusion_fzug 。

刚才看了下，[RPMFusion F24](http://download1.rpmfusion.org/free/fedora/releases/24/Everything/x86_64/os/Packages/) 已经有正式的源了。**那么是舍弃 rpmfusion_fzug 然后基于 [RPMFusion F24](http://download1.rpmfusion.org/free/fedora/releases/24/Everything/x86_64/os/Packages/) 重新打包？还是保留 rpmfusion_fzug ？** 如果保留的话倒是建议排查出哪些  rpmfusion_fzug 里的包是 fzug 依赖的，然后把它们直接合并到 fzug 。

@1dot75cm

**Comment by ghost** [comment]
话说有空我把 “FZUG Packages Massive Rebuild for F24” 列表再检查一遍；然后加上 rpmfusion_fzug 的处理，差不多就能把 #100 搞定了 :smile:

**Comment by 1dot75cm** [comment]
> 刚才看了下，RPMFusion F24 已经有正式的源了。那么是舍弃 rpmfusion_fzug 然后基于 RPMFusion F24 重新打包？还是保留 rpmfusion_fzug ？

`rpmfusion_fzug` 的包兼容 `RPMFusion F24`（比如 ffmpeg），不用重新编译就可以用。`rpmfusion_fzug` 的包可以先放那，降低维护的优先级（有需要再更新）。至于源里的依赖，为了兼容 RPMFusion， 还是直接用它的，不合并到 FZUG 单独维护。 @nrechn 

> 话说有空我把 “FZUG Packages Massive Rebuild for F24” 列表再检查一遍；然后加上 rpmfusion_fzug 的处理，差不多就能把 #100 搞定了

辛苦了，有时间窝看看 RPMFusion 都更新了什么，那些失败的应该都可以解决。 然后就可以把 #100 搞定了。

**Comment by sztsian** [comment]
现在 FZUG 源已经不再提供 RPMFusion 中存在的包。
