### ISSUE TITLE
VSCode icon

### ISSUE THREAD

**Issue by sudoforge** [FZUG/repo#138]
The visual studio code icon is incorrect. [Here's a PNG of the correct icon that works well.](http://mahpahh.com/content/images/2015/05/vso.png)

**Comment by 1dot75cm** [comment]
I think offical shoud provide a PNG of correct icon in Github. I don't know if i can [download and distribute this icon](http://mahpahh.com/content/images/2015/05/vso.png). @bddenhartog

**Comment by sudoforge** [comment]
@1dot75cm In retrospect, it looks like the vscode repo accepted a patch that changed the icon for "OSS Distros". I'll take the issue with them :)
