### ISSUE TITLE
imsettings-info 

### ISSUE THREAD

**Issue by RanchoCooper** [FZUG/repo#139]
I can't find `imsettings-info` command in my new arch (XFCE4)

**Comment by 1dot75cm** [comment]
Please try to install `imsettings`. What about this issue? @RanchoCooper 

```
$ rpm -qf /usr/bin/imsettings-info
imsettings-1.7.1-1.fc24.x86_64
```

**Comment by alick** [comment]
By arch you mean Archlinux? AFAIK imsettings is a Fedora (and its
derivatives) specific tool.

On Sun, Jul 10, 2016 at 8:33 AM, Rancho notifications@github.com wrote:

> I can't find imsettings-info command in my new arch (XFCE4)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/FZUG/repo/issues/139, or mute the thread
> https://github.com/notifications/unsubscribe/AA5AL_ez2GiqI2McQhczbZRkInfrWhKwks5qUPS1gaJpZM4JI1f3
> .

## 

Regards,
Alick

**Comment by alick** [comment]
ping @RanchoCooper

**Comment by 1dot75cm** [comment]
ping @RanchoCooper

**Comment by alick** [comment]
Will close if no response within 1 day.

**Comment by RanchoCooper** [comment]
sorry, for my delay response

input work well after setting my .xinitrc correctly

thank you guys

**Comment by 1dot75cm** [comment]
Maybe you say "input method(Fcitx) cannot work with XFCE4"?  @RanchoCooper 
Set `GTK_IM_MODULE`, `QT_IM_MODULE`, `XMODIFIERS` variable in your `~/.xinitrc` file.

**Comment by alick** [comment]
Closing as fixed
