### ISSUE TITLE
vscode is not offered as "open with"

### ISSUE THREAD

**Issue by muayyad-alsadi** [FZUG/repo#141]
vscode is not listed in open with unlike atom

![screenshot from 2016-07-11 16-11-30](https://cloud.githubusercontent.com/assets/1312683/16731702/3124d9ec-4782-11e6-808b-fb5be978b4f2.png)

**Comment by 1dot75cm** [comment]
Fixed this issue. @muayyad-alsadi 
The package is building on Copr [384155](https://copr.fedorainfracloud.org/coprs/mosquito/vscode/build/384155/), please test later.

**Comment by muayyad-alsadi** [comment]
I got an update from copr (not that build) and it works fine

```
[root@localhost ~]# rpm -q vscode
vscode-1.3.1-1.fc24.x86_64
```
