### ISSUE TITLE
wechat 打不开

### ISSUE THREAD

**Issue by sunznx** [FZUG/repo#142]
一直停留在启动页面 f24

**Comment by 1dot75cm** [comment]
请确认包版本： @sunznx 
- wechat-1.3.0-3.git5058348.fc24.x86_64.rpm
- electron-1.2.3-3.prebuilt.fc24  （用0.37.8， 1.2.0都可以启动）

**Comment by sunznx** [comment]
一直在 starting app，难道我打开方式不对？

**Comment by 1dot75cm** [comment]
[wechat-1.3.0-3.git5058348.fc24.x86_64.rpm](https://repo.fdzh.org/FZUG/testing/24/x86_64/wechat-1.3.0-3.git5058348.fc24.x86_64.rpm) 该版本已经解决该问题，请配合 `electron 0.37.8` 或 `1.2.7` 再测试一下。 @sunznx
