### ISSUE TITLE
请问 Fedora 24 的sougoupinyin源在哪里？

### ISSUE THREAD

**Issue by marswong** [FZUG/repo#143]
还有在源列表里面找不到：https://repo.fdzh.org/FZUG/rpmfusion/24/x86_64/

**Comment by 1dot75cm** [comment]
https://repo.fdzh.org/FZUG/testing/24/x86_64/sogoupinyin-2.0.0.0078-1.fc24.x86_64.rpm
@OneNewLife

**Comment by marswong** [comment]
请更新一下那个列表吧谢谢，好多包看不到

**Comment by 1dot75cm** [comment]
你是说 repo.fdzh.org 主页的列表？ @OneNewLife

**Comment by marswong** [comment]
按版本浏览里面 @1dot75cm

**Comment by 1dot75cm** [comment]
不是直接下载 FZUG.repo 就可以了吗？ 24 再添加上 https://repo.fdzh.org/FZUG/rpmfusion/ 源，根本不需要去网页上找包，直接用 `dnf search`。 @OneNewLife

**Comment by marswong** [comment]
好的，谢谢
