### ISSUE TITLE
 freshplayerplugin安装失败

### ISSUE THREAD

**Issue by liuxiang94** [FZUG/repo#144]
错误：nothing provides libavcodec.so.56()(64bit) needed by freshplayerplugin-0.3.5-1.git51946f8.fc24.x86_64

**Comment by ghost** [comment]
正在准备重新打包源里的freshplayerplugin，请稍等。

PS:
@1dot75cm ，请让 cibuild 重新打包 freshplayerplugin，即可解决此 issue 。
