### ISSUE TITLE
豆瓣FM怎么就跪了。。。

### ISSUE THREAD

**Issue by marswong** [FZUG/repo#145]
上午刚听得 high 起，怎么下午就跪了？是被**豆瓣**封了么？

**Comment by ghost** [comment]
豆瓣 fm 使用正常呀。音乐播放也正常。看到 issue 之后立马安装然后尝试了。
![snapshot3](https://cloud.githubusercontent.com/assets/13869410/16867603/09c3d51a-4ab6-11e6-8cf9-0e3524ecffa9.png)

**Comment by marswong** [comment]
啊？我已经重装两次啦，什么原因？一直在loading @nrechn

**Comment by ghost** [comment]
> 啊？我已经重装两次啦，什么原因？

泥是哪里出错了？我这里都正常的说。

**Comment by marswong** [comment]
请问日志在哪个文件夹？我想看看logs谢谢 @nrechn

**Comment by ghost** [comment]
> 请问日志在哪个文件夹？

这货自己貌似没有日志？

``` bash
root# find / -name "*douban*"
/var/lib/dnf/yumdb/d/5fc6a9177ab3991e69dc4b4dcadfdc14a664adfa-doubanfm-qt-2.2-2.git826e8a2.fc24-x86_64
/usr/bin/doubanfm-qt
/usr/share/licenses/doubanfm-qt
/usr/share/doc/doubanfm-qt
/usr/share/applications/doubanfm-qt.desktop
/usr/share/icons/doubanfm-qt.png
```

**Comment by 1dot75cm** [comment]
我这里没问题呀，换曲不要太频繁。

**Comment by marswong** [comment]
是不是频繁换曲会被豆瓣封ip？ @1dot75cm

**Comment by marswong** [comment]
极度怀疑真的是被封IP了，等候半天又给我开放了，真坑。。。

**Comment by ghost** [comment]
会不会是因为dns挂了一段时间？窝这里就经常dns原因导致上不了百度；
或者豆瓣被运营商封了之类的？窝这里网易云音乐已经被封，music.163.com 根本就上不去也ping不通的说。

**Comment by marswong** [comment]
应该不是DNS的原因，我这里教育网的DNS除了被墙的站点其它的站点一直都很正常，而且我在windows上是可以正常使用官方的豆瓣FM的。极有可能是豆瓣恶心的防御机制 @nrechn

**Comment by ghost** [comment]
233333 换取太频繁被豆瓣当成抓歌了麽~
