### ISSUE TITLE
网页上的软件包列表不是最新

### ISSUE THREAD

**Issue by alick** [FZUG/repo#149]
如题，网页上的软件包列表似乎没有随着包的加入/删除而更新。

**Comment by 1dot75cm** [comment]
似乎需要在主页动态载入这些包信息。用 Flask 貌似不是很复杂。

**Comment by alick** [comment]
不知道能否弄个脚本自动更新。眼下我觉得可以在 master 提交了新包后手动在 page 分支再做一个提交。

**Comment by alick** [comment]
切换到 gh-pages 分支的话，可能只能用静态页面了，这样就主要靠大家添加/删除时自觉在 gh-pages 分支做相应提交了

**Comment by alick** [comment]
我根据软件仓库里的rpm文件更新过一轮，后面就靠大家自觉增删吧： https://github.com/FZUG/repo/wiki/%E4%B8%AD%E6%96%87%E7%A4%BE%E5%8C%BA%E6%BA%90%E6%89%93%E5%8C%85%E6%8C%87%E5%8D%97
