### ISSUE TITLE
Custom kernel modules

### ISSUE THREAD

**Issue by cicku** [FZUG/repo#15]
Plan for:
- [ ] Broadcom wireless driver being used by Apple products.
- [ ] PAX
- [ ] Directfb

Ideas welcome.

**Comment by sztsian** [comment]
Help me fix the spec rpms/SPECS/mt7601u/dkms-mt7601u.spec if you would like to. It is ugly written as this is my first try.

**Comment by gbraad** [comment]
the Broadcom drivers are already available at RPM Fusion IIRC, called
kmod-wl or akmod-wl

On Tue, Jul 28, 2015 at 10:56 PM, Zamir SUN notifications@github.com
wrote:

> Help me fix the spec rpms/SPECS/mt7601u/dkms-mt7601u.spec if you would
> like to
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FZUG/repo/issues/15#issuecomment-125638493.

## 

Gerard Braad — 吉拉德
   F/OSS & IT Consultant in Beijing
   http://gbraad.nl  gpg: 0x592CFE75

**Comment by alick** [comment]
flag 马上快一年了哈

**Comment by alick** [comment]
@cicku updates?

**Comment by alick** [comment]
视为放弃
