### ISSUE TITLE
网易云音乐在4k屏下字体好小！

### ISSUE THREAD

**Issue by ljhui** [FZUG/repo#150]
如题，Fedora24，笔记本是4k屏，装上网易云音乐后字体好小，界面放大后字体不随着放大，在设置里面也没找到设置字体大小的选项，其他功能正常，有没有办法解决？

**Comment by alick** [comment]
可能是上游BUG。

你的桌面环境是 GNOME 还是 KDE？也许有助于排查问题。

**Comment by ljhui** [comment]
gnome版本的

**Comment by 1dot75cm** [comment]
已更新 1.0.0， 不知该版本是否对解决该问题有帮助。@ljhui

**Comment by ljhui** [comment]
@1dot75cm ，老样子，没什么改进

**Comment by caoli5288** [comment]
这问题应该去上游反馈的说

**Comment by blsyng** [comment]
试试加这个参数，可以把1.5改成2或者其他你觉得合适的数值
netease-cloud-music --force-device-scale-factor=1.5 %U

**Comment by rutiannnn** [comment]
每次开启都要设置这个参数么？好麻烦

**Comment by blsyng** [comment]
嫌麻烦了的话可以改desktop文件

/usr/share/applications/netease-cloud-music.desktop

Exec=netease-cloud-music --force-device-scale-factor=1.5 %U

**Comment by ljhui** [comment]
@blsyng ,添加参数可以解决这个问题，不过每次打开网易的初始界面比较小，界面上的文字内容都缩在一起，不得不手动调整大小，每次启动都要调整，比较麻烦，不能记忆我调整后的界面尺寸，有没有启动参数指定网易云音乐启动时的初始界面大小

**Comment by alick** [comment]
上游BUG，请向上游反馈问题。更多人向上游反馈更有可能被关注。

![_-_2017-02-26_12 28 11](https://cloud.githubusercontent.com/assets/933935/23342397/1699c734-fc1f-11e6-8986-6aeaf1199bc6.png)

**Comment by robberphex** [comment]
发现即使设置了`--force-device-scale-factor=2`参数，但是新窗口的大小没有缩放（但是内容却放大了），导致没法用（比如没法登陆）。如图：
![netease music](https://user-images.githubusercontent.com/1926185/27516711-c279676e-59f1-11e7-87d5-e69d6e16d1b1.png)
