### ISSUE TITLE
atom - find-and-replace:select-next is slow

### ISSUE THREAD

**Issue by sudoforge** [FZUG/repo#151]
I have been experiencing slow (and/or inconsistent), unresponsive execution of `find-and-replace:select-next`. This occurs **only when using the copr repository to install atom**. This issue does not occur when installing atom using a provided `.rpm` from the [official github releases page](https://github.com/atom/atom/releases).

Pressing `ctrl-d` (the default keybinding; holding `ctrl` and pressing `d`) in rapid succession results in inconsistent execution of the command. Note that this does not seem to be _slow_ -- the calls are not laggy or delayed -- rather, some are skipped entirely, while others are not. Manually waiting about a second in between keybinding executions, or holding the keybinding down, results in a consistent experience.

CPU profiles attached. Note that the extensions were changed to `.txt` so they could be uploaded.

[rapid-pressing.txt](https://github.com/atom/find-and-replace/files/371442/rapid-pressing.txt)
[holding.txt](https://github.com/atom/find-and-replace/files/371440/holding.txt)
[waiting-in-between.txt](https://github.com/atom/find-and-replace/files/371441/waiting-in-between.txt)

**Versions**

```
find-and-replace: 0.199.0
atom            : 1.8.0
electron        : 0.36.8
chrome          : 47.0.2526.110
node            : 5.1.1
fedora          : 24
```

**Comment by yajo** [comment]
Same here.

**Comment by 1dot75cm** [comment]
Hi @bddenhartog 
Please update electron to `0.37.8`, and test again. 

```
$ atom -v
Atom    : 1.8.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ apm list
find-and-replace@0.199.0
```

Make sure install the following packages:
- [electron-legacy-0.37.8-2.prebuilt.fc24.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/mosquito/atom/fedora-24-x86_64/00363700-electron-legacy/electron-legacy-0.37.8-2.prebuilt.fc24.x86_64.rpm)
- [nodejs-atom-package-manager-1.10.0-6.git87b4bcb.fc24.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/mosquito/atom/fedora-24-x86_64/00347481-nodejs-atom-package-manager/nodejs-atom-package-manager-1.10.0-6.git87b4bcb.fc24.x86_64.rpm)
- [atom-1.8.0-2.gitf89b273.fc24.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/mosquito/atom/fedora-24-x86_64/00346724-atom/atom-1.8.0-2.gitf89b273.fc24.x86_64.rpm)

**Comment by yajo** [comment]
Still happening.

```
$ atom -v
Atom    : 1.8.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
~
$ apm list | grep find-and-replace
├── find-and-replace@0.199.0
├── minimap-find-and-replace@4.5.1
~
$ rpm -q electron electron-legacy nodejs-atom-package-manager atom
electron-1.2.3-3.prebuilt.fc23.x86_64
electron-legacy-0.37.8-2.prebuilt.fc23.x86_64
nodejs-atom-package-manager-1.10.0-6.git87b4bcb.fc24.x86_64
atom-1.8.0-2.gitf89b273.fc24.x86_64
```

**Comment by sudoforge** [comment]
@Yajo is this still an issue? I no longer use Atom, and would like to close the issue if it's been resolved.

**Comment by yajo** [comment]
Seems fixed.
