### ISSUE TITLE
Package `vscode` is outdated

### ISSUE THREAD

**Issue by monkey2000** [FZUG/repo#153]

**Comment by ghost** [comment]
Package `vscode-1.3.1-1.fc24.x86_64.rpm` was pushed into FZUG testing repository in Jul 15. I suppose 1.3.1 should be the latest version.

**Comment by monkey2000** [comment]
```
nothing provides electron = 1.2.7 needed by vscode-1.3.1-1.fc24.x86_64
```

It looks like the `electron` is outdated.

**Comment by 1dot75cm** [comment]
Package [electron-1.2.7](https://repo.fdzh.org/FZUG/testing/24/x86_64/electron-1.2.7-1.prebuilt.fc24.x86_64.rpm) was pushed to FZUG testing repository. @monkey2000
