### ISSUE TITLE
Apm dialogs is broken

### ISSUE THREAD

**Issue by paulcarroty** [FZUG/repo#156]
```
apm -v
apm  1.10.0........] - :
npm  3.10.3
node 6.3.1
python 2.7.12
git 2.9.2
$ apm update
Package Updates Available (1)
└── markdown-writer 2.5.0 -> 2.5.1

[..................] - :

Installing markdown-writer@2.5.1 to /home/paul/.atom/packages [.................✓..................] - :

```

Atom 1.9.0.

**Comment by 1dot75cm** [comment]
The `atom-1.11.1` is available in [mosquito/atom/465619](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/465619/). But apm dialogs is still broken. @paulcarroty

**Comment by paulcarroty** [comment]
@1dot75cm  maybe the reason is old `apm`? We use 1.10, the latest is [1.12.7](https://github.com/atom/apm/blob/master/package.json#L4).

**Comment by 1dot75cm** [comment]
Yes, It need to be updated. But i need to review code of `apm`. Because the official package is included the `atom+nodejs(library of atom)  +  apm+node(binary)+nodejs(library of apm)  +  electron(binary)`. So i need to split them. It will take some time. @paulcarroty
