### ISSUE TITLE
求有道云笔记

### ISSUE THREAD

**Issue by 95289527** [FZUG/repo#159]
。。。。
官方没有linux版 不知道能不能实现。。

**Comment by sztsian** [comment]
你好。
社区只能打包已经存在的开源与自由软件。既然有道云笔记没有提供 Linux 版，我们是无能为力的。
如果您熟悉 Wine 并且具有自己排错的能力，那么可以参考 [这里](http://blog.csdn.net/ownfire/article/details/7738786)使用。

**Comment by sunznx** [comment]
dnf install -y epiphany
这是一个浏览器，可以将网页打包成 app
