### ISSUE TITLE
Failed To Initialize ALPM Library

### ISSUE THREAD

**Issue by tharrisone** [FZUG/repo#16]
pacman -Sy  
error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)

I went and grabbed a pacman database and moved it to that folder and still no love. Updated the database but still I get that error.

**Comment by 1dot75cm** [comment]
You should set /etc/pacman.conf， then exec pacman -v -Sy.

```
$ vim /etc/pacman.conf
RootDir     = /opt/arch/
DBPath      = /var/lib/pacman/
LogFile     = /var/log/pacman.log
$ pacman -v
Root      : /opt/arch/
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
```

**Comment by tharrisone** [comment]
I didn't mkdir the /opt/arch directory, its working good now.

**Comment by Endle** [comment]
There is a solution in [reddit](https://www.reddit.com/r/Fedora/comments/3evm2d/use_yaourt_in_fedora/ctk0ngo)


```
1.Make sure you configure /etc/pacman.conf as per the instructions.
2.Manually make the /opt/arch directory
3.Add the line "Architecture = auto" under the [options] section of the conf file.
```

**Comment by 1dot75cm** [comment]
reddit is very nice. thanks @Endle

**Comment by sztsian** [comment]
Close this as the reporter said that it already worked.

**Comment by chitkokooo** [comment]
I found same issue and was resolved by running

#mkinitcpio -p linux
