### ISSUE TITLE
Fedora24 Intel® Dual Band Wireless-AC 8260 无线网卡不能正常工作

### ISSUE THREAD

**Issue by miniyuan** [FZUG/repo#160]
笔记本系统为:Fedora24 cinnamon
无线网卡为: Intel® Dual Band Wireless-AC 8260 
ip addr 能看到网卡，但wifi是off，
不能正常工作，望高手帮忙看看!

**Comment by ghost** [comment]
如果`ip a`能顯示無線網卡信息，就說明驅動是正常的。直接去wifi settings把它打開唄。如果打不開可以試試重啟NetworkManager daemon，或者檢查是否安裝了`NetworkManager-wifi`

**Comment by sztsian** [comment]
噫，这里不是支持论坛。有问题可以发到邮件列表chinese#lists.fedoraproject.org。这里处理的是 FZUG 仓库相关问题。

**Comment by sztsian** [comment]
噫，这里不是支持论坛。有问题可以发到邮件列表chinese#lists.fedoraproject.org。这里处理的是 FZUG 仓库相关问题。
