### ISSUE TITLE
Status of moving F24 packages into stable

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#162]
As I see most of the F24 packages are in testing repo. So do we have any plan or concern moving it into stable?

**Comment by ghost** [comment]
I think we have discussed it in #130 

> - [ ] testing 源一段时间没问题就推到 stable。

It is still waiting to be done and ticked.

**Comment by 1dot75cm** [comment]
I am writing the frontend and backend for this function. @sztsian 
[flasky](https://github.com/1dot75cm/flasky)  It's a test project.

**Comment by 1dot75cm** [comment]
@sztsian @nrechn  The [RPM Update System](https://repo.fdzh.org/blog/tools/updates/?release=F24) is online. You can use follows way to move pkg into stable:
- enter `+1` or `-1` to comment input box (+1 karma need to waiting 2 days, `> +2` karma direct move package); 
- Nothing to do. The package of `testing` need to waiting 2days for move to stable.

**Comment by 1dot75cm** [comment]
It's looks like work fine. Fixes this issue. @sztsian 

Now, waiting time is 7 days ([Code](https://github.com/1dot75cm/flasky/blob/master/config.py#L68)) by environment variable.

**Comment by sztsian** [comment]
Close as FIXED since our update system is working
