### ISSUE TITLE
对 RHEL7或者 CentOS7的支持如何？

### ISSUE THREAD

**Issue by shibingli** [FZUG/repo#167]
如题

**Comment by sztsian** [comment]
hi,
由于社区的人员和硬件条件限制，我们已经停止提供RHEL/CentOS系列的软件包，因此难以确定当前的兼容状况。如果您有能力，可以尝试下载对应 SRPM包自己尝试打包使用。

**Comment by 1dot75cm** [comment]
如果您有能力，并且有时间，可以参与社区的 Wiki, 文档翻译， RPM 包维护等工作。 @shibingli

**Comment by sztsian** [comment]
No updates for over 2 weeks. So close this issue as WON'T FIX. Feel free to comment or reopen if you have strong justification.
超过两周没有跟进了。因此将此Issue关闭并标记为 WON'T FIX. 您可以继续在此issue进行回复;如有较强的支持理由， 也可以重启该issue。
