### ISSUE TITLE
Old Electron Version

### ISSUE THREAD

**Issue by taliptako** [FZUG/repo#168]
I'm using atom package and its using very old electron version like this electron-legacy.x86_64 0.37.8-2.prebuilt.fc24 current electron version is 1.4.0

**Comment by 1dot75cm** [comment]
@taliptako Please see https://github.com/atom/design-decisions/blob/master/electron-update-procedure.md.

Currently, `atom 1.10.2` still uses [electron 0.37.8](https://github.com/atom/atom/blob/3ae8b29e3d1107828990a07b6faa326c7b89f455/package.json#L15). If i update version of Electron, and then some atom plugins doesn't work with a new version of Electron. So, I think `0.37.8` is very well.
