### ISSUE TITLE
sougoupinyin 快捷键, 如何 Disable Ctrl+, (comma)

### ISSUE THREAD

**Issue by yssource** [FZUG/repo#169]
我已经绑定了 ctrl + , (comma) 作为它用，但是每一次 ctrl + , (comma) 都会激活 搜狗拼音。如何更改 这个快捷键， 或者 Disable 它。

**Comment by 1dot75cm** [comment]
设置 -> 按键 -> 切换搜狗拼音输入法快捷键  @yssource

**Comment by yssource** [comment]
@1dot75cm 也没有你说的 切换搜狗拼音输入法快捷键

![screenshot from 2016-09-27 08-01-25](https://cloud.githubusercontent.com/assets/3756334/18855856/b6945754-8488-11e6-8534-fea1e1ddee71.png)

**Comment by sunznx** [comment]
是这个设置，不是系统设置页面，是 搜狗拼音的设置页面
![screenshot from 2016-10-02 19-43-58](https://cloud.githubusercontent.com/assets/8629792/19020350/a2c013ee-886b-11e6-86a0-a4c4a432dc29.png)

**Comment by yssource** [comment]
@sunznx , 谢谢你的回复.
我的系统环境, fc24.x86_64
1.  Current locale:

```
            LANG=en_US.UTF-8
            LC_CTYPE=en_US.UTF-8
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=
```

图形界面跟你的有很大区别, 我找不到你附图的配置窗口.
你能否提供一下你的 `/usr/share/fcitx/addon/fcitx-sogoucloudpinyin.conf` 或者 `/usr/share/fcitx/addon/fcitx-sogoupinyin.conf`

这是我的 `/usr/share/fcitx/addon/fcitx-sogoucloudpinyin.conf`

```
[Addon]
Name=fcitx-sogoucloudpinyin
GeneralName=Sogou Cloud Pinyin
Comment=Add Sogou Cloud Pinyin Support to Sogou Pinyin Input Method
GeneralName[zh_CN]=搜狗云拼音
Comment[zh_CN]=在搜狗拼音输入法中添加搜狗云拼音支持
Category=Module
Enabled=True
Library=fcitx-sogoupinyin.so
Type=SharedLibrary
```

这是我的 `/usr/share/fcitx/addon/fcitx-sogoupinyin.conf`

```
[Addon]
Name=fcitx-sogoupinyin
GeneralName=Sogou Pinyin
GeneralName[zh_CN]=搜狗拼音
GeneralName[zh_TW]=搜狗拼音
Comment=搜狗拼音
Comment[zh_CN]=搜狗拼音
Comment[zh_TW]=搜狗拼音
Category=InputMethod
Enabled=True
Library=fcitx-sogoupinyin.so
Type=SharedLibrary
IMRegisterMethod=ConfigFile
```

**Comment by yssource** [comment]
我这边的问题. 开机后台默认自动启动了 ibus
`rm -fv ~/.config/autostart/ibus-daemon.desktop`
删除后, 正常显示了 设置对话框.
