### ISSUE TITLE
 key "*******************" could not be looked up remotely

### ISSUE THREAD

**Issue by schaurian** [FZUG/repo#17]
I installed yaourt on Fedora 22 and tried to install atraci. But it get this error: key "*************" could not be looked up remotely. Afterwards the programm asked, if i tried this command: "sudo pacman-key --init". But it still doesn't work.

**Comment by 1dot75cm** [comment]
```
# vim /etc/pacman.conf
[archlinuxcn]
SigLevel = Never   # change this line
Server = http://repo.archlinuxcn.org/$arch
```

Because this repository does not exist key. You may use the following command.

```
# export PATH+=:/opt/arch/usr/bin
# export GEM_PATH+=:/opt/arch/usr/local/share/gems
```

**Comment by afonso360** [comment]
I have the same problem but for the `core` repository, temporarly i used 
`Siglevel = Never`
but i would like to have key checking enabled.

**Comment by schaurian** [comment]
Okey i changed all Siglevel to Never and now it works fine. Thank you guys :). (It still doesn't build but i think that is a different problem)
