### ISSUE TITLE
update vscode to latest 1.5.x

### ISSUE THREAD

**Issue by muayyad-alsadi** [FZUG/repo#174]

**Comment by 1dot75cm** [comment]
Build pass with `1.5.3`. I will update Copr repository later. @muayyad-alsadi 
Thanks for report.

**Comment by 1dot75cm** [comment]
Test pass with Fedora 24 x86_64. @muayyad-alsadi 
https://copr.fedorainfracloud.org/coprs/mosquito/vscode/build/461789/
