### ISSUE TITLE
可以打包 zeal 吗

### ISSUE THREAD

**Issue by sunznx** [FZUG/repo#175]
https://github.com/zealdocs/zeal-packaging

**Comment by cicku** [comment]
+1

**Comment by tonghuix** [comment]
这东西不错诶

**Comment by alick** [comment]
已经在官方源了：https://admin.fedoraproject.org/pkgdb/package/rpms/zeal/

**Comment by sunznx** [comment]
官方更新的不够快 - -

**Comment by sztsian** [comment]
> 官方更新的不够快

官方版本更新不够快，可以去 Fedora 提request呢。如果有能力，也可以去pkgdb申请成为zeal包的co-maintainer

**Comment by cheese** [comment]
官方维护者已经把最新的 0.3.0 在 f26/f25 构建了，只是没有给 f24/f23 构建，可以提个 issue 让维护者给稳定分支也构建一下

**Comment by 1dot75cm** [comment]
窝给维护者写了一封邮件， 请求为 fc24/23 构建 zeal。

https://apps.fedoraproject.org/packages/zeal/changelog/
