### ISSUE TITLE
bcloud无法登录

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#176]
如题。百度云客户端在验证码处无法继续登录了。
有时间我会看下相关github repo

**Comment by sztsian** [comment]
原因是百度云盘增加了中文验证码，而客户端对验证码做检查时没有考虑中文验证码。
https://github.com/LiuLang/bcloud/issues/255

**Comment by 1dot75cm** [comment]
本地已测试通过，PR 里面可以顺便改下 SPEC，就更好了。 @sztsian

**Comment by sztsian** [comment]
啊啊啊啊啊，抱歉我竟然git add时忘了spec（我说怎么没人合并呢
晚上下班提交
