### ISSUE TITLE
F24 搜狗拼音无法显示候选词 and crash again and again

### ISSUE THREAD

**Issue by zzt93** [FZUG/repo#179]
``` bash
$ dmesg 

sogou-qimpanel[4218]: segfault at 7ffd1fa6efc0 ip 00007ff6b5028119 sp 00007ffd1fa6efb0 error 6 in libc-2.23.so[7ff6b4fa9000+1b9000]
```

If you need other info, notify me.

**Comment by 1dot75cm** [comment]
Please see #177.

**Comment by zzt93** [comment]
Sorry that I am not clear, but we have different problems.

I already installed the `fcitx-cloudpinyin`.

```
dnf install fcitx-cloudpinyin-0.3.4-3.git45277f6.fc24.x86_64 RPM Fusion for Fedora 24 - Free                 2.7 kB/s | 326 kB     02:01    
Package fcitx-cloudpinyin-0.3.4-3.git45277f6.fc24.x86_64 is already installed, skipping.

```
- imsettings：根据 `~/.cache/imsettings/log` 日志找到

```
[ 1476324812.543487]: FCITX[2405]: (FATAL-2405 /tmp/buildd/fcitx-sogoupinyin-0.1.9+20160929160916~autobuild/src/sogouimcore.cpp:1949) Enter FcitxSogouOnClose:2

[ 1476324812.543843]: FCITX[2405]: (FATAL-2405 /tmp/buildd/fcitx-sogoupinyin-0.1.9+20160929160916~autobuild/src/sogouimcore.cpp:2376) Enter SaveFcitxSogouPinyin

[ 1476324812.543957]: FCITX[2405]: (FATAL-2405 /tmp/buildd/fcitx-sogoupinyin-0.1.9+20160929160916~autobuild/src/sogouimcore.cpp:318) Enter FcitxSogouPinyinReset
```

**Comment by 1dot75cm** [comment]
Please clean `fcitx`, `SogouPY*`, `sogou-qimpanel` in `~/.config`, then relogin and try again. @zzt93

**Comment by zzt93** [comment]
Not working. I deleted all of those directories and relogin but still the same error:

```
 sogou-qimpanel[17925]: segfault at 7fff9fa3eff0 ip 00007f253f835119 sp 00007fff9fa3efe0 error 6 in libc-2.23.so[7f253f7b6000+1b9000]
```

**Comment by sztsian** [comment]
@1dot75cm segfault I think it may be a compile time problem. I asked the maintainer in Debian and he says it works fine. So I assume you could try recompile it with the newest dependency (and the newest gcc if we are building in house. if we utilize fedora building system, then gcc should not be the problem)

**Comment by zzt93** [comment]
After an update, It works now. Thanks for your effort.
