### ISSUE TITLE
Package request : nitrokey app

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#181]
[Nitrokey](https://www.nitrokey.com/) is an USB key to enable highly secure encryption and signing of emails and data, as well as login to the Web, networks and computers. Personally I think it is an open source alternative to [Yubikey](https://www.yubico.com/products/yubikey-hardware/). However Nitrokey ships their app in snapd package only, which is a concern to many users. So I think we can package nitrokey-app here.

The code is [licensed under GPL v3](https://github.com/Nitrokey/nitrokey-app/blob/master/LICENSE)
https://github.com/Nitrokey/nitrokey-app

**Comment by sztsian** [comment]
There is additional udev rules https://www.nitrokey.com/sites/default/files/40-nitrokey.rules

**Comment by 1dot75cm** [comment]
I has been review finished. It's has some problem. Please see [Gist](https://gist.github.com/1dot75cm/688e7ff7cb4ba1266718b693d606dcc4). Thanks. @sztsian

**Comment by sztsian** [comment]
Close as FIXED.
