### ISSUE TITLE
vscode: 1.6.1 gives broken installation

### ISSUE THREAD

**Issue by muayyad-alsadi** [FZUG/repo#184]
I installed your build

```
[root@localhost ~]# rpm -q electron vscode
electron-1.3.7-1.prebuilt.fc24.x86_64
vscode-1.6.1-1.fc24.x86_64
```

it points me to this link https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt

![screenshot from 2016-10-16 11-35-09](https://cloud.githubusercontent.com/assets/1312683/19416251/c2451f0a-9394-11e6-8449-d3e224514983.png)

and those are the plugins

![screenshot from 2016-10-16 11-36-56](https://cloud.githubusercontent.com/assets/1312683/19416259/e97b6084-9394-11e6-9a4a-ba03497d94bb.png)

**Comment by 1dot75cm** [comment]
Hi, @muayyad-alsadi 
I fixed it. Please test [vscode-1.11.1-2](https://copr.fedorainfracloud.org/coprs/mosquito/vscode/build/465684/) for your environment.
