### ISSUE TITLE
建议添加Infinality字体渲染补丁

### ISSUE THREAD

**Issue by caoli5288** [FZUG/repo#189]
建议添加Infinality字体渲染补丁。这个补丁打上去字体显示效果堪称天壤之别，尤其在普通分辨率屏幕上非常明显。

有以下几个理由使用Infinality而不是rpmfusion中已有的freetype-freeworld.
* freetype-freeworld需要额外配置才能达到最佳显示效果
* freetype-freeworld的最终效果比起Infinality也很差
* Infinality提供了针对Java的补丁
* Infinality提供了一些针对特定字体的优化补丁，包括常见CJK字体

> https://wiki.archlinux.org/index.php/Infinality
> https://bohoomil.com/

**Comment by 1dot75cm** [comment]
我记得 Infinality 提供了一个 Fedora 源， 但是现在 [infinality.net](http://www.infinality.net) 不知怎么，无法访问了 @caoli5288

**Comment by caoli5288** [comment]
@1dot75cm 那个早就停止维护了，现在可用的是arch那边社区维护的一个版本，我个人移植了一下f25的，https://github.com/caoli5288/infinality-ultimate

**Comment by 1dot75cm** [comment]
@caoli5288  已经搞好了，不过我感觉具体的实际效果与原版的差异没有那么大，据说要配合指定字体才能有更好的效果。鉴于字体包太多，搞不起了。

如果 CI 打包失败，可以用 `mock` 或者 `cibuild.py` 那个脚本打包测试。

Infinality 字体渲染配置，请参考 [wiki](https://github.com/FZUG/repo/wiki/%E9%85%8D%E7%BD%AE-Infinality-%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%E5%A2%9E%E5%BC%BA)。

**Comment by caoli5288** [comment]
@1dot75cm 在高分辨率屏幕效果比较明显

**Comment by 1dot75cm** [comment]
恩恩，换了苹方字体，感觉挺好的。高分屏即使不打补丁，字体效果也应该比较好。没看过高分的 Linux 字体效果是啥样。看过new macbook 的效果，简直逆天了 @caoli5288

**Comment by caoli5288** [comment]
@1dot75cm 会有点发虚，用上这个以后就感觉很细腻。听说freetype-2.7改进很大，也许f26就不需要这个东西了
