### ISSUE TITLE
Please update wiki to add step to install fakeroot dependency

### ISSUE THREAD

**Issue by ghost** [FZUG/repo#19]
Fedora 22 requires fakeroot to be installed for building packages (at least with yaourt)

Perhaps like;
### 1.Install Dependencies

yaourt requires fakeroot package, install with:
`$ dnf install fakeroot`

**Comment by 1dot75cm** [comment]
^^~ Thanks.

**Comment by ghost** [comment]
Very welcome. Thank you!

**Comment by 1dot75cm** [comment]
https://github.com/FZUG/repo/commit/551a0cd8240cc527745c7e6754d53a1cd4d6cf21  fixed it. ^^~

**Comment by 1dot75cm** [comment]
please clean metadata, and then update.

```
# rm -rf /var/cache/dnf/FZUG*
# dnf update
```
