### ISSUE TITLE
Fedora 24 中 docky 不能启动

### ISSUE THREAD

**Issue by githubyong** [FZUG/repo#190]
系统为fedora24,docky版本为2.2.1.1-1.fc24，安装后不能启动.

**Comment by Endle** [comment]
Closing this issue due to **EOL** (End of Life). Please feel free to reopen it and comment with the current version if the issue still exists.
感谢您汇报了此 issue。由于该 Fedora 版本已经停止维护，此 issue 将被关闭。如果在新的 Fedora 版本中此问题仍然存在，请重新打开此 issue。
