### ISSUE TITLE
all input methods frozen when using sogou input for a while

### ISSUE THREAD

**Issue by zzt93** [FZUG/repo#191]
When inputing using sogou for a while, all input method(not only sogou) is frozen(to be precise, all input is delaied for about 15s or more). Only english input in terminal is normal.
```
 ~/.cache/imsettings/log
[ 1479451576.620997]: FCITX[2513]: open file /usr/share/fcitx-sogoupinyin/SogouInput/sgim_urlGuide.bin failed.

[ 1479451576.621046]: FCITX[2513]: open file /usr/share/fcitx-sogoupinyin/SogouInput/sgim_tip.bin failed.

[ 1479451576.621097]: FCITX[2513]: open file /usr/share/fcitx-sogoupinyin/SogouInput/sgim_urlGuide.bin failed.

[ 1479451576.621145]: FCITX[2513]: open file /usr/share/fcitx-sogoupinyin/SogouInput/sgim_tip.bin failed.

[ 1479451576.621191]: FCITX[2513]: open file /usr/share/fcitx-sogoupinyin/SogouInput/sgim_urlGuide.bin failed.
`````
Actually, any control key is normal (like windows key), but any key related input (enter, character, delete, etc.) is delayed

**Comment by yssource** [comment]
The same issue happens to me from time to time as well.

**Comment by zzt93** [comment]
More description: If the input is already frozen, close the software and open it again can recover direct english input. And the input method can't switch any more unless you reboot the machine.
If you need any log, notify me. Thanks for your effort.

**Comment by 1dot75cm** [comment]
I have seen several similar reports (#192, #196, self). But the problem is difficult to reproduce (need to wait for long time). I hope that the log contains useful things. @zzt93 

Currently, If you encounter the problem again, please kill process of `sogou-qimpanel` and restart `fcitx`.

**Comment by zzt93** [comment]
More description: When it crash, my Java-based IDE is also crashed.

How to restart fcitx? Is the following command?
```
$fictx  restart
...
...
(ERROR-17385 /builddir/build/BUILD/fcitx-4.2.9.1/src/lib/fcitx/instance.c:440) Exiting.
```

**Comment by alick** [comment]
To restart, either select the "Restart" option from the pop down menu after
clicking fcitx's icon, or in the command line use

    fcitx -r

Regards,
Alick

**Comment by sztsian** [comment]
In USTC channel, they wonder if it is caused by SELinux. So I will take a look into this.

**Comment by sztsian** [comment]
I prefer to regard this as a upstream bug. They even have this issue in Ubuntu. See http://blog.csdn.net/jilijelon/article/details/53759965

**Comment by sztsian** [comment]
Build a package without SELinux, and the issue still happens. So concluded this has nothing to do with SELinux.

**Comment by sztsian** [comment]
Talked with the sogou input developer. As sogou input does not provide source code, the developer suggests all users who have problems using sogou to use other input methods.
