### ISSUE TITLE
求打包 aegisub

### ISSUE THREAD

**Issue by m0wong** [FZUG/repo#194]
Cross-platform advanced subtitle editor https://github.com/Aegisub/Aegisub

**Comment by 1dot75cm** [comment]
好东西～～ 正在打包 @bluesnowlake

**Comment by m0wong** [comment]
感谢

**Comment by m0wong** [comment]
求助，build 失败了。  @1dot75cm 
没看到具体错误，到这里就退出了。

```
make[2]: Entering directory '/home/user/rpmbuild/BUILD/aegisub-3.2.2/vendor/luajit/src'
LINK      luajit
OK        Successfully built LuaJIT
make[2]: Leaving directory '/home/user/rpmbuild/BUILD/aegisub-3.2.2/vendor/luajit/src'

错误：/var/tmp/rpm-tmp.6mY1Wy (%build) 退出状态不好

RPM 构建错误：
    /var/tmp/rpm-tmp.6mY1Wy (%build) 退出状态不好
```

**Comment by 1dot75cm** [comment]
应该有具体错误的，刚才试了一下，编译应该没问题。

Update 1212: 刚刚添加了 ffms2 依赖，需要先编译 ffms2，安装 ffms2-devel，再编译 aegisub。

这里有个我测试的时候编译好的包（[00484418-aegisub](https://copr-be.cloud.fedoraproject.org/results/mosquito/test/fedora-25-x86_64/00484418-aegisub/)）。另外，如果编译时突然出错退出，建议关闭其他程序再编译，这个程序编译时消耗内存较多。@bluesnowlake

**Comment by m0wong** [comment]
@1dot75cm 
重新装了 ffms2，用更新的 spec 可以打包了，但是安装后无法运行。
```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Segmentation fault (核心已转储)
```
`00484418-aegisub` 也是同样的错误，之前用 russianfedora 的 spec 打的包也是。
升级 f25 之前 一直在用 russianfedora 的包，升级后不能用了，他们也一直没有更新。

如果你运行正常，那可能是我系统里某个包安装得有问题或者是升级把什么东西搞坏了吧。


（ps.我用  yaourt 装了 arch 的包可以用。）

**Comment by 1dot75cm** [comment]
感觉像是系统库有问题， 我这里是正常的，有时间建议重装一下。 @bluesnowlake
