### ISSUE TITLE
Fedora 25 and 1.12 atom 

### ISSUE THREAD

**Issue by kmare** [FZUG/repo#195]
First of all, great work with your repo! I wanted to ask if you're going to update atom to version 1.12 for fedora 25.
Thank you!

**Comment by alick** [comment]
We will, but it is likely to have some delay since we need massive build for the new release

**Comment by alick** [comment]
Maybe better leave this open till the update is available

**Comment by sztsian** [comment]
We will do the massive rebuild for Fedora 25 once ready for a trigger. 
For the update request, we need to confirm with our package maintainer to see if it works.

**Comment by 1dot75cm** [comment]
Testing package. [build/483648](https://copr.fedorainfracloud.org/coprs/mosquito/test/build/483648/) Please wait a moment. @kmare

**Comment by stesachse** [comment]
`Error: nothing provides electron = 1.3.9 needed by atom-1.12.6-1.git5a3d615.fc25.x86_64`

is this correct? current atom requires `electron = 0.37.8`

**Comment by kmare** [comment]
I'm pretty sure atom 1.12+ switched to electron 1.3.6+.
See here: http://blog.atom.io/2016/11/09/atom-1-12.html

**Comment by stesachse** [comment]
ok, thanks. but here is another stupid question :) where can i find electron-1.3.9. the f24 repos has a 1.2.3-3 but i can not find version 1.3.9. i try to search [old fedmsg](https://apps.fedoraproject.org/datagrepper/raw?delta=604800&topic=org.fedoraproject.prod.copr.build.end&contains=electron) for copr builds. but only found lower versions.

**Comment by 1dot75cm** [comment]
I have pushed the new package to Copr. Please test them. ([atom-1.12.6](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/483866/), [483919](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/483919/) and [electron-1.3.9](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/483867/))  @kmare @stesachse

**Comment by stesachse** [comment]
@1dot75cm build of [atom-1.12.6](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/483866/) for [fedora-25-x86_64](https://copr-be.cloud.fedoraproject.org/results/mosquito/atom/fedora-25-x86_64/00483866-atom/root.log) and above are failed while setting up the build root


```
DEBUG util.py:421:  Failed to synchronize cache for repo 'coprbecloudfedoraprojectorg_results_mosquito_atom_fedora25x86_64_devel', disabling.
DEBUG util.py:421:  Failed to synchronize cache for repo 'fedora', disabling.
DEBUG util.py:421:  Last metadata expiration check: 0:02:02 ago on Fri Dec  2 06:24:13 2016.
DEBUG util.py:421:  Error: nothing provides rtld(GNU_HASH) needed by rpm-build-4.13.0-5.fc25.x86_64.
DEBUG util.py:421:  nothing provides fedora-repos(25) needed by fedora-release-25-0.12.noarch.
DEBUG util.py:421:  nothing provides rtld(GNU_HASH) needed by coreutils-8.25-15.fc25.x86_64
```

**Comment by stesachse** [comment]
thanks @1dot75cm works for me :)

**Comment by 1dot75cm** [comment]
Fixes and close.
