### ISSUE TITLE
F24、F25使用sogou拼音卡死

### ISSUE THREAD

**Issue by osmonds** [FZUG/repo#196]
升级到F24、F25以后，sogou拼音输入时会卡死，什么原因，如何解决？

**Comment by sztsian** [comment]
该issue与192重复，关闭。
如有更多信息反馈，请更新在 #192 或反馈至搜狗拼音输入法开发者。

Close as duplicated of #192 . Please update in #192 if you have more information or update to the upstream maintainer.
See https://github.com/FZUG/repo/issues/192#issuecomment-262908546
