### ISSUE TITLE
Fedora 25下sogou拼音无法在WPS中输入中文（无法开启sogou拼音）

### ISSUE THREAD

**Issue by light8lee** [FZUG/repo#197]
在WPS中，sogou输入法出不来，只能输入英文，无法输入中文，其他的地方（例如网页中）是可以输入的。

**Comment by light8lee** [comment]
已解决，

> sudo vim /usr/bin/wps
> sudo vim /usr/bin/et
> sudo vim /usr/bin/wpp

然后都是在第二行之后插入
```
export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE="fcitx"
```
就可以了，
参考[记录ubuntu安装中文输入法的坑](http://www.cnblogs.com/yiruhua/p/5466842.html)

**Comment by sztsian** [comment]
感谢。

此外在这儿增加一个说明，也可以修改用户自己的配置，让当前用户所有QT程序使用fcitx

vim ~/.bash_profile
> QT_IM_MODULE=fcitx
