### ISSUE TITLE
vscode 1.7.2 fails to reopen the folder I opened last time on start

### ISSUE THREAD

**Issue by m0wong** [FZUG/repo#198]
It always opens `/usr/lib64/vscode/ `on every start, although I opened another folder last time.

The default setting of `window.reopenFolders` is `one`,  and I have tried to set it in user settings to overwrite the default settings  but nothing changed.

I also have tried to clear the opened paths list and delete `/usr/lib64/vscode/` from `~/.config/vscode/storage.json` ,  but when vscode starts, it reopens `/usr/lib64/vscode/` and adds  `/usr/lib64/vscode/`  to the list again.

In fact, the bug also exists in the previous version. 
I installed the rpm package provided by Microsoft and it works well on this .
I guess maybe it is relative to changing the default install path of vscode?

**Comment by 1dot75cm** [comment]
Thanks report. I have pushed the package to copr ([484389](https://copr.fedorainfracloud.org/coprs/mosquito/vscode/build/484389/)). Please test it. @bluesnowlake

**Comment by m0wong** [comment]
Works for me. Thanks for your effort all the time.
