### ISSUE TITLE
worng repo number for fedora 25 (its 26)

### ISSUE THREAD

**Issue by Noori** [FZUG/repo#199]
The repo name of fedora 25 is 26! but the package name is fc25.
Its impossible to install lantern on fedora 25 from mosquito repo.

repo address
https://copr.fedorainfracloud.org/coprs/mosquito/lantern/repo/fedora-26/mosquito-lantern-fedora-26.repo

package name in repo 26
golang-github-getlantern-lantern-2.1.1-1.gitfd97e0e.fc25.x86_64.rpm

**Comment by sztsian** [comment]
Feeling a little strange that this question comes to the community issue list (instead of direct go to Mosquito's email). Anyway, assign him directly.

**Comment by alick** [comment]
This is about @1dot75cm 's personal copr, not FZUG's. Close as off topic.

If it affects FZUG copr as well, feel free to reopen.
