### ISSUE TITLE
fedora如何完美运行qq

### ISSUE THREAD

**Issue by youngjeff** [FZUG/repo#20]
我尝试过webqq,或者类似的插件qq,还有wine+qq.exe,来安装效果都不好,经常崩溃.
听说有deepinqq,但是没有linux版,所以请问fedora有定制版的qq吗,或者有大神帮我解决qq的问题吗.

**Comment by Endle** [comment]
你可以尝试通过 FZUG 里的 winetricks-zh 安装 wine qq

deepin 和 Codeweavers 有商业合作，这点 Fedora 没法比

**Comment by tvvocold** [comment]
https://github.com/im-qq/iqq
