### ISSUE TITLE
No electron-legacy in repo Fedora 25

### ISSUE THREAD

**Issue by elemc** [FZUG/repo#200]
Hi.
In Fedora 25 repo no package electron-legacy.
Without electron-legacy not working apm as expected.

**Comment by 1dot75cm** [comment]
Rebuild `electron-legacy` for this. [atom/488753](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/488753/) @elemc

**Comment by elemc** [comment]
Thanks.
