### ISSUE TITLE
The "deepin-screenshot" problem

### ISSUE THREAD

**Issue by Kashin-J** [FZUG/repo#201]
I installed "deepin-screenshot-3.0.2-1.git753410c.fc24.noarch" from the “fzug” repository on Fedora 24,there was no exception during the installation,but it doesn't work.So I checked the ["deepin-screenshot"](https://github.com/linuxdeepin/deepin-screenshot/releases) official repository and found many new releases,I do not know if this will fix the problem, but I hope the "fzug" repository to update it.
Thanks:)

**Comment by alick** [comment]
Thanks for the report. Yes we should build the updated releases.

**Comment by 1dot75cm** [comment]
Hi @Kashin-J 
I have finished to package for Deepin Desktop Environment. You can visit [Deepin_project](https://github.com/FZUG/repo/tree/master/rpms/deepin_project) subdirectory for more information.

![](https://files.gitter.im/1dot75cm/WW6X/____20170121202801.png)

![](https://files.gitter.im/1dot75cm/h9Ah/____20170121203618.png)

**Comment by 1dot75cm** [comment]
Fix it, if you have any problems, please reopen this. @Kashin-J
