### ISSUE TITLE
Pre-installed video player can not work, suggesting that the lack of dependence. I have reinstall totem related packages , if there is a better way to resolve the problem..

### ISSUE THREAD

**Issue by weikunzz** [FZUG/repo#206]

**Comment by alick** [comment]
Does reinstall solve your problem? IMO that's the best way.

**Comment by weikun123** [comment]
Reinstall not  work,I will try what's your said,thank you

**Comment by weikunzz** [comment]
But,i am sorry what is IMO?

**Comment by sztsian** [comment]
> But,i am sorry what is IMO?

Well, IMO is short saying of 'In my opinion'. So actually Alick means if reinstall works for you or not.

By the way, what is 'own video player'? I did not see this package in FZUG repo.

**Comment by weikunzz** [comment]
O,"own vidoe player"that is said the video will be exist when installed a system.And the video  application name is "videos"

**Comment by sztsian** [comment]
> O,"own vidoe player"that is said the video will be exist when installed a system.And the video application name is "videos"

Ok, it is much clear to me now. So you mean the pre-installed 'Videos' application can not play your video files with the message like "lack of dependence" or "missing plugins", am I right? If so, please read [this answer](https://ask.fedoraproject.org/en/question/9111/sticky-what-plugins-do-i-need-to-install-to-watch-movies-and-listen-to-music/?answer=12998).

**Comment by sztsian** [comment]
Close as NOT A BUG
