### ISSUE TITLE
同步仓库 'fzug-free' 的缓存失败，来自 'https://repo.fdzh.org/FZUG/free/22/x86_64/'：repomd.xml parser error: Parse error at line: 1 (no element found)，禁用。

### ISSUE THREAD

**Issue by hyt-hz** [FZUG/repo#207]
fedora22的free库无法使用，repomd.xml为空文件？

curl -v https://repo.fdzh.org/FZUG/free/22/x86_64/repodata/repomd.xml
*   Trying 110.79.20.49...
* Connected to repo.fdzh.org (110.79.20.49) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=repo.fdzh.org
* 	start date: 12月 04 17:30:00 2016 GMT
* 	expire date: 3月 04 17:30:00 2017 GMT
* 	common name: repo.fdzh.org
* 	issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> GET /FZUG/free/22/x86_64/repodata/repomd.xml HTTP/1.1
> User-Agent: curl/7.40.0
> Host: repo.fdzh.org
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.11.2
< Date: Thu, 22 Dec 2016 02:14:39 GMT
< Content-Type: text/xml; charset=utf-8
< Content-Length: 0
< Last-Modified: Sat, 19 Nov 2016 21:18:04 GMT
< Connection: keep-alive
< ETag: "5830c18c-0"
< Strict-Transport-Security: max-age=15768000; includeSubdomains; preload
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Accept-Ranges: bytes
< 
* Connection #0 to host repo.fdzh.org left intact

**Comment by sztsian** [comment]
Hi,
> fedora22的free库无法使用，repomd.xml为空文件？

[Fedora 22已经于2016年7月19日结束生命周期。](https://fedoramagazine.org/fedora-22-end-of-life-2016-july/)。Fedora中文用户组也已经停止了对Fedora 22的服务。
建议您关注[Fedora生命周期](http://fedoraproject.org/wiki/End_of_life)，及时升级系统到最新版本。升级过程请参考[这篇文档](https://fedoramagazine.org/upgrading-fedora-24-fedora-25/)。
