### ISSUE TITLE
中文社区软件源网站主题定制

### ISSUE THREAD

**Issue by alick** [FZUG/repo#21]
[中文社区软件源网站](http://repo.fdzh.org/) 目前主题看起来和中科大的开源镜像站完全一样。@cicku 建议对这一主题进行一些定制，加入 Fedora 蓝色元素，以更好地进行品牌宣传，并与中科大的开源镜像站区分。

**Comment by cicku** [comment]
我是收到某位用户的反馈（近似于嘲讽），才发现这个问题的。

**Comment by tvvocold** [comment]
@1dot75cm  可以改下吗？
FYI：之前收到了 USTC 的邮件并在底部增加了原作者的 link.

**Comment by alick** [comment]
网站源码有版本控制吗？可以放到GitHub上来。我可以发PR。
2015年8月24日 下午9:11于 "Ray" notifications@github.com写道：

**Comment by tvvocold** [comment]
ping @1dot75cm  : )

**Comment by 1dot75cm** [comment]
git 大法好， 我整理一下发上来。

**Comment by 1dot75cm** [comment]
@alick  页面已传至 page 分支。只要向 page 分支提交 PR 等待合并，服务器将自动应用更改。

**Comment by alick** [comment]
好的，我最近有空时搞个定制版。

**Comment by tvvocold** [comment]
@1dot75cm 
http://www.jamiembrown.com/blog/one-in-every-600-websites-has-git-exposed/

**Comment by 1dot75cm** [comment]
@alick 感谢 ^^
@tvvocold 嗯嗯，加强权限审计，避免这样的问题

**Comment by tvvocold** [comment]
@1dot75cm 
http://repo.fdzh.org/FZUG/ 页面中 

```
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
```

国内加载很慢，换成七牛或者又拍云的吧。

**Comment by alick** [comment]
@tvvocold plz consider to open a new issue about cdn for js libraries

**Comment by alick** [comment]
Seems no further comments on PR #27 . Can someone go ahead and merge it? OR me?

**Comment by 1dot75cm** [comment]
Yes, merge it. Thanks.

**Comment by alick** [comment]
:+1:
