### ISSUE TITLE
update vscode to 1.8.1

### ISSUE THREAD

**Issue by muayyad-alsadi** [FZUG/repo#210]
https://code.visualstudio.com/updates

**Comment by 1dot75cm** [comment]
https://copr.fedorainfracloud.org/coprs/mosquito/vscode/build/495079/
I will test it later. @muayyad-alsadi

**Comment by 1dot75cm** [comment]
I met the following two errors. @muayyad-alsadi 
- miss some `workbench.main.*` files (the files in the `/usr/lib64/vscode/out/vs/workbench/electron-browser/workbench.main.*`)

(ENOENT: no such file or directory, open '/usr/lib64/vscode/out/vs/workbench/workbench.main.js'): Error: ENOENT: no such file or directory, open '/usr/lib64/vscode/out/vs/workbench/workbench.main.js'
    at Error (native) 个(共 2 个错误)WorkbenchShell.onUnexpectedError @ workbench.main.js:173606(anonymous function) @ workbench.main.js:173539ErrorHandler.onUnexpectedError @ workbench.main.js:6551onUnexpectedError @ workbench.main.js:6569(anonymous function) @ workbench.main.js:12228(anonymous function) @ workbench.main.js:12223
workbench.main.js:12230 WARNING: Promise with no error callback:75

- a lot of `[IPC Library: Watcher] Error: watch ...... ENOSPC` errors.
VSCode monitors the opened directory. However, the Linux default watcher file limit is `8192`. This error occurs when the monitoring file is larger than `8192`. Execute the following command to fixes it.

```
$ sudo echo fs.inotify.max_user_watches=524288 >> /etc/sysctl.conf && sudo sysctl -p
```

**Comment by muayyad-alsadi** [comment]
please reopen this ticket

please ship a new file named  `/etc/sysctl.d/50-vscode.conf` having the following content

```
fs.inotify.max_user_watches=524288
```

instead of playing with existing system files

and you might as well add the following scriptlet in the specfile

```

%posttrans
/sbin/sysctl --system

```

**Comment by 1dot75cm** [comment]
I have uploaded the package to 'Copr [496658](https://copr.fedorainfracloud.org/coprs/mosquito/vscode/build/496723/)' and test later. Thank you for your help. @muayyad-alsadi
