### ISSUE TITLE
atom: jump to method causes error

### ISSUE THREAD

**Issue by poettler-ric** [FZUG/repo#211]
Hello,

I am using atom from your copr repo. Everytime I try to jump to a method pressing ctrl-r I get the following error:

Uncaught BufferedProcessError: Failed to spawn command `/usr/lib64/atom/node_modules/symbols-view/vendor/ctags-linux`. Make sure `/usr/lib64/atom/node_modules/symbols-view/vendor/ctags-linux` is installed and on your PATH

I think it's because you are deleting the whole folder in line 139 of your spec file. Maybe this could be solved by requireing the ctags Fedora package and link the executable in the spec file?

Kind regards
Richard Poettler

**Comment by 1dot75cm** [comment]
Hi @poettler-ric 
The package is miss the [ctags-linux](https://github.com/atom/symbols-view/blob/master/vendor/ctags-linux) executable file in `vendor` directory, is it?
I try to open a python file, and `ctrl+r`. It's work fine. 

PS: You may want to check out the section on `Failed to activate the atom-ctags package` at [coprs/mosquito/atom/](https://copr.fedorainfracloud.org/coprs/mosquito/atom/).

Update: i just viewed the https://github.com/atom/symbols-view/issues/153. He said: "Some languages have their own ctag binary, like Vala...". Maybe i need to add the `/usr/bin/ctags` to link the executable file to `/usr/lib64/atom/node_modules/symbols-view/vendor/ctags-linux`.

Thanks for nice report.

**Comment by 1dot75cm** [comment]
I have uploaded the package to 'Copr [496915](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/496915/)'. If you have free time, please test it. Thanks. @poettler-ric

**Comment by poettler-ric** [comment]
That removed the error message, thanks. It doesn't generate/use the tags when i press crtl-r. Imho it should, since there is a generate function/method:
https://github.com/atom/symbols-view/blob/master/lib/tag-generator.js#L72
which assembles the command line, executes ctags and parses it. My guess is that it never gets executed? So i have to use symbols-gen to generate the tags file manually...

Why is the node_modules directory removed in the spec file anyway, if I might ask?

**Comment by 1dot75cm** [comment]
Fixed it! I miss the `/usr/lib64/atom/node_modules/symbols-view/lib/ctags-config` file. @poettler-ric

I seen the some spec of nodejs in the official repository. Them has some `find` command to remove file except js(only install the js and package.json files). I feel clean directory tree is important.

**Comment by poettler-ric** [comment]
Thanks a lot! I think that did the trick and generates the symbols of a file on the fly. To search the project I have to generate the tags file by hand, but I don't see code in the package which says otherwise :) .
