### ISSUE TITLE
Fadora25 分辨率问题

### ISSUE THREAD

**Issue by AgentEric** [FZUG/repo#214]
显卡是GTX960,已经安装了官方的N卡驱动，但是分辨率只有640x480，到底该如何配置啊？

**Comment by AgentEric** [comment]
@gbraad @cheese @tonghuix @cicku @alick

**Comment by sztsian** [comment]
你好，这里是反馈 Fedora 中文用户组软件源相关问题的地方，看起来没有人能在这里帮忙回答Fedora相关配置问题。
建议您订阅[Fedora中文邮件列表 ](https://lists.fedoraproject.org/admin/lists/chinese.lists.fedoraproject.org/) 并发邮件至邮件列表咨询。
