### ISSUE TITLE
可以打包caddy吗

### ISSUE THREAD

**Issue by sunznx** [FZUG/repo#216]
RT

**Comment by sztsian** [comment]
你是说 [the Caddy web server](https://github.com/mholt/caddy) 么？[官网](https://caddyserver.com/)？

**Comment by sunznx** [comment]
是

**Comment by 1dot75cm** [comment]
奇怪为何这么多 star 的程序，没有人打包。我可以先写出来一个 @sunznx

**Comment by sztsian** [comment]
@1dot75cm  那就assign给你了。

**Comment by 1dot75cm** [comment]
已经打包好了，Golang 很赞，静态编译以后，没有多余的外部依赖，看起来很棒。@sunznx
