### ISSUE TITLE
fedora25中shadowsocks-qt5 总是无故消失

### ISSUE THREAD

**Issue by light8lee** [FZUG/repo#217]
开了shadowsocks-qt5之后，有时候人走开一下，回来时就发现底部的托盘上的shadowsocks的图标消失了，系统的代理也失效了，必须重新启动shadowsocks才行，而且要启动两次，第一次会提醒上一次已崩溃，第二次才可以正常运行。

**Comment by 1dot75cm** [comment]
终端长时间运行 `/bin/ss-qt5` 有没有报错？ @light8lee

**Comment by light8lee** [comment]
用的不是终端，是GUI程序 @1dot75cm

**Comment by tonghuix** [comment]
@light8lee 
那是让你在命令行下跑起来，这样能看到log。

顺便说这个问题我也遇到了，现在fedora下已经放弃改用ss-libev取代之

**Comment by light8lee** [comment]
哦哦，我试试看有没有log，谢谢指明 @tonghuix

**Comment by light8lee** [comment]
最近好像一直没有出现
