### ISSUE TITLE
为知笔记在Fedora 22 Gnome下无法使用fcitx

### ISSUE THREAD

**Issue by tamlok** [FZUG/repo#22]
仓库的的为知笔记无法使用fcitx输入中文，已经安装了fcitx-qt5-1.0.4-2.
此前使用OpenSuse Gnome的时候，也会有这样的问题。当时候，我尝试了下载WizNote的源码自行编译安装，居然就可以使用fcitx了。
所以是不是FZUG编译WizNote的时候有什么环境没有设置对吗？能否发布一个直接安装就可以使用fcitx的为知笔记？
另外，我尝试在fedora 22下编译WizNote，但是好像WizNote在GCC 5.1下编译会出错，有什么解决办法吗？
谢谢！

**Comment by tvvocold** [comment]
Fixed in http://hack.fdzh.org/item?id=1010

**Comment by 1dot75cm** [comment]
使用 fcitx-diagnose 检查一下看看有什么问题。
源里的 fcitx-qt5 已为 qt 5.5 重新编译，我这里 wiznote/wiznote-beta 中文输入正常。
另外，关于 wiznote 编译已在 spec 中有详细描述。如果还有问题，可随时回复。

**Comment by tamlok** [comment]
已经重新从FZUG源安装fcitx-qt5和wiznote，还是无法使用fcitx输入中文。fcitx-diagnose显示变量一切正常。

```
env | grep IM
IMSETTINGS_INTEGRATE_DESKTOP=yes
XIM_PROGRAM=fcitx
IMSETTINGS_MODULE=FCITX
XIM=fcitx
QT_IM_MODULE=fcitx
XDG_RUNTIME_DIR=/run/user/1000
GTK_IM_MODULE=fcitx
LC_TIME=en_US.UTF-8
```

同样，其它qt5程序，如goldendict，也无法使用fcitx输入。
另外，如果我使用命令`QT_IM_MODULE=fcitx wiznote`来启动为知，则可以正常使用fcitx输入。

**Comment by 1dot75cm** [comment]
alternatives --config xinputrc，选 fcitx

**Comment by tamlok** [comment]
@1dot75cm 运行了，原来选择的是ibus，但选择fcitx后依然没有效果。不管了，目前先用命令前添加变量的方法运行吧。
另外，能否在源里添加goldendict？包括最新版的。官方的有1.5rc版的，但是貌似添加有道在线词典会崩溃。但1.0.1版在opensuse中不会。谢谢。

**Comment by cicku** [comment]
1.5 rc 在官方源里面就有啊

**Comment by tamlok** [comment]
是的，但是1.5rc貌似添加有道在线辞典会崩溃。原来在openSuse上的是1.0.1,可以正常使用在线词典。而且目前goldendict之后已经有很多提交更新了，所以能否弄一个unstable的开发版？

2015-09-07 19:40 GMT+08:00 Christopher Meng notifications@github.com:

**Comment by 1dot75cm** [comment]
@tamlok 有时间可以测试一下 unstable 是否能正常运行。
如果能提交 pr 就更好了。社区源欢迎大家维护。

**Comment by tamlok** [comment]
嗯，我也想学习一下发行版包管理这方面的知识。但是目前我连wiz都编译不成功呀，所以goldendict的unstable版不知道能否编译成功。希望社区可以提供该软件。非常感谢！
后来我在opensuse 13.2下安装1.5版的，发现也可以正常使用。所以，暂时不确定是不是fedora上某些软件包过新或者不兼容导致的问题。

2015-09-08 18:10 GMT+08:00 1dot75cm notifications@github.com:

**Comment by tamlok** [comment]
@1dot75cm 以root权限运行goldendict可以解决这个问题，感觉很奇怪。
