### ISSUE TITLE
incorrect provides for package nodejs-atom-package-manager

### ISSUE THREAD

**Issue by stesachse** [FZUG/repo#220]
apm has a directory with [templates](https://github.com/atom/apm/tree/master/templates). each template includes a [package.json](https://github.com/atom/apm/blob/master/templates/package-javascript/package.json) with some place holder strings. these `package.json` files generate incorrect dependencies `Provides:` for the place holder string
```
% rpm -q --provides nodejs-atom-package-manager
nodejs-atom-package-manager = 1.13.0-2.git33e67dd.fc25
nodejs-atom-package-manager(x86-64) = 1.13.0-2.git33e67dd.fc25
npm(__package-name__) = 0.0.0
npm(atom-package-manager) = 1.13.0
npm(language-__package-name__) = 0.0.0
npm(module-with-native-code)
```

the following `Provides:` dependencies are incorrect

- npm(\_\_package-name__) = 0.0.0
- npm(language-\_\_package-name__) = 0.0.0

change the regex to exclude `package.json` files below `templates/` directory from passing over to the rpm dependency generator

```patch
--- apm.spec-orig	2017-02-17 21:51:37.690509446 +0100
+++ apm.spec	2017-02-18 08:09:02.791401759 +0100
@@ -5,7 +5,7 @@
 %global _cpln %(test $(rpm -E%?fedora) -gt 24 && echo "ln -s" || echo "cp -p")
 %global debug_package %{nil}
 %global _hardened_build 1
-%global __provides_exclude_from %{nodejs_sitelib}/.*/node_modules
+%global __provides_exclude_from ^%{nodejs_sitelib}/(.*/node_modules|[^/]+/templates)/.*
 %global __requires_exclude_from %{nodejs_sitelib}/.*/node_modules
 %global __requires_exclude (npm)
```

with this patch the 'Provides:' are generated as follows

```
% rpm -q --provides -p RPMS/nodejs-atom-package-manager-1.13.0-2.git33e67dd.fc25.x86_64.rpm
nodejs-atom-package-manager = 1.13.0-2.git33e67dd.fc25
nodejs-atom-package-manager(x86-64) = 1.13.0-2.git33e67dd.fc25
npm(atom-package-manager) = 1.13.0
npm(module-with-native-code)
```

**Comment by 1dot75cm** [comment]
Very nice. Thanks @stesachse

**Comment by alick** [comment]
Closing as we fail to build atom for a while
