### ISSUE TITLE
File conflict: /usr/bin/html2text from python-html2text 

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#224]
Due to historical reason, if you enabled fzug-free and now updated to Fedora 25, you will get conflict error when updating  python-html2text.

The workaround before we can fix our repo is disable fzug-free when update python-html2text or python3-html2text like

sudo dnf update python-html2text --disablerepo=fzug-free

**Comment by sztsian** [comment]
@1dot75cm Please remove the package **python-html2text** and **python3-html2text**  manually from the fzug-free repo and recreate repo metadata to avoid future problems.

**Comment by 1dot75cm** [comment]
Thanks report, fixed it. @sztsian
