### ISSUE TITLE
fedora25,wps无法安装

### ISSUE THREAD

**Issue by ghost** [FZUG/repo#227]
`--2017-03-12 23:41:00--  http://linux.linuxidc.com/2014%E5%B9%B4%E8%B5%84%E6%96%99/4%E6%9C%88/20%E6%97%A5/Ubuntu%2014.04%20%E5%AE%89%E8%A3%85%20WPS/symbol-fonts_1.2_all.deb
正在解析主机 linux.linuxidc.com (linux.linuxidc.com)... 60.191.177.106
正在连接 linux.linuxidc.com (linux.linuxidc.com)|60.191.177.106|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2017-03-12 23:41:00 错误 404：Not Found。

--2017-03-12 23:41:00--  http://linux.linuxidc.com/2014%E5%B9%B4%E8%B5%84%E6%96%99/4%E6%9C%88/20%E6%97%A5/Ubuntu%2014.04%20%E5%AE%89%E8%A3%85%20WPS/symbol-fonts_1.2_all.deb
再次使用存在的到 linux.linuxidc.com:80 的连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2017-03-12 23:41:00 错误 404：Not Found。

dpkg-deb：错误：读取包文件 symbol-fonts_1.2_all.deb 失败: No such file or directory
mv: 无法将'wps-office_10.1.0.5672~a21_x86_64' 移动至'wps-office/wps-office_10.1.0.5672~a21_x86_64': Directory not empty
find: ‘../usr’: No such file or directory
cp: 缺少了文件操作数
Try 'cp --help' for more information.
错误：%prein(wps-office-10.1.0.5672-1.a21.net.x86_64) 脚本执行失败，退出状态码为 123
Error in PREIN scriptlet in rpm package wps-office
Error in PREIN scriptlet in rpm package wps-office
wps-office-10.1.0.5672-1.a21.net.x86_64 假定被安装但并非这样！
  验证: wps-office-10.1.0.5672-1.a21.net.x86_64                                                        1/1 

失败:
  wps-office.x86_64 10.1.0.5672-1.a21.net                        `

fzug-testing的office无法安装

**Comment by wsws1996** [comment]
而且在装完官方的最新rpm包之后，如果用dnf更新，会提示需要更新wps，版本号和现有的版本号一样
上次元数据过期检查：0:18:15 前，执行于 Fri May 12 20:21:01 2017。
依赖关系解决。
 Package         架构        版本                       仓库               大小
升级:
 wps-office      x86_64      10.1.0.5672-1.a21.net      fzug-testing      410 k

事务概要
升级  1 软件包

总下载：410 k
确定吗？[y/N]

**Comment by alick** [comment]
@MatcherAny symbol-fonts_1.2_all.deb 下载链接失效的问题，应该已经修复了：https://github.com/FZUG/repo/commit/3552e28d278c0be07568a931dbe12a12f237317a

**Comment by alick** [comment]
@wsws1996 应该避免混用wps官方rpm包和这个软件源的网站安装包，因为二者内容是一样的。用了FZUG软件源就最好不要从wps官方下载安装rpm。如果想用wps官方rpm，同时不想禁用FZUG软件源，也许可以试试 yum.conf 里的 installonlypkgs 选项。

有后续问题请新开 Issue。

**Comment by sztsian** [comment]
我觉得似乎可以关闭这个了。
