### ISSUE TITLE
搜狗拼音不正常显示

### ISSUE THREAD

**Issue by uxov** [FZUG/repo#228]
Fedora 25 更新后,搜狗拼音打字不能显示汉字.

4.9.13-201.fc25.x86_64

![1489668456698](https://cloud.githubusercontent.com/assets/17727735/23997047/cdd13250-0a1d-11e7-8b5d-de4d4c052dc7.jpg)

**Comment by alick** [comment]
参考下 #43 中的解决办法？

**Comment by uxov** [comment]
谢谢! 使用了 #43 中 dc3671 的方法:  
删除~/.config下的搜狗输入配置文件夹：SogouPY、SogouPY.users、sogou-qimpanel  

成功解决了我的问题.
