### ISSUE TITLE
有冲突

### ISSUE THREAD

**Issue by sunznx** [FZUG/repo#23]
file /usr/lib/rpm/macros.d/macros.pyqt5 from install of python-qt5-5.4.1-1.fc22.x86_64 conflicts with file from package python3-qt5-5.5-1.fc22.x86_64

**Comment by alick** [comment]
您在试图安装哪个软件包？

**Comment by sunznx** [comment]
deepin-screenshot

**Comment by Endle** [comment]
请问能贴出完整的 terminal output 吗？并具体说一下如何重现？
谢谢

**Comment by 1dot75cm** [comment]
@sunznx
需要装同一个版本的（5.5-1.fc22.x86_64 ） python3-qt5 和 python-qt5。感觉像是源信息有问题，单独更新一下 python-qt5，然后再安装 deepin-screenshot 试试。
如果存在文件冲突导致无法更新， 卸载旧包，然后装新包一般就可以了。（卸载旧包一般会卸载相关依赖软件，可以记录下来卸载了什么，更新 python-qt5 以后再安装回去；或者使用 rpm 命令强制卸载python-qt5，再使用 dnf 更新 python-qt5 至 5.5 即可，这样一般不会造成依赖问题。）

**Comment by sunznx** [comment]
我先将 fedora.repo 换成 fedora.repo.bak 然后安装完之后 再换回去 解决了
