### ISSUE TITLE
Atom 1.16 available

### ISSUE THREAD

**Issue by exploide** [FZUG/repo#233]
Would be great to have an updated build available at copr 😉

**Comment by xenithorb** [comment]
@1dot75cm Please update the atom package. Thank you :)

It also looks like 1.17 is on the way soon.

**Comment by 1dot75cm** [comment]
It test pass in Fedora 25. Please wait for rpm package on [Copr/556319](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/556319/).  @xenithorb  @exploide

**Comment by xenithorb** [comment]
Checks out, 1.17.0 installed and worked fine, thank you!

**Comment by exploide** [comment]
Awesome, thank you. It seems to work, so I'll close this issue. 👍 

The only thing that I noticed: The shipped electron version 1.3.13 is quite old. Aren't recent Atom builds based on newer versions of electron?

**Comment by 1dot75cm** [comment]
yes, i will update new version of electron later. @exploide
