### ISSUE TITLE
Fedora官方源的bochs过于陈旧

### ISSUE THREAD

**Issue by nogpgcheck** [FZUG/repo#234]
希望添加bochs2.6.9进入源中。
fedora2425官方源都是262，而且BUG多多，无法正常使用。
希望FDZH能发扬一贯的优良传统，帮助我，谢谢！
此致

**Comment by cheese** [comment]
给 Fedora 报了个 issue
https://bugzilla.redhat.com/show_bug.cgi?id=1447171

**Comment by nogpgcheck** [comment]
我猜是rpmfusion太慢并不是fedora本身的问题
在 2017/5/2 10:16, Robin Lee 写道:

**Comment by nogpgcheck** [comment]
爱你哦~


在 2017/5/2 10:16, Robin Lee 写道:

**Comment by sztsian** [comment]
Hi,
这条issue似乎不明确。 @nogpgcheck 你是表达rpmfusion太慢，还是bochs太陈旧？ bochs并不在rpmfusion中。如果关于rpmfusion太慢的问题，可以考虑使用[TUNA的rpmfusion镜像](https://mirrors.tuna.tsinghua.edu.cn/help/rpmfusion/) 或者[USTC的rpmfusion镜像](https://lug.ustc.edu.cn/wiki/mirrors/help/rpmfusion)。对于bochs陈旧的问题，参见Robin报的bug。
由于该issue与FZUG源无关，关闭该issue。

**Comment by nogpgcheck** [comment]
最早是想让rpmfusion加上bochs
但是丫的太慢啦
就想让fdzh加上去

发自我的 iPhone

在 2017年5月2日，上午10:50，Zamir SUN <notifications@github.com> 写道：

Hi,
这条issue似乎不明确。 @nogpgcheck 你是表达rpmfusion太慢，还是bochs太陈旧？ bochs并不在rpmfusion中。如果关于rpmfusion太慢的问题，可以考虑使用TUNA的rpmfusion源。对于bochs陈旧的问题，参见Robin报的bug。
由于该issue与FZUG源无关，关闭该issue。

**Comment by sztsian** [comment]
> 最早是想让rpmfusion加上bochs

哦，是这个意思啊。
rpmfusion等第三方源通常不会添加Fedora官方已经有的软件包。Fedora中文用户组也旨在为Fedora官方源中没有的软件包和rpmfusion中没有的软件包进行打包。若存在同一个包来自不同的软件源，通常会带来各种冲突，如 https://github.com/FZUG/repo/issues/224 。

**Comment by cheese** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2017-6e54134f4c
维护者已经提交更新

**Comment by nogpgcheck** [comment]
非常感谢诸位的帮助！感激不尽，如有机会必当涌泉相报!

发自我的 iPhone

在 2017年5月6日，上午2:30，Robin Lee <notifications@github.com> 写道：

https://bodhi.fedoraproject.org/updates/FEDORA-2017-6e54134f4c
维护者已经提交更新

**Comment by nogpgcheck** [comment]
在2017-05-07“dnf makecache”操作之后，bochs269依旧是不可活取，可获取的还是262


在 2017/5/6 2:30, Robin Lee 写道:

**Comment by sztsian** [comment]
> 在2017-05-07“dnf makecache”操作之后，bochs269依旧是不可活取，可获取的还是262

Hi,
刚刚看了一下，Bochs 在Fedora Bodhi中仍处于testing状态。仍需等待几天才会进入updates源。

**Comment by nogpgcheck** [comment]
但我把testing打开还是找不到啊


在 2017/5/7 16:44, Zamir SUN 写道:

**Comment by sztsian** [comment]
> 但我把testing打开还是找不到啊 

是的。我这儿也找不到。
我查看了bodhi，维护者是7小时之前刚刚推送到testing. 而从Fedora主源到镜像还有延迟（有些镜像12小时才同步一次，有些更长）。所以我觉得这是可以理解的。建议明天再试试。

**Comment by linuxqiao** [comment]
You can add your test results/comments or feedback
to FEDORA-2017-6e54134f4c, like "+1" actions.
This can speed up its process.

--
Thanks,
Qiao
