### ISSUE TITLE
Fedora25的FZUG源中没有为知笔记

### ISSUE THREAD

**Issue by orangeclk** [FZUG/repo#236]
请问能添加吗？谢谢！或者能告诉我该怎样添加吗？

**Comment by sztsian** [comment]
Hi,
感谢报告。
源中是有为知笔记的SPEC的。看起来应该是编译失败了。

**Comment by 1dot75cm** [comment]
前一段时间，为知笔记 开发比较缓慢， 而且开发人员没有为 Release 版本打 Tag，造成社区维护也有点困难， 以后会定期进行新版本的编译测试。

建议有需求的用户，购买它的 VIP， 只有有 Money 才能更好的支持开发，提高代码质量，才有希望搞上 CI 提高测试效率。 @orangeclk

**Comment by orangeclk** [comment]
我就是年费vip。所以说短期内不大会维护这个源了是吗？

**Comment by 1dot75cm** [comment]
2.5.1 本地测试通过，可以添加 [Wiznote Copr](https://copr.fedorainfracloud.org/coprs/mosquito/wiznote/build/557101/) 源进行更新。 @orangeclk 

我未购买 VIP，笔记无法上传，这部分功能您可以测试一下， 如有问题可向官方汇报。

**Comment by robberphex** [comment]
Hi, 我自己测试了一下，用master分支上的`wiznote.spec`文件，是可以编译出`~/rpmbuild/RPMS/x86_64/wiznote-2.5.6-1.git10a9fe2.fc27.x86_64.rpm`这个包的。

@1dot75cm @sztsian 为何`https://repo.fdzh.org/FZUG/free/26/x86_64/`页面的wiznote还是2.5.1版本？

**Comment by sztsian** [comment]
感谢 @RobberPhex 。
我看了下log，F26 massive rebuild 时采用的snapshot是 https://github.com/FZUG/repo/commit/0d1f7feb060dc53515eb6d37c0b4c6dff0d2f0e6 ，而wiznote-2.5.6-1是在两天之后更新的。加上现在CI有问题，所以源里仍然是旧版本。

**Comment by sztsian** [comment]
刚刚已经把 wiznote-2.5.6-1.git10a9fe2.fc26.x86_64.rpm 发给了 @1dot75cm 。待他有时间时合并到repo就可以啦

**Comment by sztsian** [comment]
Fedora 25 已经停止支持。
