### ISSUE TITLE
269bochs的fedora25还是无法获取

### ISSUE THREAD

**Issue by nogpgcheck** [FZUG/repo#238]
说是已经移动到稳定源里面去了
但是makecache之后bochs还是不出来269，还是262的
截图什么的都有其实但是怎么上传呢

[root@localhost ~]# dnf makecache
Failed to synchronize cache for repo 'fzug-nonfree-source'，禁用。
Failed to synchronize cache for repo 'fzug-free-source'，禁用。
元数据缓存已建立。
[root@localhost ~]# dnf install bochs-
bochs-2.6.2-10.fc24.i686             bochs-devel-2.6.2-10.fc24.i686
bochs-2.6.2-10.fc24.x86_64           bochs-devel-2.6.2-10.fc24.x86_64
bochs-bios-2.6.2-10.fc24.noarch      bochs-gdb-2.6.2-10.fc24.x86_64
bochs-debugger-2.6.2-10.fc24.x86_64

**Comment by sztsian** [comment]
Bodhi里显示是15小时之前push的。我看了Fedora官方的情况是有了。
我看了下国内最大的两个mirror：
USTC上次同步时间是16小时之前，上游是Fedora官方。所以今天刚好错过了。
TUNA的上游是kernel.org，而kernel.org还没有bochs-2.6.9-2.所以TUNA也至少还要等到明天。
而国内其他几个源的上游很可能是TUNA或者USTC，或者其他二级源，所以通常会比USTC和TUNA还慢。
综上所述，您再等等。

**Comment by nogpgcheck** [comment]
我的源除了FDZH以外就是系统自带的官方源咯


在 2017/5/18 20:28, Zamir SUN 写道:

**Comment by sztsian** [comment]
> 我的源除了FDZH以外就是系统自带的官方源咯

我来解释一下：
如果你不修改软件源配置，Fedora会默认通过mirrorlist机制给你推送一个理论上比较快的源列表。在大陆访问时，这个列表里包含的源通常就是国内几所大学的，以及sohu,163等。
我在前述回复中所提到的Fedora官方，是指所有软件源镜像的rsync源头。
各高校的软件源上游多数是USTC和TUNA。国内其他小一些的软件源通常也是从其他源同步的，这样就有一个同步时效的差异。这也是为什么需要等待。
但愿这次我解释明白了。。

**Comment by nogpgcheck** [comment]
收到了，谢谢您。以后还请多多担待

发自我的 iPhone

在 2017年5月19日，下午12:29，Zamir SUN <notifications@github.com> 写道：

我的源除了FDZH以外就是系统自带的官方源咯

我来解释一下：
如果你不修改软件源配置，Fedora会默认通过mirrorlist机制给你推送一个理论上比较快的源列表。在大陆访问时，这个列表里包含的源通常就是国内几所大学的，以及sohu,163等。
我在前述回复中所提到的Fedora官方，是指所有软件源镜像的rsync源头。
各高校的软件源上游多数是USTC和TUNA。国内其他小一些的软件源通常也是从其他源同步的，这样就有一个同步时效的差异。这也是为什么需要等待。
但愿这次我解释明白了。。

**Comment by sztsian** [comment]
我看了下我本机，已经能安装2.6.9版本了。所以关闭这个issue
