### ISSUE TITLE
atom 无法运行需更新

### ISSUE THREAD

**Issue by orangeclk** [FZUG/repo#239]
我从fzug源中安装的atom无法运行，且源中atom版本也较落后。

**Comment by 1dot75cm** [comment]
请使用 Copr 中的 Atom 源，已测试通过 1.17.0，正在编译。 @orangeclk https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/556319/

**Comment by orangeclk** [comment]
我点进链接，看到编译状态还是failed

**Comment by 1dot75cm** [comment]
https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/556371/
Fedora 25 x86_64 已经编译成功 @orangeclk

**Comment by orangeclk** [comment]
感谢！@1dot75cm

**Comment by 1dot75cm** [comment]
The Atom 1.33.0 is available in the mosquito/atom Copr repository.
