### ISSUE TITLE
可以将 staruml的 deb 包 转换成 rpm包吗

### ISSUE THREAD

**Issue by sunznx** [FZUG/repo#24]
地址 http://staruml.io/download

**Comment by alick** [comment]
似乎需要买许可才能用？这样的话中文社区源是无法收录的。http://staruml.io/license_comparison

**Comment by sunznx** [comment]
http://baike.baidu.com/link?url=COybH6GKq-uTk8sHbtWBjqIRRzjkumFc3_ljPOU757UFEcWV_m8YYcxlj5NsP42xZz2PSfFYGYxpNDFxpyz8oa = = 老师推荐用的... 好吧
