### ISSUE TITLE
Error install in fedora 25

### ISSUE THREAD

**Issue by nalakawula** [FZUG/repo#240]
here the log when i run : `sudo dnf install deepin-desktop deepin-session-ui deepin-launcher deepin-screenshot deepin-terminal`

Error: Transaction check error:
  file /usr/bin/dde-desktop conflicts between attempted installs of deepin-desktop-4.0.4-1.gita9a4c9e.fc25.x86_64 and deepin-file-manager-4.1.5-1.git99d7597.fc25.x86_64
  file /usr/share/applications/dde-computer.desktop conflicts between attempted installs of deepin-desktop-4.0.4-1.gita9a4c9e.fc25.x86_64 and deepin-file-manager-4.1.5-1.git99d7597.fc25.x86_64
  file /usr/share/applications/dde-trash.desktop conflicts between attempted installs of deepin-desktop-4.0.4-1.gita9a4c9e.fc25.x86_64 and deepin-file-manager-4.1.5-1.git99d7597.fc25.x86_64
  file /usr/share/dde-desktop/translations/dde-desktop_zh_CN.qm conflicts between attempted installs of deepin-desktop-4.0.4-1.gita9a4c9e.fc25.x86_64 and deepin-file-manager-4.1.5-1.git99d7597.fc25.x86_64

**Comment by 1dot75cm** [comment]
The `deepin-file-manager 4.1.5` is instead of `deepin-desktop` package. Please use following command:  @sumarouno 

`sudo dnf install deepin-file-manager deepin-dock deepin-session-ui deepin-launcher deepin-screenshot deepin-terminal`

**Comment by nalakawula** [comment]
Thanks, but i cancel my deepin instalation for some reason

**Comment by 1dot75cm** [comment]
You can try to install it on your Virtual Machine. @sumarouno

**Comment by sztsian** [comment]
Closing this issue as fixed.
