### ISSUE TITLE
安装搜狗拼音需要解决依赖关系，libfcitx却没有

### ISSUE THREAD

**Issue by abbaangel** [FZUG/repo#241]
dnf install sogoupinyin
上次元数据过期检查：0:01:47 前，执行于 Sat Jun  3 10:45:41 2017。
错误：nothing provides libfcitx-config.so.4()(64bit) needed by sogoupinyin-2.1.0.0082-2.fc25.x86_64

**Comment by cheese** [comment]
[cheese@cheese-1055T ~]$ dnf whatprovides 'libfcitx-config.so.4()(64bit)'
Last metadata expiration check: 13 days, 12:20:59 ago on Sun May 21 01:04:46 2017.
fcitx-libs-4.2.9.1-2.fc24.x86_64 : Shared libraries for Fcitx
Repo        : @System

fcitx-libs-4.2.9.1-2.fc24.x86_64 : Shared libraries for Fcitx
Repo        : fedora

[cheese@cheese-1055T ~]$ cat /etc/redhat-release 
Fedora release 25 (Twenty Five)

查了一下有这个包啊，运行 dnf info fcitx-libs 看看

**Comment by chinaluopiao** [comment]
搜狗输入法不知道怎么回事 经常死机

**Comment by alick** [comment]
Fedora 25 已不再支持，所以关闭该issue。
