### ISSUE TITLE
fedora25软件仓库无法安装软件

### ISSUE THREAD

**Issue by gfwei** [FZUG/repo#243]
大家好，我安装完fedora25工作站版本后，添加了中科大、清华的源后，软件仓库无法再安装任何软件了（比如当我安装stellarium时，提示：multiple matches of stellarium;0.15.2-1.fc25;x86_64;updates）。请问，这个问题该如何解决呢？谢谢了！

**Comment by sztsian** [comment]
首先，这个问题不是中文用户组repo的问题。所以恐怕不会有很多人在这儿回答。如需要更多细节，请订阅[邮件列表](https://lists.fedoraproject.org/archives/list/chinese@lists.fedoraproject.org/)，并在邮件列表里提问。

你的问题是因为你的本地配置里对同一个仓库配置了不同的地址，并且刚好这些地址的版本不一致导致。

你所说的“添加了中科大、清华的源”是指这两个源同时添加到源列表里么？如果是，那么这就是问题的起因。Fedora默认的源会根据你所在区域自动匹配较优的软件源（在中国大陆通常会获得USTC/TUNA/NJPTU/CUHK等），所以完全可以不修改软件源设置。如果是打算手动指定软件源，则必须首先将fedora默认的软件源禁用，并且同一个仓库只添加一个地址。
