### ISSUE TITLE
Need to support Fedora 23

### ISSUE THREAD

**Issue by Endle** [FZUG/repo#25]
Fedora 23 Beta is going to be released.
I think it's time to support Fedora 23 in FZUG now

**Comment by 1dot75cm** [comment]
ok，这几天就提供。

**Comment by 1dot75cm** [comment]
预计今天就可以全部更新完毕， 新加了 rime。rpmfusion 用 22 或 rawhide 就可以。
http://repo.fdzh.org/FZUG/23/x86_64/

**Comment by alick** [comment]
fixed?

**Comment by 1dot75cm** [comment]
一些包还没有重编译，使用了 fc22 的。另外，到现在还没有进行完整的功能测试。根据 http://repo.fdzh.org/visitor.html 显示的访问量来看，fc23 的测试打算在 fc23 release 前夕进行。
有时间的情况下，帮忙测试看看 @alick 。

**Comment by alick** [comment]
哦，全部重编译后就算完成吧。完整的功能测试有难度，我们没有那么多人力。（话说当初招募的志愿者们还能联系上不？）我会尽力测试我感兴趣的软件包。

**Comment by alick** [comment]
ping @1dot75cm

**Comment by biergaizi** [comment]
另外不知道这些包有没有采用 Hardened Build，如果用了会出现什么样的问题。

**Comment by sztsian** [comment]
Called for QA during the meeting today.

http://meetbot.fedoraproject.org/fedora-zh/2015-10-16/fedora-zh.2015-10-16-13.00.html

**Comment by 1dot75cm** [comment]
@biergaizi  fedora23 在 macros 中添加了 Hardened Build 相关选项 ，现在官方源中的所有包都已应用该特性。我刚刚已切换至 fc23，准备调整源中的包。

@sztsian Yes. 我已经看到了。

**Comment by sztsian** [comment]
Close as of already delivered?

**Comment by Endle** [comment]
恩，已经解决了。如果有某个软件用不了，那就另开issue吧
