### ISSUE TITLE
求助：fedora25网易云音乐无法播放

### ISSUE THREAD

**Issue by kjartanjph** [FZUG/repo#257]
一直提示加载失败网络错误，gstreamer还有其他各种解码器都已经确认安装，但是还是无法解决，求助

**Comment by alick** [comment]
是否排除就是网络问题？

**Comment by kjartanjph** [comment]
网络肯定是没问题的，可以在线播放MV，也可以下载歌曲，就只是无法播放

**Comment by 1dot75cm** [comment]
网上有人说要装 gstreamer-plugins-good，暂未测试。 @kjartanjph

**Comment by alick** [comment]
Fedora 25 已经不再支持了，关闭 issue。如果在新版本 Fedora 上仍有该问题，请重新开启 (reopen) issue
