### ISSUE TITLE
请求加入新软件包 ccal

### ISSUE THREAD

**Issue by alick** [FZUG/repo#26]
ccal 是一个命令行的农历（阴历）小程序（用法和 cal 命令类似）

URL: http://ccal.chinesebay.com/ccal/ccal.htm
License: GPL, LGPL

**Comment by 1dot75cm** [comment]
Internal Server Error ，不知道什么情况。

**Comment by alick** [comment]
really? It seems fine to me.

ref: http://isup.me/http://ccal.chinesebay.com/ccal/ccal.htm

**Comment by 1dot75cm** [comment]
http://ccal.chinesebay.com/ccal/ccal.htm
这个连接是挂的，服务器版本都显示了，好像不怎么维护了，还用的 rhel5。
Apache/2.2.24 (Unix) mod_ssl/2.2.24 OpenSSL/0.9.8e-fips-rhel5 mod_auth_passthrough/2.1 mod_bwlimited/1.4 mod_fcgid/2.3.6

**Comment by sztsian** [comment]
@1dot75cm 北京联通，山东联通，山东教育网都能打开这个链接啊。

**Comment by 1dot75cm** [comment]
@sztsian  主页能打开，**但是** 源码包下不来。
^^ ～ 我联系一下作者吧。

**Comment by alick** [comment]
@1dot75cm ,

不是吧，我下载源码包（.tar.gz）也正常啊。。。如果需要的话，我可以直接传给你。

你可以试试从其他网络位置下载试试。可能需要联系你的ISP了……

**Comment by 1dot75cm** [comment]
http://ccal.chinesebay.com/ccal/ccal-2.5.3.tar.gz
百度了一下 ，搜到链接了。一会打包

suse 社区的小伙伴 03 年就打包了，真早。
http://download.opensuse.org/repositories/home:/zhonghuaren/Fedora_22/x86_64/

**Comment by 1dot75cm** [comment]
Done. http://repo.fdzh.org/visitor.html

**Comment by 1dot75cm** [comment]
Done. http://repo.fdzh.org/visitor.html

**Comment by alick** [comment]
似乎并没有加到软件源首页的列表里？

分类：实用工具 Utils
描述：命令行下的农历日历

**Comment by 1dot75cm** [comment]
Ok, 已添加

**Comment by alick** [comment]
Thanks!
