### ISSUE TITLE
Unable to update atom

### ISSUE THREAD

**Issue by hanaokaiwa** [FZUG/repo#260]
I was trying to update atom package on "Copr repo for atom owned by mosquito", and got the following error:
  file /usr/bin/apm from install of atom-1.18.0-0.1.x86_64 conflicts with file from package nodejs-atom-package-manager-1.18.2-1.gitcf5474e.fc26.x86_64

it should have an update package for nodejs-atom-package-manager or package nodejs-atom-package-manager should be marked as "Obsoletes" while updating to atom-1.18.0-0.1.x86_64.

**Comment by sophiekovalevsky** [comment]
This issue have been resolved?

**Comment by sztsian** [comment]
Hi,
This is issues tracker for packages in FZUG repo only. For @1dot75cm (aka mosquito in Fedora) owned repos please contact with him directly.

**Comment by sophiekovalevsky** [comment]
All right then. Thanks.
