### ISSUE TITLE
Pkg request: freefilesync

### ISSUE THREAD

**Issue by dengbangjie** [FZUG/repo#268]
FreeFileSync 是一款基于GPLv3协议的同步文件目录的程序。希望FZUG能收录这个软件。

网站: [FreeFileSync](https://www.freefilesync.org/)
最新源代码包: [https://www.freefilesync.org/download/FreeFileSync_9.3_Source.zip](https://www.freefilesync.org/download/FreeFileSync_9.3_Source.zip)

如能收录，万分感激。

**Comment by sztsian** [comment]
很遗憾，该软件现在已经不符合GPLv3了。我在其网站上没有找到版权声明，但找到了二进制[分发约束](https://www.freefilesync.org/faq.php#distribute)

> You are permitted to distribute the software subject to the following conditions:
The software must be distributed free of charge and without modification to the contents of the archive. Redistributing this archive with any files added, removed, or modified is prohibited. The inclusion of any individual file from this archive in another archive without the prior permission of the author is prohibited. 

上述条款只允许照原样分发其压缩包。所以我们无法将FreeFileSync打包。
