### ISSUE TITLE
版本仓库26下没有nonfree与testing

### ISSUE THREAD

**Issue by shensl** [FZUG/repo#270]
使用默认repo文件添加源会出现
“”“
同步仓库 'fzug-nonfree' 缓存失败，禁用。
同步仓库 'fzug-testing' 缓存失败，禁用。
”“”
错误，是否26已经不支持nonfree与testing？

**Comment by alick** [comment]
会支持 nonfree，但暂时还没。

testing 应该不会有，我们应该需要更新 FZUG.repo 文件以及 fzug-release.fc26 @1dot75cm @sztsian 

另外，这个“错误”并不影响使用。

**Comment by sztsian** [comment]
Hi,
现在nonfree里的包在F26编译都失败了。所以没有生成nonfree的目录。
因为这次不是通过CI编译的，所有的包都直接进入了free而没有经过testing，所以testing也没有f26。

中文用户组提供的默认repo配置里面设置了skip_if_unavailable，使用FZUG提供的repo文件的应该不受影响。

**Comment by 1dot75cm** [comment]
都添加了 metadata，不会报这个错误了。包有时间在移到 nonfree 里。 @shensl
