### ISSUE TITLE
F26+ nonfree 仓库为空

### ISSUE THREAD

**Issue by alick** [FZUG/repo#271]
F25 nonfree 仓库空了，例如 https://repo.fdzh.org/FZUG/nonfree/25/x86_64/

有用户已经遇到了 nonfree 被 dnf 自动禁用的现象 #92

**Comment by sztsian** [comment]
这是一个基础设施问题。估计暂时不会修复。
参考这条任务单 https://github.com/FZUG/repo/issues/130#issuecomment-231121311
对于F24 ~ F25, 在启用testing repo之后，由于FZUG RPM Update System会将所有包移动到free，所以nonfree长期是空的。

**Comment by alick** [comment]
所以是 FZUG RPM Update System 的 bug？或者说是仓库配置问题（本来应该分 free-testing 和 nonfree-testing 的）？

但是，我以为没有启用 testing 的必要，不如直接推到 free/nonfree 让用户帮忙测试，随时发现问题随时解决。

建议：
1. 将 free 中的 nonfree 软件包手动移到 nonfree
2. 将 testing 中软件包手动移动 free 或 nonfree
3. 删除 testing 仓库

**Comment by Endle** [comment]
Closing this issue since Fedora 25 is EOL
如果讨论仓库架构，我们是不是新开工单/移步#130？

**Comment by alick** [comment]
我repopen了，因为 F26+ 同样有这个问题

**Comment by alick** [comment]
求更新。

我能看到的目前打包的 nonfree 的只有 jdk 和 opera，F28 仓库里只有 opera，其版本严重落后（40.0 vs 最新 57.0）。

我的想法是：

1. 手动删除镜像站上的 opera-*.rpm
2. 如果有人想更新 opera (@1dot75cm ?)，那么尽快更新 spec。否则删除 spec，或标记为 retired
3. 鉴于 nonfree 实际为空，`.repo` 文件里把 nonfree 部分禁用

**Comment by alick** [comment]
@sztsian, FZUG RPM Update System 相关的脚本在哪里呢？

**Comment by sztsian** [comment]
>     1. 手动删除镜像站上的 opera-*.rpm

已经删除 f27/f28/f29 中的 opera*。明天同步的时候会同步到 tuna

>     2. 如果有人想更新 opera，那么尽快更新 spec。否则删除 spec，或标记为 retired

最初这包是 nrechn 加的。现在他已经不在 github 了。所以我标为 obsoleted 了。

>     3. 鉴于 nonfree 实际为空，`.repo` 文件里把 nonfree 部分禁用

不必了。现在 FZUG 的 repo 配置都是 `skip_if_unavailable=True`

**Comment by alick** [comment]
@sztsian `skip_if_unavailable=True` 还是会检查这个仓库，出一行警告信息吧？如果没有内容，不妨禁用，应该能减少 dnf 命令执行时间。

**Comment by sztsian** [comment]
保留 nonfree 是为了将来仍然能拆分仓库。但是现在没时间做。
