### ISSUE TITLE
请求补充对单个rpm的build脚本及相关说明文档

### ISSUE THREAD

**Issue by dengbangjie** [FZUG/repo#274]
请问能否更新补充对单个软件的打包的脚本及说明文档。方便愿意帮忙测试的人来帮忙。可能能力有限，最近尝试使用cibuild并不是很顺利。

**Comment by dengbangjie** [comment]
F27月底就可能发布了。。

**Comment by sztsian** [comment]
Hi,
cibuild是运行在 FZUG repo 上的后端脚本。如果你是需要编译一个特定的软件包，可以尝试使用mock。如果你是打算批量编译，并且当前系统版本与预期版本一致，可以使用前几天我提交的 [rebuildtool.sh](https://github.com/FZUG/repo/blob/master/repos/rebuildtool.sh)。
此外，我们计划在10月份进行F27第一次 massive rebuild （基于F27 Beta）。

**Comment by dengbangjie** [comment]
非常感谢，我这几天试一试。

**Comment by 1dot75cm** [comment]
https://github.com/FZUG/repo/wiki/For-Packager

cibuild 是对 mock 的封装，本机编译测试直接用 mock 就好了。
cibuild.py 如果运行有什么错误也可以贴上来。 @Bangjie
