### ISSUE TITLE
fedora26没有sogoupinyin, xware-desktop, python3-keybinder

### ISSUE THREAD

**Issue by BruceChen2017** [FZUG/repo#275]
`dnf list --disablerepo=* --enablerepo=fzug-free --enablerepo=fzug-nonfree | grep -i fzug`  
并没有sogoupinyin和xware-desktop这两项，自然无法通过`dnf install xxxx`安装  

还有每次使用dnf或yum,前面都会出现各种同步仓库失败，这个今后能解决吗？

**Comment by BruceChen2017** [comment]
不好意思，刚才安装kwplayer遇到一个问题，kwplayer需要python3-keybinder，但上面的列表也没有，我试着`sudo pip3 install python3-keybinder`安装包成功也没用，`sudo dnf install python3-keybinder`则找不到这个东西。以上列表对比于[FDZH软件包列表](https://repo.fdzh.org/#)

**Comment by alick** [comment]
以后请针对每个问题分别提交issue。新建issue前先搜索是否已经被报告过。谢谢。

**Comment by alick** [comment]
On Sun, Oct 8, 2017 at 10:51 PM, BruceChen2017 <notifications@github.com>
wrote:

> dnf list --disablerepo=* --enablerepo=fzug-free --enablerepo=fzug-nonfree
> | grep -i fzug
> 并没有sogoupinyin和xware-desktop这两项，自然无法通过dnf install xxxx安装
>
因为它们构建失败了，所以不在软件源里。参见 #270


> 还有每次使用dnf或yum,前面都会出现各种同步仓库失败，这个今后能解决吗？
>

同样是 #270

**Comment by alick** [comment]
On Sun, Oct 8, 2017 at 11:57 PM, BruceChen2017 <notifications@github.com>
wrote:

> 不好意思，刚才安装kwplayer遇到一个问题，kwplayer需要python3-keybinder，但上面的列表也没有，我试着sudo
> pip3 install python3-keybinder安装包成功也没用，sudo dnf install python3-keybinder
> 则找不到这个东西。以上列表对比于FDZH软件包列表 <https://repo.fdzh.org/#>
>
>
有可能是 `sudo pip3 install ...` 安装到的 `/usr/local/...` 目录不在默认的 PYTHONPATH
里。也有可能是 kwplayer 的其他问题。需要更多错误信息。

中文社区软件源里没有，同样是因为对应包构建失败了。另外，这个项目可以在 pypi 上找到，但其上游链接 github 已经 404 了。

**Comment by sztsian** [comment]
- xware-desktop
上游所使用的方式已经过期，且上游已经不存在了，所以该包被移除了。参考 https://github.com/FZUG/repo/issues/101
- sogoupinyin
在Fedora 26 massive rebuild时失败了。刚刚提交了一个修复，https://github.com/FZUG/repo/pull/278 ， 应该会解决这个问题。
- python3-keybinder
上游消失了。所以整个kwplayer估计都会失败。
