### ISSUE TITLE
F27: x86_64/ 下面有个 noarch/ ，目录组织有点奇怪

### ISSUE THREAD

**Issue by alick** [FZUG/repo#279]
x86_64/ 下面有个 noarch/ ，目录组织感觉有点奇怪:

https://repo.fdzh.org/FZUG/free/27/x86_64/

**Comment by yssource** [comment]
**no architecture # 缩写, noarch** 

 - x86_64 # 64位
 - i386     # 32位
 - noarch # 非以上两种架构

**Comment by alick** [comment]
目录结构应该是

    27/x86_64/
    27/noarch/
    ...

**Comment by sztsian** [comment]
已经修复了。
https://mirrors.tuna.tsinghua.edu.cn/fzug/free/27/x86_64/
