### ISSUE TITLE
rebuild vscode for fedora 27

### ISSUE THREAD

**Issue by muayyad-alsadi** [FZUG/repo#280]
the current package can't be installed it says

```
 - nothing provides nodejs(v8-abi5) >= 5.1 needed by vscode-1.16.1-1.fc26.x86_64
```

but I already have `abi6` not `abi5`

```
nodejs(v8-abi) = 6.1
nodejs(v8-abi6) = 6.1
```

**Comment by 1dot75cm** [comment]
The vscode 1.29.1 package is testing (Rawhide) in the mosquito/vscode Copr repository. @muayyad-alsadi 

```
atom 1.33.0 - electron 3.0.10
vscode 1.29.1 - electron 3.0.10
```

https://copr.fedorainfracloud.org/coprs/mosquito/vscode/build/835522/

**Comment by 1dot75cm** [comment]
The vscode 1.30.0 is available in the mosquito/vscode Copr repository. @muayyad-alsadi 
Closed this
