### ISSUE TITLE
为知笔记 wiznote 在 fedora27/29下崩溃

### ISSUE THREAD

**Issue by hooklab** [FZUG/repo#282]
点击任何一篇笔记 或新建 都会 core 错误

[10033.676619] wiznote[22439]: segfault at 7fcee8649d50 ip 00007fcef22302aa sp 00007ffcbbe95150 error 7 in libquazip.so.1.0.0[7fcef2218000+2d000]
[10341.454701] pool[23027]: segfault at 0 ip 00007f13f0737510 sp 00007f13deafe680 error 6 in libmozjs-38.so[7f13f0271000+6a4000]
[10369.184619] pool[23072]: segfault at 0 ip 00007fe735dc1510 sp 00007fe73181a680 error 6 in libmozjs-38.so[7fe7358fb000+6a4000]
[10371.572900] pool[23099]: segfault at 0 ip 00007f02a4b81510 sp 00007f0293ffe680 error 6 in libmozjs-38.so[7f02a46bb000+6a4000]
[10376.089908] pool[23129]: segfault at 0 ip 00007f26553af510 sp 00007f2650e08680 error 6 in libmozjs-38.so[7f2654ee9000+6a4000]
[10818.568747] pool[23830]: segfault at 90 ip 00007feab329e500 sp 00007feaafcf9680 error 4 in libmozjs-38.so[7feab2dd8000+6a4000]
[11024.556159] WizDocumentWebV[24202]: segfault at 7f24f9638d50 ip 00007f250321f2aa sp 00007f2436bda930 error 7 in libquazip.so.1.0.0[7f2503207000+2d000]
[11070.959010] pool[24297]: segfault at 90 ip 00007fd002be1500 sp 00007fcffcffe680 error 4 in libmozjs-38.so (deleted)[7fd00271b000+6a4000]
[11253.660662] pool[24603]: segfault at 90 ip 00007f5090d4f500 sp 00007f5056ffe680 error 4 in libmozjs-38.so[7f5090889000+6a4000]

**Comment by sztsian** [comment]
现在 wiznote 已经在 Fedora 29 了。能试下还有这个问题么？我没有 wiznote 账户。

**Comment by hooklab** [comment]
> 现在 wiznote 已经在 Fedora 29 了。能试下还有这个问题么？我没有 wiznote 账户。

同样崩溃在fd29下,不过报错信息不一样


[ying@ying ~]$ wiznote
[WARNING]: QWidget::setLayout: Attempting to set QLayout "" on QMainWindow "", which already has a layout ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (-5) ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: QObject::connect: No such signal WizDocumentWebViewPage::actionTriggered(QWebEnginePage::WebAction) ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: Empty filename passed to function ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
[INFO] client version: QTLINUX(2.6.7)
[INFO] [Sync] "----------同步开始----------"
[INFO] [Sync] "连接服务器"
[INFO] [Sync] "登录"
[INFO] [Sync] "获取企业群组信息"
[INFO] [Sync] "获取群组信息"
Received signal 11 SEGV_ACCERR 7f3ffa1ad9f0
#0 0x7f3ffd724e7e <unknown>
#1 0x7f3ffd724f90 <unknown>
#2 0x7f3ffd7255c7 <unknown>
#3 0x7f40027bf030 <unknown>
#4 0x7f400264e46f QuaZip::QuaZip()
#5 0x55a74888d312 JlCompress::extractDir()
#6 0x55a74888d8e3 WizUnzipFile::extractZip()
#7 0x55a748932d14 WizDatabase::extractZiwFileToFolder()
#8 0x55a748933022 WizDatabase::documentToHtmlFile()
#9 0x55a74893318b WizDatabase::documentToTempHtmlFile()
#10 0x55a748ae7dde WizDocumentWebViewLoaderThread::run()
#11 0x7f3ff9f674bb <unknown>
#12 0x7f40027b458e start_thread
#13 0x7f3ff9aa56a3 __GI___clone
  r8: 00007f3f1c0001d0  r9: 0000000000000078 r10: 00007f3f1c0008d0 r11: 0000000000000080
 r12: 00007f3f23ffe910 r13: 00007f3f23ffe910 r14: 00007f3f23ffe908 r15: 00007f3f23ffea90
  di: 00000000000000e1  si: 00007f3f1c009dd0  bp: 00007f3f1c0068b0  bx: 00007f3f1c009c80
  dx: 00007f3f1c009c01  ax: 00007f3ffa1ad9e0  cx: 00007f3f1c000020  sp: 00007f3f23ffe8a0
  ip: 00007f400264e46f efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000007
 trp: 000000000000000e msk: 0000000000000000 cr2: 00007f3ffa1ad9f0
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[1:1:0100/000000.520025:ERROR:broker_posix.cc(43)] Invalid node channel message

**Comment by hooklab** [comment]
> > 现在 wiznote 已经在 Fedora 29 了。能试下还有这个问题么？我没有 wiznote 账户。
> 
> 同样崩溃在fd29下,不过报错信息不一样
> 
> [ying@ying ~]$ wiznote
> [WARNING]: QWidget::setLayout: Attempting to set QLayout "" on QMainWindow "", which already has a layout ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (-5) ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: QObject::connect: No such signal WizDocumentWebViewPage::actionTriggered(QWebEnginePage::WebAction) ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: Empty filename passed to function ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [WARNING]: QFont::setPixelSize: Pixel size <= 0 (0) ((null):0, (null))
> [INFO] client version: QTLINUX(2.6.7)
> [INFO] [Sync] "----------同步开始----------"
> [INFO] [Sync] "连接服务器"
> [INFO] [Sync] "登录"
> [INFO] [Sync] "获取企业群组信息"
> [INFO] [Sync] "获取群组信息"
> Received signal 11 SEGV_ACCERR 7f3ffa1ad9f0
> #0 0x7f3ffd724e7e 
> #1 0x7f3ffd724f90 
> #2 0x7f3ffd7255c7 
> #3 0x7f40027bf030 
> #4 0x7f400264e46f QuaZip::QuaZip()
> #5 0x55a74888d312 JlCompress::extractDir()
> #6 0x55a74888d8e3 WizUnzipFile::extractZip()
> #7 0x55a748932d14 WizDatabase::extractZiwFileToFolder()
> #8 0x55a748933022 WizDatabase::documentToHtmlFile()
> #9 0x55a74893318b WizDatabase::documentToTempHtmlFile()
> #10 0x55a748ae7dde WizDocumentWebViewLoaderThread::run()
> #11 0x7f3ff9f674bb 
> #12 0x7f40027b458e start_thread
> #13 0x7f3ff9aa56a3 __GI___clone
> r8: 00007f3f1c0001d0 r9: 0000000000000078 r10: 00007f3f1c0008d0 r11: 0000000000000080
> r12: 00007f3f23ffe910 r13: 00007f3f23ffe910 r14: 00007f3f23ffe908 r15: 00007f3f23ffea90
> di: 00000000000000e1 si: 00007f3f1c009dd0 bp: 00007f3f1c0068b0 bx: 00007f3f1c009c80
> dx: 00007f3f1c009c01 ax: 00007f3ffa1ad9e0 cx: 00007f3f1c000020 sp: 00007f3f23ffe8a0
> ip: 00007f400264e46f efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000007
> trp: 000000000000000e msk: 0000000000000000 cr2: 00007f3ffa1ad9f0
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> [1:1:0100/000000.520025:ERROR:broker_posix.cc(43)] Invalid node channel message

能启动起来，点击笔记　或新建　就如上崩溃退出了

**Comment by hooklab** [comment]
[ying@ying ~]$ uname -a 
Linux ying 4.19.13-300.fc29.x86_64 #1 SMP Sat Dec 29 22:54:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sztsian** [comment]
现在在推测是上游的问题了

**Comment by alick** [comment]
关闭，因为可能是上游bug，而且Fedora 29已经不再支持

**Comment by cheese** [comment]
可以考虑使用 flatpak 版本 https://flathub.org/apps/details/com.wiz.Note
