### ISSUE TITLE
OUTAGE: FZUG repo server not reachable 服务器失联

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#285]
Just now I received report from users that FZUG repo is not reachable. And we checked the FDZH site (FDZH is our sponsor for this server instance), the server is also offline. We are now working to 
1. Figure out the cause
2. Finding alternative place to hold the repo

刚刚接到 Fedora 中文用户组源 的用户报告，中文用户组源无法访问。我们尝试访问赞助商FDZH的主站发现服务器似乎离线了。我们正在
1. 找出根源；
2. 寻找存储软件源的替代服务。

**Comment by tvvocold** [comment]
原因是我们的赞助商 UCloud 提供的带宽服务到期了，正在和赞助商沟通续费事宜。预计今天能恢复。

**Comment by tvvocold** [comment]
Update：赞助商已同意并提供了带宽的续费，服务已恢复。（如果打不开请刷新 DNS 缓存或重启网络重试，或检查 ping repo.fdzh.org 的 IP 结果是否为最新的 110.79.20.123，也可以手动修改 hosts 文件）

**Comment by sztsian** [comment]
感谢 @tvvocold ！
我们也在积极寻找办法降低对fdzh服务器资源的占用。这个issue将在此后关闭。

**Comment by alick** [comment]
我这里解析的 IP 地址已经是新的，但是网站还是连接超时。但 isup.me 说只是我这的问题。是限制了国外访问么？

**Comment by sztsian** [comment]
状态更新：
Fedora 中文用户组源已经恢复运行。
为了避免该类事件的发生我们正在与清华大学TUNA协会合作以实现容灾。与 TUNA 的合作已经开始。

Updates:

Fedora Chinese User Group repo is now back online.
And we are currently working with Tsinghua University TUNA Association
to make our repo fault tolerance. The cooperation with TUNA is just
starting.

**Comment by tvvocold** [comment]
@alick  没有限制国外访问，你可以刷新浏览器缓存或更换浏览器访问试试。

**Comment by alick** [comment]
@tvvocold 嗯，现在好了 😄
