### ISSUE TITLE
vscode Fedora 27 install fails due to missing dependencies: electron

### ISSUE THREAD

**Issue by sferich888** [FZUG/repo#286]
$ sudo dnf install vscode
Failed to synchronize cache for repo 'ivoarch-gnome-shell-extension-tilix-dropdown', disabling.
Last metadata expiration check: 0:03:35 ago on Tue 19 Dec 2017 09:27:15 AM EST.
Error: 
 Problem: conflicting requests
  - nothing provides electron = 1.6.9 needed by vscode-1.18.1-1.fc27.x86_64

**Comment by Triple-Z** [comment]
I think you should read this: https://code.visualstudio.com/docs/setup/linux

**Comment by 1dot75cm** [comment]
The vscode 1.29.1 package is testing (Rawhide) in the mosquito/vscode Copr repository. @sferich888 

```
atom 1.33.0 - electron 3.0.10
vscode 1.29.1 - electron 3.0.10
```

https://copr.fedorainfracloud.org/coprs/mosquito/vscode/build/835522/

**Comment by 1dot75cm** [comment]
The vscode **1.30.0** is available in the mosquito/vscode Copr repository. @sferich888
Closed this.
