### ISSUE TITLE
重打包网易云音乐1.1?

### ISSUE THREAD

**Issue by ghost** [FZUG/repo#288]
我用alien和rpmrebuild从官方的netease-cloud-music_1.1.0_amd64_ubuntu.deb转换出了一个能用的rpm包, 正常使用没有出现问题, 原先在KDE上点击标题栏就拖动窗口的bug也解决了, 是不是可以重打包了?

![screenshot_20171229_021224](https://user-images.githubusercontent.com/24662041/34419269-cec92b7e-ec3d-11e7-8b88-8b68e62632ec.png)

具体步骤: 下载ubuntu版本的网易云音乐, 用`alien -r [deb]`转换成rpm包, 然后用`rpmrebuild -e -p [rpm]`修改spec, 把libjasper.so.1改成fedora的libjasper.so.4, 直接删掉libqcef.so的依赖(ubuntu版自带了这个库不明白为什么还要依赖), 然后把最后面files部分`/`,`/usr`,`/usr/bin`之类不是网易云音乐建立的文件夹属性删掉, 再生成rpm包就可以用了

**Comment by sztsian** [comment]
Hi,
感谢您提供的详尽信息。
我们会尽快了解新版网易云音乐的许可协议约束，如果允许的情况下我们会更新软件包。
