### ISSUE TITLE
fontconfig-infinality和freetype-infinality找不到

### ISSUE THREAD

**Issue by zendo** [FZUG/repo#290]
未找到匹配的参数： fontconfig-infinality
未找到匹配的参数： freetype-infinality
字体渲染教程是不是过时了？求更新F27中文渲染方案

**Comment by sztsian** [comment]
Hi,

由于~-infinality 会[破坏wine](https://github.com/FZUG/repo/issues/231)，在找到解决办法之前我们不会更新Fedora 27中的infinality字体包。

**Comment by zendo** [comment]
@sztsian 我不用 wine，可不可以把需要的安装包发一份给我？自己下了源码编译累惨了~~维护者的博客也挂了，完全不懂怎么安装配置使用。。。

**Comment by alick** [comment]
这种上游都消失了的项目，还要继续支持吗？

**Comment by zendo** [comment]
>  danielrenninghoff commented on 18 Sep 2016 
Hi, sorry but I won't support Fedora 25. Freetype 2.7 has  now implemented the v40 hinter which is similar to infinality hinting  and doesn't need any configuring. With this I feel like you can finally  get good font rendering with the default settings. Therefore I will  stick to the stock fonts and packages that come with fedora and won't  update this repository anymore. Sorry! If you feel like you need to  continue using infinality, feel free to port my packages to fedora 25  and compile them yourself.
--
[https://github.com/danielrenninghoff/infinality-ultimate-fedora/issues/20](https://github.com/danielrenninghoff/infinality-ultimate-fedora/issues/20)

infinality 项目已经停止开发了，fedora 打包者说 freetype v2.7 效果就相当于 infinality 渲染效果，不再更新。现在 freetype 版本已经是 v2.8，但是中文显示还是发虚，我们的中文该怎么办？

**Comment by alick** [comment]
@zendo “中文显示发虚”是另一个可能的问题，请到 [FZUG 的 irc/tg 或者 Ask Fedora 中文版块](https://fedoraproject.org/wiki/Zh)提问，提问时请附上截图。

**Comment by alick** [comment]
@sztsian @1dot75cm 我觉得我们可以淘汰(retire)这些包，关闭这个issue了
