### ISSUE TITLE
已打包 Electronic-Wechat 2.0.0 版本，求加入

### ISSUE THREAD

**Issue by Triple-Z** [FZUG/repo#291]
[electronic-wechat-2.0.0.x86_64.rpm](https://drive.google.com/open?id=1cMy04RiOL1Diba1NVclpYaQnbM17l04C)

**Comment by alick** [comment]
这个项目收录的是 spec 文件，不是最终的 rpm 包。请使用 pull request 添加新的 spec 文件，谢谢。

**Comment by Triple-Z** [comment]
好的，我学习一下。
