### ISSUE TITLE
证书过期

### ISSUE THREAD

**Issue by raontie** [FZUG/repo#292]
正在解析主机 repo.fdzh.org (repo.fdzh.org)... 110.79.20.123
正在连接 repo.fdzh.org (repo.fdzh.org)|110.79.20.123|:443... 已连接。
错误: “repo.fdzh.org” 的证书不可信。
错误: “repo.fdzh.org” 的证书已经过期。
证书已经过期

**Comment by raontie** [comment]
thank you : )

**Comment by sztsian** [comment]
已通知系统管理员。需等其处理。

**Comment by raontie** [comment]
666

**Comment by arisskz6** [comment]
I met the same problem~
```
Adding repo from: http://repo.fdzh.org/FZUG/FZUG.repo
Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://repo.fdzh.org/FZUG/FZUG.repo
 [SSL certificate problem: certificate has expired]
```

**Comment by raontie** [comment]
It seems that fzug's https certification is out of date

**Comment by kinoward** [comment]
还是没有修复......

**Comment by sztsian** [comment]
Please use TUNA mirror temporary (a little outdated): 
请临时使用TUNA镜像（内容略陈旧）

https://mirrors.tuna.tsinghua.edu.cn/fzug/

**Comment by 1dot75cm** [comment]
Fixed, thanks
