### ISSUE TITLE
Failed to synchronize cache for repo 'mosquito-brackets', disabling.

### ISSUE THREAD

**Issue by wyatt-herkamp** [FZUG/repo#293]
Failed to synchronize cache for repo 'mosquito-brackets', disabling.
`[wherkamp@wherkamp Downloads]$ sudo dnf install brackets
Failed to synchronize cache for repo 'mosquito-brackets', disabling.
Last metadata expiration check: 0:00:00 ago on Thu 01 Feb 2018 10:04:09 AM EST.
No match for argument: brackets
Error: Unable to find a match
`

**Comment by sztsian** [comment]
Hi,
Please directly reach out to mosquito (@1dot75cm ) for issue in his copr.
Although he is our main packager in Fedora Zhongwen User Group (aka FZUG), here we only collect issues for FZUG repo.
