### ISSUE TITLE
dnf can't install sogoupinyin in Fedora 27

### ISSUE THREAD

**Issue by acoolda** [FZUG/repo#295]
I follow this guide and  add FZUG.repo,but it can't work at all.I don't know how to add this repo in right way.Please HELP ME.
#Please NOTICE that my Fedora version is 27.I don't know whether it is bug,or just my careless.

I used this commad to add reop:
wget https://repo.fdzh.org/FZUG/FZUG.repo -P /etc/yum.repos.d/ 

it seems some guys add this repo correctly.So,please teach me.And update this right method on your site
that may help some people  like me.
Thanks guys.

**Comment by alick** [comment]
What do you mean by "can't work at all"? Is there any error message? Have you made sure the file `FZUG.repo` is under `/etc/yum.repos.d/` with the correct content?

**Comment by sztsian** [comment]
Hi,
To simplify the process, can you try the following way?

> sudo dnf install https://repo.fdzh.org/FZUG/free/27/x86_64/noarch/fzug-release-27-0.2.noarch.rpm
> sudo dnf makecache

They try the application you want to install from FZUG.

If this still do not work, please reply with
1. What application you want to install from FZUG?
2. Your command executed, and the corresponding output

Also you can use Chinese here if you want.

**Comment by acoolda** [comment]
@alick 我很确定的说是完全无法工作，当安装sougoupinyin的时候，会告诉我FZUG repo缓存禁用。我使用的是 # wget https://repo.fdzh.org/FZUG/FZUG.repo -P /etc/yum.repos.d/ 也很确定东西在里面。

**Comment by acoolda** [comment]
@sztsian 我尝试了将网站上面的Fedora26的安装方式做下修改（简单的将26改成27），但是告诉我找不到rpm包，我有时间了再去尝试一下您提供的方法。

希望更新一下Fedora中文社区里面Fedora27简易添加方式就像25，和26一样
半路出家，有什么麻烦到的，还请海涵。

**Comment by sztsian** [comment]
所以你的问题其实是不能安装 sogoupinyin 而不是源不工作。
Sogoupinyin 在 Fedora 26 和 Fedora 27 的编译中失败了。由于在 Fedora 25 中有很多人报告安装sougoupinyin 之后输入法频繁出现问题， Sogoupinyin 的其中一位维护者建议 Fedora 中使用其他输入法（因为 Sogoupinyin 不是开源软件，我们不能获得其代码，所以编译失败以及不能使用的问题我们无法解决）。

**Comment by sztsian** [comment]
> FZUG repo缓存禁用

这个提示应该是说 non-free 的缓存禁用吧？ F26/27 在这儿暂时没有 non-free 所以这也是正常的，不会影响其他包的使用。 而恰好你所述的 sogoupinyin 理应出现在 non-free 里，所以给你造成了上述误解。

**Comment by acoolda** [comment]
@sztsian 如果是这样的话那可能是因为我的问题，因为的确是有三个repo无法使用,'fzug-nonfree','fzug-testing','fzug-pr'，这三个仓库是无法使用的
感谢解答，因为i我一直不知道仓库中会有这些区分。看到仓库总是被提示 缓存失败禁用，以为仓库有问题。
@alick 同时也非常感谢您的解答

**Comment by sztsian** [comment]
对于 F26/F27, 'fzug-nonfree','fzug-testing','fzug-pr' 这三个仓库不能使用是正常的。因为现在软件包都存在于 fzug-free

**Comment by lulin** [comment]
When would be sogou-pinyin usable on Fedora-28. Or maybe I need to learn how to create rpm packages.

**Comment by sztsian** [comment]
> When would be sogou-pinyin usable on Fedora-28. Or maybe I need to learn how to create rpm packages.

Thanks for your interested in this repo. Basically it failed our packaging. Since SogouPinyin is not fully open source, so it's not in our priority.

**Comment by alick** [comment]
You are welcome to contribute a fixed version.
