### ISSUE TITLE
F27 UnrealEngine 4.19.0 rpmbuild rpm-strip failure

### ISSUE THREAD

**Issue by rajeebk** [FZUG/repo#300]
It looks like rpm-strip step in rpmbuild tries to strip non-Linux archive files with filename extension `.lib` thinking they are `ar` archives, and fails the install stage.

I had to add the following line in the spec file `rpms/unrealengine/ue4.huge`:

`%global __brp_strip_static_archive %{nil}
`

**Comment by alick** [comment]
Hi @rajeebk , thanks for your report. Can you prepare a pull request (PR) for this?

**Comment by alick** [comment]
Sorry, we are going to drop this package due to license and use case issues.
