### ISSUE TITLE
Infinallity for Fedora28 when will be ready  ?

### ISSUE THREAD

**Issue by toplinuxsir** [FZUG/repo#303]
Infinallity for Fedora28 when will be ready  ?

**Comment by sztsian** [comment]
Hi, do you mean fontconf-infinality?

Since it is not compatible with wine and some other applications, and constantly causing problems for users when installing applications or upgrading systems, we are no longer maintaining the fontconf-infinality package since Fedora 27.

**Comment by alick** [comment]
By the way, if you think there's any issue/bug with the default font
settings in Fedora, please report at the Red Hat Bugzilla against Fedora
product.


Regards,
Alick
