### ISSUE TITLE
netease-cloud-music构建失败的问题

### ISSUE THREAD

**Issue by robberphex** [FZUG/repo#306]
根据[日志](https://zsun.fedorapeople.org/pub/fzug/f28betalog/netease-cloud-music_netease-cloud-music.spec-FAILED.log)来看，netease-cloud-music打包失败的原因是没有找到`libssl1.0.0_1.0.2g-1ubuntu4.5_amd64.deb`。

但是目前 [netease-cloud-music.spec](https://github.com/FZUG/repo/blob/bcb6e30b86fc8ef27b9f98e2f8e8bbee6831732b/rpms/netease-cloud-music/netease-cloud-music.spec)中没有使用这个文件，而且这个文件早在`Mon Oct 03 2016`就修复了啊。

@sztsian 请重新构建下看看。

**Comment by sztsian** [comment]
问题是，我4月18日才合并[你的pr](https://github.com/FZUG/repo/pull/299)， 但是 Fedora 28 Beta Massive Rebuild 是4月7日做的。现在已经修好了。我已经在跑 Fedora 28 最终的 massive rebuild 了
