### ISSUE TITLE
Just add this line to the documentation

### ISSUE THREAD

**Issue by andreicristianpetcu** [FZUG/repo#31]
Hi, 
Add `Architecture` to the `options` section in [Configuration](https://github.com/FZUG/repo/wiki/use-yaourt#2configuration)

```
[options]
Architecture = auto
RootDir = /opt/arch/         # Very important!!! You should create this directory.
DBPath = /opt/arch/var/lib/pacman/    # Database Path
LogFile = /var/log/pacman.log
```

Thank you!

**Comment by alick** [comment]
Thanks.

A silly question: Can you explain why this is necessary? Is "auto" not the default value?

**Comment by andreicristianpetcu** [comment]
On Fedora 22 it is not. I get a strange error that $arch is not defined or something.

**Comment by alick** [comment]
OK. Seems the same as #18

**Comment by alick** [comment]
Thanks @andreicristianpetcu . I just added it.

@1dot75cm please check if there is any issue with my change.

**Comment by 1dot75cm** [comment]
The "Architecture = auto" option is default value in pacman.conf. Thanks report @andreicristianpetcu .
@alick Normal.

**Comment by andreicristianpetcu** [comment]
thank you!

**Comment by alick** [comment]
@1dot75cm It is default and it is required to specify? (wierd to me)

**Comment by andreicristianpetcu** [comment]
For me it was required. Don't know why.
