### ISSUE TITLE
centos7.5能用这个社区源吗

### ISSUE THREAD

**Issue by liangjiongyao** [FZUG/repo#315]
我发现centos7用该源安装软件总是报一些依赖错误，但我又非常想用该源，因为有好多想用的软件，有没有大神指导下
---> Package python3-cairo.x86_64 0:1.10.0-12.fc22 will be installed
---> Package python34-libs.x86_64 0:3.4.8-1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: bcloud-3.8.2-6.git3847155.fc23.noarch (fzug-testing)
           Requires: python3-cssselect
Error: Package: bcloud-3.8.2-6.git3847155.fc23.noarch (fzug-testing)
           Requires: python3-crypto
Error: Package: bcloud-3.8.2-6.git3847155.fc23.noarch (fzug-testing)
           Requires: python3-dbus
Error: Package: bcloud-3.8.2-6.git3847155.fc23.noarch (fzug-testing)
           Requires: python3-lxml
Error: Package: bcloud-3.8.2-6.git3847155.fc23.noarch (fzug-testing)
           Requires: python3-keyring
Error: Package: bcloud-3.8.2-6.git3847155.fc23.noarch (fzug-testing)
           Requires: python3-inotify
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

下面是我的fedora社区源配置文件
[root@localhost T4]# cat /etc/yum.repos.d/FZUG.repo 
[fzug-free]
name=FZUG fc$releasever - Free
baseurl=https://repo.fdzh.org/FZUG/free/22/x86_64/
skip_if_unavailable=True
metadata_expire=1d
gpgcheck=0
enabled=1

[fzug-nonfree]
name=FZUG fc$releasever - Nonfree
baseurl=https://repo.fdzh.org/FZUG/nonfree/23/x86_64/
skip_if_unavailable=True
metadata_expire=1d
gpgcheck=0
enabled=1

[fzug-testing]
name=FZUG fc$releasever - Testing
baseurl=https://repo.fdzh.org/FZUG/testing/23/x86_64/
skip_if_unavailable=True
metadata_expire=1d
gpgcheck=0
enabled=1

[fzug-free-source]
name=FZUG fc$releasever - Free - Source
baseurl=https://repo.fdzh.org/FZUG/free/$releasever/source/SRPMS/
skip_if_unavailable=True
metadata_expire=1d
gpgcheck=0
enabled=0

[fzug-nonfree-source]
name=FZUG fc$releasever - Nonfree - Source
baseurl=https://repo.fdzh.org/FZUG/nonfree/$releasever/source/SRPMS/
skip_if_unavailable=True
metadata_expire=1d
gpgcheck=0
enabled=0

**Comment by sztsian** [comment]
@liangjiongyao 感谢您对 Fedora 中文用户组 repo 的关注。由于贡献者有限，很遗憾我们暂时只打包 Fedora 使用的 rpm 包。

**Comment by alick** [comment]
抱歉我们精力有限无法支持 CentOS。您感兴趣的 bcloud 软件上游已经不再维护了，转而推荐其他替代品了：https://github.com/Yufeikang/bcloud
