### ISSUE TITLE
fedora27安装搜狗输入法问题

### ISSUE THREAD

**Issue by xunfanglv** [FZUG/repo#320]
运行命令imsettings-switch fcitx  报如下错误：

[ 1529550931.667868]: IMSettings-Daemon[31969]: INFO: Starting imsettings-daemon...
[ 1529550931.668707]: IMSettings-Daemon[31969]: INFO:   [HOME=/home/xiaowencheng/.config/imsettings]
[ 1529550931.668723]: IMSettings-Daemon[31969]: INFO:   [XINPUTRCDIR=/etc/X11/xinit/]
[ 1529550931.668734]: IMSettings-Daemon[31969]: INFO:   [XINPUTDIR=/etc/X11/xinit/xinput.d/]

[ 1529550931.668742]: IMSettings-Daemon[31969]: INFO:   [MODULEDIR=/usr/lib64/imsettings]

[ 1529550931.668751]: IMSettings-Daemon[31969]: INFO:   [MODULES=gsettings]

[ 1529550931.669952]: IMSettings-Daemon[31969]: INFO: Attempting to switch IM to fcitx [lang=zh_CN.UTF-8, desktop=GNOME, update=true]
org.gnome.SettingsDaemon.Keyboard.desktop exists. imsettings is going to be disabled.

[ 1529550931.758674]: IMSettings-Daemon[31969]: WARNING **: Current desktop isn't targeted by IMSettings.
[ 1529550931.761205]: IMSettings-Daemon[31969]: INFO: Unloading imesttings module: gsettings
[ 1529550931.761267]: IMSettings-Daemon[31969]: INFO: imsettings-daemon is shut down.

请问下可能是什么原因造成的？

**Comment by cheese** [comment]
详见 https://bugzilla.redhat.com/show_bug.cgi?id=1528892
不是 fcitx 的问题

**Comment by xunfanglv** [comment]
这个是fedora系统的问题吗？我看了你的这个链接，问题还没有得到解决？

**Comment by sztsian** [comment]
这个不是 Fedora 的问题。这个是 [gnome-settings-daemon](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/25) 的问题。
