### ISSUE TITLE
SSL Certificate Has Expired on FZUG repo

### ISSUE THREAD

**Issue by starvsion** [FZUG/repo#322]
basically,

-  when doing `wget https://repo.fdzh.org/FZUG/FZUG.repo -P /etc/yum.repos.d/ ` , it shows that the SSL cert has expired, 
- When visit repo.fdzh.org, it shows that the SSL cert expired 2 days ago. 
-  and when I managed to wget it, it shows `Failed to synchronize cache for repo 'fzug-free', disabling.` , 
- so I went to the URL in the repo file, it gives a NGINX 404 error

**Comment by LionTao** [comment]
same on my desktop too

**Comment by sztsian** [comment]
Hi all,

For now repo is also available in TUNA.

https://mirrors.tuna.tsinghua.edu.cn/fzug/free/28/x86_64/
https://mirrors.tuna.tsinghua.edu.cn/fzug/free/27/x86_64/

You can manually switch to use the above URL (according to your version) as a workaround.

**Comment by Triple-Z** [comment]
![image](https://user-images.githubusercontent.com/16285716/43629806-e077fb0e-9730-11e8-8a29-f7a0912bb3ae.png)

SSL 证书过期了

**Comment by alick** [comment]
close as fixed
