### ISSUE TITLE
Failed to synchronize cache

### ISSUE THREAD

**Issue by Miffyrc** [FZUG/repo#323]
Failed to synchronize cache for repo 'fzug-nonfree', disabling.
Failed to synchronize cache for repo 'fzug-pr', disabling.
Failed to synchronize cache for repo 'fzug-testing', disabling.
能告诉我这是为什么呢?

**Comment by sztsian** [comment]
这是正常现象。自从 Fedora 26 以来我们没有成功编译过 fzug-nonfree 的包。 fzug-pr 和 fzug-testing 默认就不应该开启。

**Comment by Miffyrc** [comment]
谢谢,我明白了
