### ISSUE TITLE
when will repos for fedora28 come

### ISSUE THREAD

**Issue by bookug** [FZUG/repo#329]
RT, I am waiting:)

**Comment by sztsian** [comment]
28 开始，源的地址在
https://mirrors.tuna.tsinghua.edu.cn/fzug/free/28/x86_64/

可以通过 
`dnf install https://mirrors.tuna.tsinghua.edu.cn/fzug/free/28/x86_64/fzug-release-28-0.1.noarch.rpm`
更新 Fedora 28 的地址。

（另外，RT 不是英语，是汉语）
