### ISSUE TITLE
KDE5 下，Fcitx 中文输入不能使用

### ISSUE THREAD

**Issue by lookforit** [FZUG/repo#33]
环境：
Fedora 22 + KDE5

安装Fcitx（包括sogoupinyin）后，在浏览器的地址输入栏可以正常输入，
但在其他一些软件中：如Konsole、Kwrite、KDE系统的其他输入栏，均无法输入中文，只能输入英文。
Fcitx配置、图标均能正常显示。
即使显示当前的状态为中文输入法，输入的还是英文。
已安装 Fcitx-qt5

**Comment by 1dot75cm** [comment]
刚才测试了一下，我这里 KDE5 可以正常输入，更新源中的 fcitx 4.2.9 了？
使用 fcitx-diagnose 诊断一下看看哪的问题。xinputrc 需要指向 fcitx.conf。

```
# alternatives --display xinputrc
链接当前指向 /etc/X11/xinit/xinput.d/fcitx.conf
```

**Comment by cheese** [comment]
用的哪个版本的 fcitx-qt5？

**Comment by lookforit** [comment]
@cheese 
fcitx-qt5.x86_64

**Comment by lookforit** [comment]
@1dot75cm 
从诊断输出来看，提示　**`环境变量 QT_IM_MODULE 的值被设为了 "xim" 而不是 "fcitx"`**

文件　**/etc/X11/xinit/xinput.d/fcitx.conf**　的内容

``` bash
XIM=fcitx
XIM_PROGRAM=/usr/bin/fcitx
ICON="/usr/share/pixmaps/fcitx.png"
XIM_ARGS="-D"
PREFERENCE_PROGRAM=/usr/bin/fcitx-configtool
SHORT_DESC="FCITX"
GTK_IM_MODULE=fcitx
if test -f /usr/lib/qt4/plugins/inputmethods/qtim-fcitx.so || \
   test -f /usr/lib64/qt4/plugins/inputmethods/qtim-fcitx.so;
then
    QT_IM_MODULE=fcitx
else
    QT_IM_MODULE=xim
fi

```

不知这个是否有问题，如何更改？
就是在ｋｏｎｓｏｌｅ、ｋｗｒｉｔｅ下无法输入中文。

## fcitx-diagnose 输出
1.  当前 locale:
   
   ```
       LANG=zh_CN.UTF-8
       LC_CTYPE=zh_CN.UTF-8
       LC_NUMERIC="zh_CN.UTF-8"
       LC_TIME="zh_CN.UTF-8"
       LC_COLLATE="zh_CN.UTF-8"
       LC_MONETARY="zh_CN.UTF-8"
       LC_MESSAGES="zh_CN.UTF-8"
       LC_PAPER="zh_CN.UTF-8"
       LC_NAME="zh_CN.UTF-8"
       LC_ADDRESS="zh_CN.UTF-8"
       LC_TELEPHONE="zh_CN.UTF-8"
       LC_MEASUREMENT="zh_CN.UTF-8"
       LC_IDENTIFICATION="zh_CN.UTF-8"
       LC_ALL=
   ```
2.  目录：
   1.  主目录：
      
      ```
      /home/dennis
      ```
   2.  `${XDG_CONFIG_HOME}`:
      
      环境变量 `XDG_CONFIG_HOME` 没有设定。
      
      `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/dennis/.config`)。
   3.  Fcitx 设置目录：
      
      当前 fcitx 设置目录是 `~/.config/fcitx` (`/home/dennis/.config/fcitx`)。
3.  当前用户：
   
   脚本作为 dennis (1000) 运行。

# Fcitx 状态:
1.  可执行文件:
   
   在 `/bin/fcitx` 找到了 fcitx.
2.  版本:
   
   Fcitx 版本: `4.2.9`
3.  进程:
   
   找到了 2 个 fcitx 进程:
   
   ```
     4076 fcitx
     4095 fcitx-dbus-watc
   ```
4.  `fcitx-remote`:
   
   `fcitx-remote` 工作正常.

# Fcitx 配置界面:
1.  配置工具封装：
   
   在 `/bin/fcitx-configtool` 找到了 fcitx-configtool。
2.  用于 GTK+-2.0 的配置界面：
   
   在 `/bin/fcitx-config-gtk` 找到了 `fcitx-config-gtk`。
3.  用于 GTK+-3.0 的配置界面：
   
   在 `/bin/fcitx-config-gtk3` 找到了 `fcitx-config-gtk3`。
4.  KDE 的配置界面：

# 前端设置:

## Xim:
1.  `${XMODIFIERS}`:
   
   环境变量 XMODIFIERS 已经正确地设为了 "@im=fcitx".
   从环境变量中获取的 Xim 服务名称为 fcitx.
2.  根窗口上的 XIM_SERVERS:
   
   Xim 服务的名称与环境变量中设置的相同.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:
   
   **环境变量 QT_IM_MODULE 的值被设为了 "xim" 而不是 "fcitx". 请检查您是否在某个初始化文件中错误的设置了它的值.**
   **您正在 qt4 程序中使用 xim.**
   
   **您可以在 [Linux 输入法支持耻辱堂](http://fcitx-im.org/wiki/Hall_of_Shame_for_Linux_IME_Support) 找到一些会在使用 xim 时出现问题的应用程序. 包括应用程序卡死在内的更多使用 xim 可能出现的普遍问题请参见 [这里](http://fcitx-im.org/wiki/XIM/zh-cn).**
   
   **请使用您发行版提供的工具将环境变量 QT_IM_MODULE 设为 "fcitx" 或者将 `export QT_IM_MODULE=fcitx` 添加到您的 `~/.xprofile` 中. 参见 [输入法相关的环境变量: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#QT_IM_MODULE).**
2.  qt5 - `${QT_IM_MODULE}`:
   
   **环境变量 QT_IM_MODULE 的值被设为了 "xim" 而不是 "fcitx". 请检查您是否在某个初始化文件中错误的设置了它的值.**
   **您正在 qt5 程序中使用 xim.**
   
   **您可以在 [Linux 输入法支持耻辱堂](http://fcitx-im.org/wiki/Hall_of_Shame_for_Linux_IME_Support) 找到一些会在使用 xim 时出现问题的应用程序. 包括应用程序卡死在内的更多使用 xim 可能出现的普遍问题请参见 [这里](http://fcitx-im.org/wiki/XIM/zh-cn).**
   
   **请使用您发行版提供的工具将环境变量 QT_IM_MODULE 设为 "fcitx" 或者将 `export QT_IM_MODULE=fcitx` 添加到您的 `~/.xprofile` 中. 参见 [输入法相关的环境变量: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#QT_IM_MODULE).**
3.  Qt 输入法模块文件:
   找到了 Qt5 的输入法模块: `/lib64/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
   找到了 fcitx 的 qt 模块: `/lib64/fcitx/qt/libfcitx-quickphrase-editor.so`.
   **无法找到 Qt4 的 fcitx 输入法模块.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:
   
   环境变量 GTK_IM_MODULE 已经正确地设为了 "fcitx".
2.  `gtk-query-immodules`:
   1.  gtk 2:
      
      在 `/bin/gtk-query-immodules-2.0-64` 找到了 gtk `2.24.28` 的 `gtk-query-immodules`.
      版本行:
      
      ```
      # Created by /bin/gtk-query-immodules-2.0-64 from gtk+-2.24.28
      ```
      
      已找到 gtk `2.24.28` 的 fcitx 输入法模块.
      
      ```
      "/usr/lib64/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
      "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 
      ```
   2.  gtk 3:
      
      在 `/bin/gtk-query-immodules-3.0-64` 找到了 gtk `3.16.7` 的 `gtk-query-immodules`.
      版本行:
      
      ```
      # Created by /bin/gtk-query-immodules-3.0-64 from gtk+-3.16.7
      ```
      
      已找到 gtk `3.16.7` 的 fcitx 输入法模块.
      
      ```
      "/usr/lib64/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
      "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 
      ```
3.  Gtk 输入法模块缓存:
   1.  gtk 2:
      
      在 `/lib64/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.28` 的输入法模块缓存.
      版本行:
      
      ```
      # Created by /usr/bin/gtk-query-immodules-2.0-64 from gtk+-2.24.28
      ```
      
      已找到 gtk `2.24.28` 的 fcitx 输入法模块.
      
      ```
      "/usr/lib64/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
      "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 
      ```
   2.  gtk 3:
      
      在 `/lib64/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.16.7` 的输入法模块缓存.
      版本行:
      
      ```
      # Created by /usr/bin/gtk-query-immodules-3.0-64 from gtk+-3.16.7
      ```
      
      已找到 gtk `3.16.7` 的 fcitx 输入法模块.
      
      ```
      "/usr/lib64/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
      "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 
      ```
4.  Gtk 输入法模块文件:
   1.  gtk 2:
      
      找到的全部 Gtk 2 输入法模块文件均存在.
   2.  gtk 3:
      
      找到的全部 Gtk 3 输入法模块文件均存在.

# 配置:

## Fcitx 插件:
1.  插件配置文件目录:
   
   找到了 fcitx 插件配置目录: `/usr/share/fcitx/addon`.
2.  插件列表:
   1.  找到了 28 个已启用的插件:
      
      ```
      fcitx-autoeng
      fcitx-autoeng-ng
      fcitx-chttrans
      fcitx-classic-ui
      fcitx-clipboard
      fcitx-dbus
      fcitx-freedesktop-notify
      fcitx-fullwidth-char
      fcitx-fullwidth-char-enhance
      fcitx-imselector
      fcitx-ipc
      fcitx-keyboard
      fcitx-kimpanel-ui
      fcitx-lua
      fcitx-notificationitem
      fcitx-punc
      fcitx-punc-ng
      fcitx-quickphrase
      fcitx-remote
      fcitx-sogoucloudpinyin
      fcitx-sogoupinyin
      fcitx-spell
      fcitx-unicode
      fcitx-vk
      fcitx-x11
      fcitx-xim
      fcitx-xkb
      fcitx-xkbdbus
      ```
   2.  找到了 0 个被禁用的插件:
3.  插件库: 
   
   所有插件所需的库都被找到。
4.  用户界面:
   
   找到了 2 个已启用的用户界面插件:
   
   ```
   fcitx-classic-ui
   fcitx-kimpanel-ui
   ```
   
   Kimpanel 进程:
   
   ```
     4519 sogou-qimpanel
   ```

## 输入法:
1.  找到了 5 个启用的输入法:
   
   ```
   fcitx-keyboard-us
   sogoupinyin
   pinyin
   wubi
   wbpy
   ```
2.  默认输入法:
   
   您已经正确的将一个键盘输入法 "fcitx-keyboard-us" 设为默认.

# 日志:
1.  `date`:
   
   ```
   2015年 10月 19日 星期一 09:06:35 CST
   ```
2.  `~/.config/fcitx/log/`:
   
   ```
   总用量 0
   ```
3.  `~/.config/fcitx/log/crash.log`:
   
   `~/.config/fcitx/log/crash.log` 未找到.

**Comment by lookforit** [comment]
已解决，最终是在　**/etc/profile** 中加入：

``` shell
export XIM_PROGRAM=fcitx

export XIM=fcitx

export GTK_IM_MODULE=fcitx

export QT_IM_MODULE=fcitx

export XMODIFIERS="@im=fcitx"
```

可以在上述软件中正常输入中文了。
感谢楼上２位

**Comment by 1dot75cm** [comment]
fcitx-qt4 也装一下， 由 `/etc/X11/xinit/xinput.d/fcitx.conf` 设置这些环境变量。当然自己设置也没问题啦 : )

**Comment by 1dot75cm** [comment]
已更新 sogoupinyin-2.0.0.0068-1.fc23.x86_64，现在有问题吗？ @lookforit

**Comment by 1dot75cm** [comment]
Thanks report, See #49

**Comment by sztsian** [comment]
I guess this problem is fixed. If so, please kindly close this ticket.

**Comment by Endle** [comment]
> I guess this problem is fixed. If so, please kindly close this ticket.

你有权限吗？你或者 @1dot75cm 关掉它？

**Comment by sztsian** [comment]
Close this as no future issue reported.

**Comment by ghost** [comment]
我和你的境遇竟然一模一样

**Comment by ghost** [comment]
不过，我装了fcitx-qt5就好了，一切都ok了

**Comment by Cznorth** [comment]
sudo pacman -S kcm-fcitx   #楼上说的可能只适用于plasma5，安装kcm-fcitx可以根据当前环境直接解决依赖fcitx-qt5或者别的
