### ISSUE TITLE
Fedora 29 Mass Rebuild

### ISSUE THREAD

**Issue by dengbangjie** [FZUG/repo#330]
RT。
Fedora 29 beta 已发布。并顺便检查仓库中程序包是否有新版本 (可以使用python3-nvchecker)。

**Comment by sztsian** [comment]
感谢。 Fedora 29 Beta massive rebuild 已经编译好了。我回家后就发出来。

**Comment by dengbangjie** [comment]
Thank you!

**Comment by sztsian** [comment]
Fedora 29 Beta 已经上传，将在 TUNA 服务器的下一个同步周期发布在下面地址 
https://mirrors.tuna.tsinghua.edu.cn/fzug/free/29/x86_64/

**Comment by alick** [comment]
已经看得到了。要不要发个blog/SNS通告？

**Comment by sztsian** [comment]
可以发个 SNS 求测试。blog 和 邮件列表就算了

**Comment by alick** [comment]
发推了：https://twitter.com/FZUG/status/1050583219362500608

**Comment by sztsian** [comment]
在 GA 之后还要做一次 massive rebuild 的，我一般那时候才关 issue。

**Comment by Eric8069** [comment]
什么时候更新fedora 29的软件源啊？

**Comment by sztsian** [comment]
> 什么时候更新fedora 29的软件源啊？

已经发布在如下地址了
 https://mirrors.tuna.tsinghua.edu.cn/fzug/free/29/x86_64/
如果在你的设置里不能用，请参考这个 ticket 进行调试 https://github.com/FZUG/repo/issues/334

**Comment by sztsian** [comment]
I pushed an update to the packages. The repo will be updated within 24 hours.

**Comment by hooklab** [comment]
> > 什么时候更新fedora 29的软件源啊？
> 
> 已经发布在如下地址了
> https://mirrors.tuna.tsinghua.edu.cn/fzug/free/29/x86_64/
> 如果在你的设置里不能用，请参考这个 ticket 进行调试 #334

请加入为知笔记的包啊　wiznote

**Comment by sztsian** [comment]
请不要在该任务单下面回复无关内容。无关内容不会得到有效指派。
