### ISSUE TITLE
Fc29: wechat (electron-wechat) 缺少依赖。

### ISSUE THREAD

**Issue by dengbangjie** [FZUG/repo#331]
RT。
```
nothing provides electron needed by wechat-1.4.0-1.gitc0c4667.fc29.x86_64
```
我没有javascript的背景，但我建议是否可以考虑将wechat和electron一并安装至 /opt/wechat。 避免拆包带来的麻烦。
谢谢。

**Comment by sztsian** [comment]
是因为 electron 编译失败引起的。 https://github.com/FZUG/repo/issues/341

**Comment by sztsian** [comment]
临时解决方案已经推送。一天内应该会同步完成。

electron-3.0.10-1.prebuilt.fc29.x86_64.rpm

**Comment by dengbangjie** [comment]
thank you.
