### ISSUE TITLE
Atom package has broken Exec line in .desktop file

### ISSUE THREAD

**Issue by audreytoskin** [FZUG/repo#335]
The Atom package from the mosquito/atom Copr has left placeholders in the "Exec" line in the .desktop file, so you can't launch Atom from the system apps menu.

```
Exec=<%= installDir %>/bin/<%= appFileName %> %F
```

As far as I can tell, the only work around is to run the `atom` command instead.

Testing with Atom 1.33.0-1 on Fedora 29 Workstation x86_64.

**Comment by 1dot75cm** [comment]
Thank you. Package is building.
BTW, The vscode package was available in the mosquito/vscode Copr repository.

https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/835528/
