### ISSUE TITLE
unknown public key

### ISSUE THREAD

**Issue by andreicristianpetcu** [FZUG/repo#34]
Hi, 

I am trying to install jmeter with yaourt `yaourt -S jmeter` but I get this error:

``` bash
[100%] [..................................................] [   1.3KB/s][00:00]

Downloaded 819 bytes in 0 seconds. (1.33 KB/s)
==> Validating source files with sha256sums...
    apache-jmeter-2.13.tgz ... Passed
    apache-jmeter-2.13.tgz.asc ... Skipped
==> Verifying source file signatures with gpg...
    apache-jmeter-2.13.tgz ... FAILED (unknown public key AC214CAA0612B399)
==> ERROR: One or more PGP signatures could not be verified!
==> ERROR: Makepkg was unable to build jmeter.
==> Restart building jmeter ? [y/N]
```

Do I need to manually import each key or is there a simpler way?

Thank you!

**Comment by 1dot75cm** [comment]
Hi, The archwiki provide solution for this problem, please try it.
https://wiki.archlinux.org/index.php/Makepkg_#Signature_checking

```
$ gpg --recv-keys AC214CAA0612B399
```

Yes, jmeter work fine.

```
$ yaourt-link -s jmeter
 link to: /opt/jmeter/
Operating finish: local/jmeter 2.13-1
$ youart -Q
local/jmeter 2.13-1
$ /opt/jmeter/bin/jmeter.sh
```

**Comment by andreicristianpetcu** [comment]
It worked, thank you!

**Comment by andreicristianpetcu** [comment]
I also linked archlinux-keyring so I will not need any pkg checking.

``` bash
$cat /etc/pacman.conf
...
 [core]
#SigLevel = Optional TrustAll
SigLevel = Optional TrustedOnly
...
```

``` bash
$yaourt-link -s archlinux-keyring
$sudo pacman-key --init
$sudo pacman-key --populate
....
...
==> Updating trust database...
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   5  signed:  64  trust: 0-, 0q, 0n, 5m, 0f, 0u
gpg: depth: 2  valid:  64  signed:   6  trust: 64-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2016-01-22
```

Should this be added to the documentation? I will clean it up, test it again on a new Fedora 23 in a VM and send a patch with the documentation instructions. I will do this only if you think it is worth it. This seems the secure way of doing things and is less complicated than fetching each gpg key by hand.

**Comment by alick** [comment]
@andreicristianpetcu Sorry for not following up... You suggestion seems great. Please send a patch if you can. Thanks!
