### ISSUE TITLE
electron fail to build on f29

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#341]
See build log https://paste.fedoraproject.org/paste/ekCY85yyMTSaIuLm8c3A~Q

**Comment by IantheChan** [comment]
PASTE NOT FOUND...可以重新发下吗

**Comment by sztsian** [comment]
那是个出错信息。Fedora 30 massive rebuild 的时候我删了我这儿存的错误信息了。。。

**Comment by sztsian** [comment]
Fedora 29 end of life. Closing.
