### ISSUE TITLE
Fedora 29:同步仓库 'fzug-nonfree' 缓存失败，忽略这个 repo。

### ISSUE THREAD

**Issue by a523** [FZUG/repo#342]
同步仓库 'fzug-nonfree' 缓存失败，忽略这个 repo。
上次元数据过期检查：0:07:56 前，执行于 2019年01月07日 星期一 12时15分53秒。
fzug-release-29-0.1.noarch.rpm                     5.6 kB/s | 7.2 kB     00:01    
软件包 fzug-release-29-0.1.noarch 已安装。

```
[xin@xin-thinkpad yum.repos.d]$ cat /etc/yum.repos.d/fzug-nonfree.repo 
[fzug-nonfree]
name=FZUG fc$releasever - Nonfree
baseurl=https://mirrors.tuna.tsinghua.edu.cn/fzug/nonfree/$releasever/$basearch/
skip_if_unavailable=True
metadata_expire=7d
gpgcheck=0
enabled=1

[fzug-nonfree-source]
name=FZUG fc$releasever - Nonfree - Source
baseurl=https://mirrors.tuna.tsinghua.edu.cn/fzug/nonfree/$releasever/source/SRPMS/
skip_if_unavailable=True
metadata_expire=7d
gpgcheck=0
enabled=0
```

**Comment by sztsian** [comment]
hi，
这是预期的。现在 fzug-nonfree 是空的。
该警告不会影响使用。

**Comment by a523** [comment]
> hi，
> 这是预期的。现在 fzug-nonfree 是空的。
> 该警告不会影响使用。

可是我想在Fedora 29 安装sougoupinyin ，可以么?

**Comment by sztsian** [comment]
因为搜狗拼音使用了不开源的组件，并且一些用户报告其频繁卡死等问题。与搜狗拼音 Linux 版某开发者联系后，我们决定不再继续打包搜狗拼音。

**Comment by 1dot75cm** [comment]
前天更新的 2.2.0.0108 @sztsian
