### ISSUE TITLE
建议加入CheckInstall 的rpm

### ISSUE THREAD

**Issue by lookforit** [FZUG/repo#35]
以前用deb系的时候必备的打包工具。
貌似此工具在rpm 上不甚流行，甚至都没有完美的rpm包。
谢谢。

**Comment by 1dot75cm** [comment]
嗯， 好工具， 准备收录。

**Comment by cicku** [comment]
...为啥有人喜欢用，甚是不解，RPM 系的真的没人用这个...

**Comment by 1dot75cm** [comment]
嗯，确实主要还是使用 rpmbuild。

**Comment by 1dot75cm** [comment]
此工具需要更多测试，请谨慎使用。

**Comment by lookforit** [comment]
从该工具的项目主页看，已经停止了更新，而且官方源码编译有错误。

存在一个简单好用、持续更新的打包工具吗？

在 2015/10/23 4:11, 1dot75cm 写道:

**Comment by cicku** [comment]
没有任何打包工具是可靠的。
