### ISSUE TITLE
fcitx-rime 被标记为过时，且 f29 的源下无法安装这个包。

### ISSUE THREAD

**Issue by jixunmoe** [FZUG/repo#357]
3cd806c49101b58a7e99b30f6b14331e60dfb120 将 `fcitx-rime` 标记为过时的项目，然而官方源并没有提供这个包。而 f29 的源也不包含这个包，无法正常安装。

使用的 f29 源：https://mirrors.tuna.tsinghua.edu.cn/fzug/free/29/x86_64/

**Comment by sztsian** [comment]
@cheese 请问在 Fedora 官方源里有 rime 支持么？

**Comment by cheese** [comment]
没有，还没人提交 fcitx-rime 到官方源

**Comment by jixunmoe** [comment]
我把这个 repo 里的内容改了改，然后用 gitlab pages （有 CI 做自动构建）做了个 `fcitx-rime` 的源（fc29/30）：

```
# 启用 fcitx-rime 第三方源
sudo dnf install https://fcitx-rime-fedora-jixun.gitlab.io/fcitx-rime-fc$(rpm -E %fedora)/RPMS/noarch/fcitx-rime-jixun-release-$(rpm -E %fedora)-0.1.noarch.rpm

# 安装中州韵
sudo dnf install fcitx-rime
```

不过包没有 x86 的版本就是了…

相关仓库在 https://gitlab.com/fcitx-rime-fedora-jixun 这里
