### ISSUE TITLE
请问 Fedora 31 如何添加 FZUG 源？

### ISSUE THREAD

**Issue by XhstormR** [FZUG/repo#368]
[Wiki](https://github.com/FZUG/repo/wiki/%E6%B7%BB%E5%8A%A0-FZUG-%E6%BA%90) 里并没有针对 Fedora 31 的操作，并且 fzug-release-29-0.1.noarch.rpm 也没有了。

**Comment by sztsian** [comment]
hmm 我都注意 Fedora 31 的 fzug-release 没推送。你暂时用这个吧

`dnf install https://mirrors.tuna.tsinghua.edu.cn/fzug/free/30/x86_64/fzug-release-30-0.1.noarch.rpm`

虽然版本叫 30, 但是在 31 的系统上是能够正确选择 Fedora 31 的仓库的。

**Comment by XhstormR** [comment]
Ok

**Comment by alick** [comment]
感谢 @sztsian , 我根据你的评论更新了下Wiki页
