### ISSUE TITLE
fedora32 massive rebuild

### ISSUE THREAD

**Issue by Lavaong** [FZUG/repo#369]
我成功安装了fzug 30的源，但是显示软件列表的时候发生错误，因为没有fefora32 软件包的元数据文件

**Comment by sztsian** [comment]
还没来得及做 Fedora 32 的编译。

**Comment by Lavaong** [comment]
好的👌🏻



---Original---

**Comment by sztsian** [comment]
已经上传。 24 小时之内会自动发布出来。

**Comment by Lavaong** [comment]
thank you



---Original---
