### ISSUE TITLE
清理具有重分发授权问题的软件包

### ISSUE THREAD

**Issue by shankerwangmiao** [FZUG/repo#374]
建议核查软件源中软件是否符合 [打包指南](https://github.com/FZUG/repo/wiki/中文社区打包分类指南)中关于重分发授权的指引。可能存在问题的软件包括：

* [ ] wechat
* [ ] doubanfm
* [ ] youdao-dict

**Comment by sztsian** [comment]
感谢。
与 @shankerwangmiao 进行了简单沟通，确认 FZUG 需要移除具有分发限制的软件包，从而符合 tuna 镜像规定。需要重新审查的包包括但不仅限于上述。
注：TUNA 现在是 FZUG 源的 tier0.

**Comment by sztsian** [comment]
youdao-dict 已移除。会在下次同步时生效。

wechat , doubanfm 是对开源项目的打包，并非官方二进制包二次分发。所以符合 FZUG license 规定。

暂时没有发现其他需要清理的包。
