### ISSUE TITLE
tengine logrotate use wrong pid path

### ISSUE THREAD

**Issue by frostynova** [FZUG/repo#38]
In CentOS 6, it is /var/run/tengine.pid not /run/tengine.pid

**Comment by alick** [comment]
I don't think this repo supports CentOS. (Only Fedora in mind).

Besides, the current release of CentOS is 7.

**Comment by 1dot75cm** [comment]
Thanks, report. Currently, only `nginx` / `tengine` / `openresty` support el5-el7.
The pid path will be fixed in later versions.
