### ISSUE TITLE
希望能有搜狗输入法的包

### ISSUE THREAD

**Issue by a772304419** [FZUG/repo#381]
希望能有搜狗输入法的包，Fedora 35默认的ibus中文输入法实在不怎么好用

**Comment by sztsian** [comment]
搜狗拼音输入法并没有完全开源。

数年之前我们曾经对其二进制进行二次打包，但频繁有用户报告使用问题。在与搜狗拼音一位开发者进行沟通之后，开发者建议我们让用户换用其他输入法。故我们不再提供搜狗拼音的二进制重打包文件了。

https://github.com/FZUG/repo/issues/295#issuecomment-370379049
