### ISSUE TITLE
xware-desktop 缺少依赖项

### ISSUE THREAD

**Issue by jimmy9065** [FZUG/repo#41]
qt5-webkit需要引用qt5-sensors
安装包并没有加入这个依赖项，需要手动安装

**Comment by 1dot75cm** [comment]
感谢提醒， 由于 qt5-qtwebkit 依赖 qt5-qtsensors ，而 xware-desktop 又依赖 qt5-qtwebkit，所以 qt5-qtsensors 可以被安装。

```
$ rpm -q --requires xware-desktop
qt5-qtwebkit >= 5.2
$ rpm -q --requires qt5-qtwebkit
libQt5Sensors.so.5()(64bit)
$ rpm -q --provides qt5-qtsensors
libQt5Sensors.so.5()(64bit)
```

**Comment by sztsian** [comment]
Close this as I see there is already dependency for qt5-qtwebkit in the spec.

> Requires: qt5-qtwebkit >= 5.2
