### ISSUE TITLE
fedora23 xware-desktop下载到90%卡住

### ISSUE THREAD

**Issue by Ray93** [FZUG/repo#42]
![Uploading 2015-11-06 23-43-28屏幕截图.png…]()

**Comment by 1dot75cm** [comment]
现在下完了么？

**Comment by Ray93** [comment]
没有，卡在90%失败几次了，清理软件包重新安装还是一样

**Comment by alick** [comment]
楼主的问题是下载安装 xware-desktop 这个软件包时卡住，还是安装完成后使用这个软件时下载其他东西时卡住？

对于前者，我自己试了一下，下载安装软件包很正常。楼主遇到的可能是临时问题。

对于后者，我就不清楚了，但很可能与具体下载资源有关吧。

另外，楼主最开始试图发送的截图，我们看不到图片本身，只能看到如下一行字

```
[Uploading 2015-11-06 23-43-28屏幕截图.png…]()
```

总之，目测问题与打包关系不大，先关闭了。如有需要，可再次开启 (Reopen Issue)。
