### ISSUE TITLE
KDE5 ，搜狗拼音出不来候选词

### ISSUE THREAD

**Issue by lookforit** [FZUG/repo#43]
1、已安装 `Fcitx 4.2.9`
2、已安装 `sogoupinyin`
3、已安装 `Fcitx-qt4` `Fcitx-qt5`

`Fcitx-Dignose` 报告正常。 

现象：
任务栏可以看到搜狗的图标，但打字时候出不来正常情况下的搜狗输入法界面，只有一个简单的框框：
![fcitx](https://cloud.githubusercontent.com/assets/1892462/11087171/fdcb9c92-8892-11e5-9c48-b4aeb4f10834.png)

何解？

**Comment by lookforit** [comment]
亲测，是 `sogoupinyin-2.0.0.0066-2.fc23.x86_64` 带来的问题。
使用`sogoupinyin-2.0.0.0066-1.fc23.x86_64` 正常。

**Comment by 1dot75cm** [comment]
运行 sogou-qimpanel 就行了，它会开机启动的。

**Comment by 1dot75cm** [comment]
已更新 sogoupinyin-2.0.0.0068-1.fc23.x86_64，现在还有问题吗？ @lookforit

**Comment by sunznx** [comment]
我也遇到了 好像selinux 的问题  现在还有...

**Comment by 1dot75cm** [comment]
Thanks report, See #49 .

**Comment by sztsian** [comment]
请问问题解决了嘛？

**Comment by dc3671** [comment]
同问这个问题最终解决方案是什么... @1dot75cm 
似乎老版本多切换几次就自动好了，会出现候选词和皮肤
但是不知哪次更新之后就再也不出现了...需要再提供什么诊断信息吗？

另外请问运行`sogou-qimpanel`之后卡在下面界面正常吗...
![screenshot_20161123_101448](https://cloud.githubusercontent.com/assets/5948851/20549283/7955d504-b0f0-11e6-83ab-5d8244212c84.png)

**Comment by sztsian** [comment]
根据最新评论，该问题仍然发生，因此我将标题中的版本号去掉。

**Comment by dc3671** [comment]
找到解决办法了...
删除~/.config下的搜狗输入配置文件夹：SogouPY、SogouPY.users、sogou-qimpanel
重启输入法就可以了

**Comment by alick** [comment]
Close as fixed
