### ISSUE TITLE
bcloud在fedora 23下不能启动

### ISSUE THREAD

**Issue by kylinfedora** [FZUG/repo#44]
bcloud在fedora 23下不能启动

**Comment by jimmy9065** [comment]
可以启动，fedora23 KDE。。。

**Comment by 1dot75cm** [comment]
经测试，Gnome 上游已修正 bug。只要更新至最新版本，bcloud 即可正常使用。

相关软件版本：
- libgnome-keyring 3.12
- gtk3 3.18.6  更新～
- python3-crypto 2.6.1
- python3-dbus 1.2.0
- python3-gobject-base 3.18.2  更新～
- python3-inotify 0.9.6
- python3-keyring 5.0

See https://github.com/LiuLang/bcloud/issues/196
@kylinfedora  @jimmy9065
