### ISSUE TITLE
建议将 23 版本中加入 vim

### ISSUE THREAD

**Issue by lookforit** [FZUG/repo#47]
MS 23的repo中还没有.
当然,用最新的patch更好,省得自己动手了.

**Comment by 1dot75cm** [comment]
vim-X11-7.4.827-1.fc23.x86_64.rpm

官方的不是挺好的么？

**Comment by jimmy9065** [comment]
vim有的吧，再说命令行用vi就够了吧，真的需要可以用Gvim吧
