### ISSUE TITLE
Fedora23 无法安装Chrome浏览器

### ISSUE THREAD

**Issue by zgcao** [FZUG/repo#48]
按照wiki指导安装,但是出现问题,bash输出如下:
warning: /var/cache/dnf/google64-376e8cc1298accba/packages/google-chrome-stable-47.0.2526.73-1.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 7fac5991: NOKEY
Curl error (28): Timeout was reached for https://dl-ssl.google.com/linux/linux_signing_key.pub [Connection timed out after 120000 milliseconds]
The downloaded packages were saved in cache till the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.

**Comment by 1dot75cm** [comment]
将repo中的 `gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub`
改成`gpgkey=https://dl.google.com/linux/linux_signing_key.pub` 即可
