### ISSUE TITLE
无法显示中文候选词

### ISSUE THREAD

**Issue by sunznx** [FZUG/repo#49]
运行 sudo journalctl -xe | grep sogou
AVC avc:  denied  { getattr } for  pid=2580 comm="abrt-hook-ccpp" path="/usr/bin/sogou-qimpanel" dev="dm-0" ino=141037 scontext=system_u:system_r:abrt_dump_oops_t:s0 tcontext=system_u:object_r:sogou_exec_t:s0 tclass=file permissive=0

版本: 2.0.0.0068  fedora 23

要手动执行一次 sogou-qimpanel 才可以输入

**Comment by 1dot75cm** [comment]
Gnome 3下测试无问题，安装后重启系统，即可正常使用。 KDE 应该也可以自动启动 sogou-qimpanel，其他桌面环境 需要自行设置启动 sogou-qimpanel。

```
$ imsettings-info  # 检查是否为 fcitx
$ imsettings-switch fcitx  # 如果未切换，手动切换一下
```

**Comment by 1dot75cm** [comment]
Plasma 环境测试正常，安装后重启系统，imsettings 将切换至 fcitx，且自动启动 fcitx-ui-sogou-qimpanel.desktop。如有问题，请回复。

**Comment by sunznx** [comment]
imsettings-info  没有显示 fcitx  但是已经用 imsetting-switch 切换了

**Comment by sunznx** [comment]
cp /usr/share/applications/fcitx-ui-sogou-qimpanel.desktop ~/.config/autostart 还是不行

**Comment by 1dot75cm** [comment]
事实上，安装包后重启就可以用了，我在测试环境未做任何更改。重启后，检查如下信息：

```
[User]$ imsettings-info
Xinput file: /etc/X11/xinit/xinput.d/fcitx.conf
GTK+ immodule: fcitx
Qt immodule: fcitx
XMODIFIERS: @im=fcitx
XIM server: /usr/bin/fcitx -D
Preferences: /usr/bin/fcitx-configtool 
Auxiliary:  
Short Description: FCITX
Long Description: 
Icon file: /usr/share/pixmaps/fcitx.png
Is system default: TRUE
Is user default: TRUE
Is XIM server: FALSE
[User]$ alternatives --display xinputrc
xinputrc - 状态为手工。
链接当前指向 /etc/X11/xinit/xinput.d/fcitx.conf
[User]$ ll /etc/xdg/autostart/fcitx-ui-sogou-qimpanel.desktop 
lrwxrwxrwx. 1 root root /etc/xdg/autostart/fcitx-ui-sogou-qimpanel.desktop -> /usr/share/applications/fcitx-ui-sogou-qimpanel.desktop
```

我怀疑是否单独安装 KDE 环境，由于缺少 GNOME3 的某个包，导致不能切换至 fcitx。

**Comment by sunznx** [comment]
我也是gnome3.. 难道我要重装一次....

**Comment by 1dot75cm** [comment]
如果你有时间可以装个 fc23 虚拟机，在虚拟机测试，以确定是环境问题还是包问题。

**Comment by sunznx** [comment]
今天在虚拟机试了一下， 还是那样 不能打字啊... 
![screenshot from 2015-12-22 12-15-56](https://cloud.githubusercontent.com/assets/8629792/11947713/d67228ea-a8a5-11e5-8ff7-0a7c5d19374e.png)

**Comment by 1dot75cm** [comment]
如果 imsetting-switch 切换失败，gdm 不会启动 fcitx 和 sogou-qimpanel。以下提供一个临时解决方案。 更完善的方案，有待进一步研究。

```
$ imsettings-switch none  切换为 none 此时不会加载 fcitx
$ vi ~/.profile   启动 X 时调用该文件
# fcitx variable
export XIM=fcitx
export XIM_PROGRAM=/usr/bin/fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
while(test ! -d /proc/`pidof sogou-qimpanel||echo None`); do
  fcitx; sogou-qimpanel &>/dev/null
  sleep 15
done &
```

附加资源： https://wiki.archlinux.org/index.php/Fcitx_%28%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%29

**Comment by 1dot75cm** [comment]
已更新 2.0.0.0068-2，麻烦测试一下。

**Comment by 1dot75cm** [comment]
已更新 2.0.0.0068-3，有时间帮忙测试一下。

这个 commit https://github.com/FZUG/repo/commit/6a4e91acf82ec266e5c625b5db89c51e4b7142e2 解决了以下问题。
- 修复 SELinux 导致 sogou-qimpanel-watchdog 无法启动 sogou-qimpanel 
- 修复 55-sogoupinyin.sh 脚本错误
- 为 sogou-diag 增加 rpm 相关脚本
- 添加 fcitx 环境变量配置，作为某些桌面环境不支持启动 /etc/xdg/autostart/sogou.desktop 的备选方案

现在，应该不需要手动启动 sogou-qimpanel 了。 

Wiki 有详细说明 https://github.com/FZUG/repo/wiki/Sogou-Pinyin-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
