### ISSUE TITLE
Legal Issue

### ISSUE THREAD

**Issue by tvvocold** [FZUG/repo#5]
@sztsian 
repo 的 index 背景图片可以换，FZUG 的私有软件，有的的确应该删掉，或者划到个人名下。

Chrome 这个，基于国情和广大群众需求[1] 建议保留。（除非谷歌发邮件要求删:)
@1dot75cm 

[1] http://www.zhihu.com/question/27528326

**Comment by Endle** [comment]
[**@tvvocold**](https://github.com/tvvocold) commented on [2015年5月26日 GMT+8下午8:21](https://github.com/FZUG/repo/issues/5#issue-80937857):

> @sztsian 
> repo 的 index 背景图片可以换，FZUG 的私有软件，有的的确应该删掉，或者划到个人名下。
> 
> Chrome 这个，基于国情和广大群众需求[1] 建议保留。（除非谷歌发邮件要求删:)
> @1dot75cm 
> 
> [1] http://www.zhihu.com/question/27528326

chromium 不行吗？

我查看了一下 https://www.google.com/intl/zh-CN/chrome/browser/privacy/eula_text.html
貌似谷歌对 Chrome 的要求不是很严格，但绑定的 Adobe 模块是个很大的问题。

**Comment by tvvocold** [comment]
@Endle
Chrome 满足了大众的日常，更为稳定与安全且需求大；Chromuim 更适合开发者。

**Comment by tvvocold** [comment]
```
12. 终止您与 Google 的关系

12.1 除非您或 Google 依据下述条款终止本条款，否则本条款将持续有效。

12.2 出现下列情况时，Google 可随时终止与您达成的法律协议：

(A) 您违反了本服务条款中的任何规定（或您的行为方式明显表明，您无意或无法遵循本服务条款中的相关规定）；或

(B) 法律要求 Google 终止与您签署的法律协议（例如，向您提供的相关服务不合法或不再合法）；或

(C) 与 Google 合作向您提供服务的合作伙伴终止了与 Google 的合作关系，或不再向您提供服务；或

(D) Google 不再向您所在的国家/地区，或您使用相关服务时所在的国家/地区提供相关服务；或

(E) Google 认为向您提供相关服务在商业上已不再可行。
```

很明显谷歌已经终止对大陆提供服务了。TOC无效。
Adobe 的问题也不归搬运工吧。

**Comment by sztsian** [comment]
> 很明显谷歌已经终止对大陆提供服务了。TOC无效。

我不赞同。
谷歌还在中国经营业务。Google Map，广告等还是正常使用的。而且根据查询到的信息，谷歌的ICP证在2013年还办理过，且未处于失效状态，说明其在中国大陆仍然存在公司实体。

**Comment by tvvocold** [comment]
那这些 Chrome 提供站点呢? 
https://www.baidu.com/s?wd=chrome
Chrome 的讨论可以关闭了，我正在联系谷歌，如果他们不同意就下架。

**Comment by sztsian** [comment]
> 那这些 Chrome 提供站点呢?

其他站点的法律问题与我们无关。

> Chrome 的讨论可以关闭了，我正在联系谷歌，如果他们不同意就下架。

根据Google Chrome的[EULA](https://www.google.com/intl/en/chrome/browser/privacy/eula_text.html), [Chrome不是开源自由软件](http://en.wikipedia.org/wiki/Google_Chrome#cite_note-12)，如果参考我们此前制定的打包指南，它适用于第5条“不开源或不真正开源，没有法律问题，可以自由分发、免费使用（免费软件，非开源软件）。”，我们最后的结论是“符合5情形的软件，除非该软件的版权人**主动**提出打包要求，并出具书面打包及分发许可，否则不应当在中文社区 Copr 进行打包。书面许可需要允许公开并进行公开“。 Opera同样，也不是自由与开源软件。 
如果抛开社区而言，从我个人的角度，你也提到了有其他的站点在分发Chrome，那我们再分发一次也没太大必要了呗。
对于其他的问题，我的concern仅仅是，需要大家approve。

**Comment by 1dot75cm** [comment]
> 我们最后的结论是“符合5情形的软件，除非该软件的版权人主动提出打包要求，并出具书面打包及分发许可，否则不应当在中文社区 Copr 进行打包。书面许可需要允许公开并进行公开“。

关于符合第五条的软件，"除非该软件的版权人**主动**提出打包要求"。这点在实际操作中，“上游”永远不会主动提出打包要求。应改为如果社区用户有使用需求，则向版权人发出打包分发许可，如果版权人同意，则进行打包并托管包。

另外，作为社区软件源，应当仿照 rpmfusion 将不开源的软件统一放在 nonfree 源，这样也不影响 free 源的纯洁性。（nonfree源的软件都应当取得版权人的许可）

**Comment by alick** [comment]
google chrome 目前不应该放在 fzug copr repo 名下。

**Comment by alick** [comment]
@1dot75cm 打包规范文本修改的话，单开issue吧。

**Comment by tvvocold** [comment]
那就新建一个二级域名 mirrors.fdzh.org  ?

**Comment by alick** [comment]
2015-06-02 19:46 GMT+08:00 Ray notifications@github.com:

> 那就新建一个二级域名 mirrors.fdzh.org ?
> 
> 你可以这样做。注意不要让它看起来和 fzug 有关联。

**Comment by sztsian** [comment]
@tvvocold  @1dot75cm 我看到源里有Opera.而我并没有找到它的license信息。我可以确认Opera不是开源的。Opera是否允许二次分发？
有道词典看起来似乎是闭源但允许分发？

我建议把这些与第5条相悖的也转移到“No Free”之类地方去吧

**Comment by 1dot75cm** [comment]
好的，我先标记一下，尽快处理。@sztsian

**Comment by 1dot75cm** [comment]
已分为 free 和 nonfree 源，修复此问题？

**Comment by alick** [comment]
我认为应遵循[维基上的约定](https://github.com/FZUG/Copr/wiki/%E4%B8%AD%E6%96%87%E7%A4%BE%E5%8C%BA-Copr-%E6%89%93%E5%8C%85%E5%88%86%E7%B1%BB%E6%8C%87%E5%8D%97)。这样 nonfree 里面也不能有分发限制的软件。请 @1dot75cm 确认一下 nonfree 里没有类似软件。

**Comment by cicku** [comment]
+1 for @alick

**Comment by alick** [comment]
@1dot75cm 关闭？

**Comment by sztsian** [comment]
我觉得当前现状暂时没有问题。所以关闭这个issue。
如果有其他法务问题，可以reopen。

**Comment by sztsian** [comment]
Robert Lu, [29.10.17 01:27]
http://www.newsmth.net/nForum/#!article/LinuxApp/934578

Robin Lee, [29.10.17 01:48]
这就有问题了

Alick Zhao, [29.10.17 04:15]
需要联系 zamirsun 和 mosquito 处理下
Robert Lu, [29.10.17 01:27]
http://www.newsmth.net/nForum/#!article/LinuxApp/934578

teleboto, [29.10.17 01:27]
[BadGirl] [2012-05-01 12:39:14] Posted by c/fy@ubuntu-cn already: 水木社区-源于清华的高知社群

Robin Lee, [29.10.17 01:48]
这就有问题了

Alick Zhao, [29.10.17 04:15]
[In reply to Robert Lu]
需要联系 @zamirsun 和 mosquito 处理下

Robin Lee, [29.10.17 15:09]
主要是 license 问题，要能放跟 rpmfusion 同样级别的东西

**Comment by alick** [comment]
算是解决了吧
