### ISSUE TITLE
安装chrome失败.

### ISSUE THREAD

**Issue by jason20140612** [FZUG/repo#51]
Error: Failed to synchronize cache for repo 'updates' from 'https://mirrors.fedoraproject.org/metalink?repo=updates-released-f22&arch=i386': Cannot prepare internal mirrorlist: Curl error (7): Couldn't connect to server for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f22&arch=i386 [Failed to connect to mirrors.fedoraproject.org port 443: Connection refused]

**Comment by alick** [comment]
这个错误应该只是暂时性的网络连接问题或者 metalink 服务器临时问题。和 chrome 无关。请稍后重试。
