### ISSUE TITLE
请求更新shadowsocks 的替代软件

### ISSUE THREAD

**Issue by sdc6882278** [FZUG/repo#52]
原生shadowsocks 开发者因种种原因放弃开发此软件，breakwa11开发了基于ss协议增强版本，更好的应对干扰，提升性能。https://github.com/breakwa11/shadowsocks

**Comment by cicku** [comment]
谁告诉你 shadowsocks 原版停止开发了?

**Comment by sdc6882278** [comment]
恳请告知 现在正在活跃开发的地址。

**Comment by cicku** [comment]
诶，原版的 master 分支下面还是有 activity 的。算吗？ :joy: 

真正的原版估计是没了。

**Comment by sdc6882278** [comment]
feature-ota 分支与master分支 现在处于bug维护阶段，不再添加新的特性 ota一次性验证还是从shadowsocks-libev 合并过去的，所以恳请加入breakwa11的版本。

**Comment by 1dot75cm** [comment]
有什么新特性么？我先看看
