### ISSUE TITLE
deepin-music-box 无法播放网易云音乐的歌曲

### ISSUE THREAD

**Issue by MichaelVipub** [FZUG/repo#54]
目前我能定位的就是deepin下的插件代码太老了。换用github的代码后就可以正常播放了。
具体的描述见：
https://github.com/wu-nerd/dmusic-plugin-NeteaseCloudMusic/issues/23

**Comment by 1dot75cm** [comment]
好的，谢谢汇报。已知晓，将在迁移 deepin 的过程中优先解决。

**Comment by Endle** [comment]
现在有了正式的网易云音乐，还有必要打包这个插件吗？

**Comment by alick** [comment]
如果一周内没有人对不再打包这个插件有异议，那就行动吧。

**Comment by 1dot75cm** [comment]
嗯嗯， 依然有必要，有部分人喜欢用第三方的，内存占用少，速度快。这个问题，我找一天集中把 deepin 的包更新一下。 @Endle

**Comment by sztsian** [comment]
As Fedora 23 is end of life. I am closing this bug. If this still happen on newer release of Fedora, please reopen and change the release number. 
Fedora 23 已经结束生命周期。现关闭该故障报告。如该该问题仍然存在于更新版本的 Fedora 上，请重新开启这个报告并修改版本号。

**Comment by 1dot75cm** [comment]
Deepin 的包互相依赖很多， 我在 Copr 上看到[另一个库](https://copr.fedorainfracloud.org/coprs/jstepanek/deepin-test/)，迁移了好多 Deepin 的包， 准备看看他的工作，再做调整。

**Comment by 1dot75cm** [comment]
已经迁移了完整的 Deepin Desktop Environment，截图在 #201 。Deepin-music 3.x现在用不了插件了，2.x 可以运行，你试试看可以解决这个问题吗？ @MichaelVipub

**Comment by sztsian** [comment]
超过一年没有跟进。关闭该问题。
