### ISSUE TITLE
fedora 23 deepin-movie无法启动

### ISSUE THREAD

**Issue by MichaelVipub** [FZUG/repo#55]
启动错误如下：
[michael@localhost ~]$ deepin-movie
ATTENTION: default value of option bo_reuse overridden by environment.
AudioResampler::Register(..., FFmpeg)
Singleton 0x7ff7a00bbc90 created...
AudioResampler::Register(..., Libav)
AudioOutputBackend::Register(..., OpenAL)
Singleton 0x7ff7a00bc120 created...
AudioOutputBackend::Register(..., Pulse)
VideoDecoder::Register(..., CUDA)
Singleton 0x7ff7a00bc2b0 created...
VideoDecoder::Register(..., VAAPI)
VideoRenderer::Register(..., OpenGLWindow)
Singleton 0x7ff7a00bc440 created...
SubtitleProcessor::Register(..., LibASS)
Singleton 0x7ff7a00bc5b0 created...
SubtitleProcessor::Register(..., FFmpeg)
AudioDecoder::Register(..., FFmpeg)
Singleton 0x7ff7a00bc820 created...
AudioEncoder::Register(..., FFmpeg)
Singleton 0x7ff7a00bc930 created...
ImageConverter::Register(..., FFmpeg)
Singleton 0x7ff7a00bca40 created...
MediaIO::Register(..., QIODevice)
Singleton 0x7ff7a00bd100 created...
MediaIO::Register(..., QFile)
AudioOutputBackend::Register(..., null)
VideoDecoder::Register(..., FFmpeg)
VideoEncoder::Register(..., FFmpeg)
Singleton 0x7ff7a00bd350 created...
VideoRenderer::Register(..., QQuickItem)
VideoRenderer::Register(..., QuickFBO)
AudioOutputBackend::next(0x7ff7a00a03b0)
AudioOutputBackend::next(0x7ff7a00a03b4)
AudioOutputBackend::next(0x7ff7a00a03b8)
AudioOutputBackend::id("Pulse")
SubtitleProcessor::id("LibASS")
SubtitleProcessor::id("FFmpeg")
段错误 (核心已转储)

**Comment by 1dot75cm** [comment]
Thanks, test. It's my fault.

**Comment by sztsian** [comment]
As Fedora 23 is end of life. I am closing this bug. If this still happen on newer release of Fedora, please reopen and change the title. 
Fedora 23 已经结束生命周期。现关闭该故障报告。如该该问题仍然存在于更新版本的 Fedora 上，请重新开启这个报告并修改版本号。

**Comment by 1dot75cm** [comment]
deepin-movie 已经可以运行了， 详见 [deepin_project](https://github.com/FZUG/repo/tree/master/rpms/deepin_project)  @MichaelVipub
