### ISSUE TITLE
cant start wine-qqintl

### ISSUE THREAD

**Issue by MichaelVipub** [FZUG/repo#56]
[michael@localhost ~]$ wine-qqintl 
wineserver: mkdir /tmp/.wine-1000: Permission denied

solution:
[michael@localhost ~]$ wine-qqintl 
wineserver: mkdir /tmp/.wine-1000: Permission denied
[michael@localhost ~]$ sudo mkdir /tmp/.wine-1000
[sudo] michael 的密码：
[michael@localhost ~]$ sudo chown michael.michael /tmp/.wine-1000
[michael@localhost ~]$ sudo chmod 700 /tmp/.wine-1000/
[michael@localhost ~]$

**Comment by 1dot75cm** [comment]
Thanks, test. I think it should be used `/var/tmp` directory instead of `/tmp` directory.
Because tmpfs is mounted to `/tmp`.

**Comment by 1dot75cm** [comment]
重启，清空 `/tmp` 目录就好了。下次把网络安装包的临时目录改到 `/var/tmp`。 Happy New Year～

**Comment by alick** [comment]
Better to follow the suggestion here:
http://0pointer.net/blog/projects/tmp.html

On Thu, Dec 31, 2015 at 11:09 AM, 1dot75cm notifications@github.com wrote:

> 重启，清空 /tmp 目录就好了。下次把网络安装包的临时目录改到 /var/tmp。 Happy New Year～
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FZUG/repo/issues/56#issuecomment-168223859.

## 

Regards,
Alick

**Comment by cicku** [comment]
我怎么记得 /var/tmp 和 /tmp 已经没有任何区别了（On Fedora） :question:

**Comment by Endle** [comment]
```
lizhenbo@localhost var$ ls /tmp
hsperfdata_lizhenbo
kde-lizhenbouZA0v7
mozilla_lizhenbo0
NutstoreTmp0xyz
systemd-private-f6f0f7fd360c45289d0c37b9f0411423-colord.service-TH8UOj
systemd-private-f6f0f7fd360c45289d0c37b9f0411423-rtkit-daemon.service-y0Noqt
tracker-extract-files.1000
lizhenbo@localhost var$ ls /var/tmp
abrt
dnf-lizhenbo-yvw1evzu
kdecache-lizhenbo
systemd-private-f6f0f7fd360c45289d0c37b9f0411423-colord.service-agLEjl
systemd-private-f6f0f7fd360c45289d0c37b9f0411423-rtkit-daemon.service-jEtOUL
lizhenbo@localhost var$ 
```

/var/tmp 和  / tmp 还是不一样的

**Comment by cicku** [comment]
目前看是系统级的应用都在 /tmp，应用级的都在 /var/tmp :grey_question:

**Comment by 1dot75cm** [comment]
临时的在 /tmp（个头小的，如 socket, 缓存等），持久的（个头较大）临时文件在 /var/tmp 。
/tmp 是 tmpfs 直接写入内存，/var/tmp 直接写入磁盘。

**Comment by 1dot75cm** [comment]
已更新，如果有问题请回复 @MichaelVipub

**Comment by alick** [comment]
默认问题已解决，关闭之。如果还有，请重新开启问题。
