### ISSUE TITLE
wps-office 镜像源问题

### ISSUE THREAD

**Issue by ghost** [FZUG/repo#59]
non-free repo里开始有wps-office了,size 显示408k,不知道什么包,不过看行为,是到链接去下载wps-office的RPM包了,终端一直停在Running transaction不动,会让人以为出问题了.wps-office进源当然是好事,不用总去查看wps是不是有更新了.FZUG可不可以考虑做一份wps的镜像,这样更新/安装的时候,就直接从repo里安装了,不会给人感觉transaction卡住了一样.这个镜像是需要金山授权吗?还是有带宽或者存储空间问题?

**Comment by alick** [comment]
镜像需要 WPS 允许分发。印象中是不行的。

2016-01-19 20:25 GMT-06:00 SeAL80s notifications@github.com:

> non-free repo里开始有wps-office了,size
> 显示408k,不知道什么包,不过看行为,是到链接去下载wps-office的RPM包了,终端一直停在Running
> transaction不动,会让人以为出问题了wps-office进源当然是好事,不用总去查看wps是不是有更新了FZUG可不可以考虑做一份wps的镜像,这样更新/安装的时候,就直接从repo里安装了,不会给人感觉transaction卡住了一样这个镜像是需要金山授权吗?还是有带宽或者存储空间问题?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FZUG/repo/issues/59.

## 

Regards,
Alick

**Comment by alick** [comment]
"终端一直停在Running transaction不动,会让人以为出问题了"会不会只是网速不好？

**Comment by sztsian** [comment]
@alick wps的分发限制似乎只是 [4. 通过合法方式在除北美以外的全球范围内分发本“软件”，但您同意在您分发本“软件”时必须同时遵守本款下述全部约定：
仅能按金山软件提供的本“软件”现状分发本“软件”，且分发的本“软件”仅能为金山软件提供的完整的（包括但不限于包含本《协议》全部内容）包含所有版权标识的未作任何修改的本“软件”； ](http://community.wps.cn/wiki/WPS_Office_Linux%E7%89%88%E6%9C%80%E7%BB%88%E7%94%A8%E6%88%B7%E5%8D%8F%E8%AE%AE)

但是，其中的方正字库有更严格约束[4.1您不得对本字库软件进行复制、修改、仿制、反编译、反汇编、反向工程、转换、翻译、拆分，或以其他方式试图从本软件取得源代码，或从本软件文档中摘取其实质部分作其他应用；](http://www.foundertype.com/index/license.html)

综上，我们完全不能够打包。

**Comment by alick** [comment]
@sztsian 你是指连下载安装的脚本都不能吗？我理解没有那个意思吧。“现状分发”是说不允许修改吧？

**Comment by 1dot75cm** [comment]
> 终端一直停在Running transaction不动,会让人以为出问题了

可通过 `ls /var/tmp/wps*` 查看下载进度。

> 其中的方正字库有更严格约束

方正字库协议中，对因使用字库而获益的商业行为，需要获取授权。

> > 2.2 “使用”是指安装、下载、复制、展览或以其他方式通过利用本字库软件的功能而获益的行为。
> > 如果您的使用需求超出了本协议的使用许可范围，尤其是，您出于商业目的为他人而复制、发行或者展览了本协议中的知识产权，请与我们联系以获取方正字库知识产权的相应授权。

我不知道，通过链接下载字体算不算侵权；如果有问题，会去掉下载链接。

> > 4.5 根据字库软件中字体的美术作品属性，如果您没有获得方正电子公司的明确的授权许可不得实施下述行为，包括但不限于：发表、署名、修改、复制、发行、出租、展览、放映、广播、信息网络传播、摄制、改编、翻译、汇编等。

**Comment by sztsian** [comment]
@alick 我理解的是，WPS我们可以制作下载安装脚本，（也许也可以直接打包。现在WPS官方提供的参考spec链接就是 @cheese fedorapeople中的文件。）。但是我认为WPS中的方正字库限制了“复制”“信息网络传播”，在我的理解中，这样我们就不能直接对WPS打包了。或者打包但不提供方正字库（似乎这样又违反了WPS的规定？）。因此我觉得唯一稳妥的办法也许是制作一个wps-installation脚本，但rpm中不包含wps应用。

**Comment by alick** [comment]
@1dot75cm 应该就是这样做的吧。

**Comment by 1dot75cm** [comment]
> 因此我觉得唯一稳妥的办法也许是制作一个wps-installation脚本，但rpm中不包含wps应用。

对，该 rpm 包相当于安装脚本，里面除了 shell 脚本外什么都没有。

**Comment by alick** [comment]
close

2016-01-21 16:35 GMT-06:00 1dot75cm notifications@github.com:

> 因此我觉得唯一稳妥的办法也许是制作一个wps-installation脚本，但rpm中不包含wps应用。
> 
> 对，该 rpm 包相当于安装脚本，里面除了 shell 脚本外什么都没有。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FZUG/repo/issues/59#issuecomment-173737361.

## 

Regards,
Alick
