### ISSUE TITLE
tragtor无法启动

### ISSUE THREAD

**Issue by ghost** [FZUG/repo#60]
/usr/bin/tragtor从命令行启动一点反应都没有...ps aux | grep tragtor也没有后台进程.安装也不报错,也没有依赖缺失.这到底是个什么鬼?

**Comment by alick** [comment]
报一下系统版本、安装软件包版本吧。

**Comment by 1dot75cm** [comment]
tragtor 是 Python 编写的 FFmpeg 音视频转换器。
启动不了，请提供一下系统版本，可能是缺少依赖。

**Comment by ghost** [comment]
Fedora 23 x86_64 xfce4.12 
系统装有python 2.7.10

**Comment by alick** [comment]
我刚在 Fedora 23 Workstation （即 GNOME 桌面环境）上试了一下， 命令行启动跳出了图形界面，看起来正常。

楼主的系统是新安装的，还是从 Fedora 旧版本上升级过来的？

**Comment by ghost** [comment]
不搞GNOME了，GNOME3/KDE5都裝過，之后都卸载了。连gtk3/kf5以及相关依赖都卸载了。可能tragtor有相关的gtk3依赖。不用了，ffmpeg命令行够用了，就算要批量转码，搭配shell脚本也够了。不折腾图形界面了

**Comment by 1dot75cm** [comment]
> traGtor is written completely in Python and uses GTK as toolkit.
>  It depends on ffmpeg/avlib and id3v2 and needs Python > 2.5 with pygtk-support

traGtor 需要 pygtk，一般的桌面环境应该装了，不行我把依赖补上。不过可能那就要装 gtk3 了：）

**Comment by sztsian** [comment]
Fedora 25 已经停止支持。该问题报告于 Fedora 25 之前的版本。故关闭该问题
