### ISSUE TITLE
fcitx 疑问

### ISSUE THREAD

**Issue by alick** [FZUG/repo#62]
今天更新发现 fcitx, fcitx-pinyin 等被升级到了中文社区源中的版本。而它们本来在 fedora 官方源里就有，为什么中文社区源又做了一份呢？莫非是搜狗输入法支持必须的？

另外，中文社区源里的 fcitx 安装时有警告没有 GPG 密钥签名，为什么不签呢？Copr 里应该可以签的。

**Comment by alick** [comment]
@1dot75cm

**Comment by 1dot75cm** [comment]
只是用 [checker](https://github.com/1dot75cm/repo-checker) 检查的时候，发现 fcitx 有更新，就打包了。搜狗 需要修改 OpenCC，fcitx 需要 4.2.8+。
关于 fcitx 的更新，还是应该通知 Packager :+1: (以后优先通知)。

由于之前的库被 Fedora Copr 删了，包也就一直没重新签名。这个会尽快补上。

**Comment by alick** [comment]
呃，关于这个 checker，我也是才知道。我们不是有 release monitoring 吗？是否重复功能了？还是说适用于非自由软件？既然是给 FZUG/repo 用的，转移到 FZUG 名下？

**Comment by alick** [comment]
fcitx 新版本 RHBZ BUG：https://bugzilla.redhat.com/show_bug.cgi?id=1293610

**Comment by cheese** [comment]
有什么特别要求？

**Comment by 1dot75cm** [comment]
> 我们不是有 release monitoring 吗？是否重复功能了？还是说适用于非自由软件？

我感觉 release monitoring 用着不方便，且速度慢；另外，版本检查的脚本不是很复杂，自己写各方面都好控制。

> 既然是给 FZUG/repo 用的，转移到 FZUG 名下？

我怕写的不好，出丑 :)

> fcitx 新版本 RHBZ BUG：https://bugzilla.redhat.com/show_bug.cgi?id=1293610

fcitx 还请 @cheese 更新。

**Comment by alick** [comment]
2016-01-25 1:34 GMT-06:00 1dot75cm notifications@github.com:

> 我们不是有 release monitoring 吗？是否重复功能了？还是说适用于非自由软件？
> 
> 我感觉 release monitoring 用着不方便，且速度慢；另外，版本检查的脚本不是很复杂，自己写各方面都好控制。
> 
> 明白了。那么不再用 release monitoring （删掉 README 中链接等），只用自家脚本？我的担心是用两套工具更让人疑惑不解给人误导。
> 
> 既然是给 FZUG/repo 用的，转移到 FZUG 名下？
> 
> 我怕写的不好，出丑 :)

ESR 说过， 更多眼睛让 BUG 无处可藏啊。(Give enough eyeballs, all bugs are shallow.)对吧？

> fcitx 新版本 RHBZ BUG：https://bugzilla.redhat.com/show_bug.cgi?id=1293610
> 
> fcitx 还请 @cheese https://github.com/cheese 更新。

**Comment by 1dot75cm** [comment]
> 那么不再用 release monitoring （删掉 README 中链接等），只用自家脚本？我的担心是用两套工具更让人疑惑不解给人误导。

误导应该不会吧，只是检查版本的工具。

> ESR 说过， 更多眼睛让 BUG 无处可藏啊。(Give enough eyeballs, all bugs are shallow.)对吧？

成，那我整理好了转到 FZUG下。

**Comment by alick** [comment]
2016-01-26 3:43 GMT-06:00 1dot75cm notifications@github.com:

> 那么不再用 release monitoring （删掉 README 中链接等），只用自家脚本？我的担心是用两套工具更让人疑惑不解给人误导。
> 
> 误导应该不会吧，只是检查版本的工具。

怎么说，已经成功误导我认为在用 release monitoring 监控版本更新了。

**Comment by 1dot75cm** [comment]
：） 我没有 fork 权限，不能把 checker fork 到 FZUG。 @alick

**Comment by alick** [comment]
我也没有。

@sztsian

**Comment by alick** [comment]
fcitx 新版本已经在 updates-testing 源，请帮忙测试兼容性等

**Comment by alick** [comment]
中文社区源里的 fcitx 是否不再需要可以删除了？

**Comment by alick** [comment]
关于 repo checker， @1dot75cm 你发邮件请求吧，夹杂在这个 issue 里没人注意到。发到列表，抄送 github fzug 管理员（cicku, zsun 等）

**Comment by 1dot75cm** [comment]
：）好的， 可以删除 fcitx。

checker 里面我后来又添加了 trans 翻译脚本， 这个库里面是否仅包含和 checker 有关的脚本， 其他示例脚本或小工具不能包含？

**Comment by alick** [comment]
我建议“名副其实”，一个项目就做它该做的事。翻译脚本和 repo checker 有什么关系？为何不给它独立的 repo？如果觉得没必要做成一个项目，那就搞成 gist。

后续有关 repo checker 讨论另开主题吧。

**Comment by 1dot75cm** [comment]
已删除 fcitx，可以关闭该问题了。

**Comment by alick** [comment]
fcitx-qt5 又是因为什么呢？

**Comment by 1dot75cm** [comment]
fcitx 和 fcitx-qt5 是最初适配 CentOS 7 时添加的。后来社区源不维护 CentOS 7 了，确实可以删除。

**Comment by alick** [comment]
是指中文社区源不支持 CentOS 7 了吧？要是 CentOS 7 发行版不维护了就是大新闻了。

**Comment by 1dot75cm** [comment]
对对，社区源不维护 CentOS 7，因为缺少的依赖太多，需要牵扯一些精力。

另外， @cheese 可否向 epel 提交 fcitx/fcitx-qt5 ，这会造福不少用户。 ^^~

**Comment by sztsian** [comment]
这个issue跑题的内容太多了吧！

@alick @1dot75cm 现在的状况是，默认只有owner可以创建repo（也就是说，我和cicku才能创建新repo）。其他权限似乎没有受到github权限框架升级的影响（实质是可以通过为team添加权限的方式达到与以前相同的效果）

**Comment by 1dot75cm** [comment]
确实跑偏了，整理如下 @sztsian
- [x] 删除社区源 fcitx, fcitx-qt5 等 (这俩已删除，还有其他 fcitx-\* 再看看要删哪些)
- [ ] RPM包 GPG 签名
- [x] fork repo-checker
- [x] 向 epel 提交 fcitx/fcitx-qt5

**Comment by sztsian** [comment]
> - [ ] 删除社区源 fcitx, fcitx-qt5 等 (这俩已删除，还有其他 fcitx-\* 再看看要删哪些)

我的看法是：如果官方源有这些包，立即删掉就好了。如果上游已经更新，Fedora官方源可以更新，那么你可以提醒一下相关maintainer（我随手点了几个，发现fcitx*的packager主要是liangsuilong和Cheese Lee，都是FZUG的成员）。
如果是官方没有的fcitx包，可以先保留在FZUG的源，符合官方guideline的尝试提交到官方源。

**Comment by 1dot75cm** [comment]
了解，稍后删除。 @sztsian

**Comment by cheese** [comment]
pwu 已向 epel7 提交 fcitx
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-22beba5915

**Comment by 1dot75cm** [comment]
Good job. @cheese

**Comment by Endle** [comment]
> 删除社区源 fcitx, fcitx-qt5 等 (这俩已删除，还有其他 fcitx-\* 再看看要删哪些)

现在已经被删掉了，`fcitx-qt5`是官方源提供的，是不是可以关闭issue了？

**Comment by 1dot75cm** [comment]
可以关闭了， 其他问题再开新 issue 讨论。 @Endle
