### ISSUE TITLE
多进程下载 避免单文件包下载过慢？

### ISSUE THREAD

**Issue by ak47sss** [FZUG/repo#63]
fedora小吧前来报道！
已安装fzug 源和chrome。已经能正常更新google-chrome  …… 开心中……
but
我在更新atom编程软件时发现atom下载过慢，经常只有几KB。
在网上找的其它多进程下载工具貌似没起什么作用，包括dnf自带的进程。
希望能把atom包加到FZUG源中。或跟chrome一样，单新建一个repo。
要不然下载atom.rpm真能急死。。。。。
谢谢了。哈。

**Comment by 1dot75cm** [comment]
:+1:  dl.google.com 不知咋的，前一段时间已经挂了。

atom 已经在 FZUG 源中， 或者使用 Copr 的 [mosquito/atom](https://copr.fedorainfracloud.org/coprs/mosquito/atom) 也可以(凌晨速度快)。

**Comment by 1dot75cm** [comment]
谷歌北京的 IP，DNS 被解析到美国了，这要是 Google Play 入华，得受到多大打压。
203.208.49.169 dl.google.com

**Comment by ak47sss** [comment]
确实发现快了。多谢。 其实google play入华，百度的反应应该最大。毕竟有爵位在身。上周D吧出征闹的挺凶，我看vpn 和SS 翻墙之类的软件应该会被清一批吧。。。。以后翻墙就不好用了。。。

**Comment by 1dot75cm** [comment]
已修复 chrome 更新脚本，现在 exe, dmg, rpm, deb 都正常了。

```
$ curl http://repo.fdzh.org/chrome/version.json
$ curl http://repo.fdzh.org/chrome/version.csv
```
