### ISSUE TITLE
Request for package: gmrender-resurrect

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#65]
gmrender-resurrect is used as a DLNA render. It works well on my Raspberry Pi and so I want to have it in my Fedora.
Here is a ready-to-use SPEC by the upstream.
https://github.com/hzeller/gmrender-resurrect/pull/72/files

**Comment by 1dot75cm** [comment]
Everything is looks fine. Thanks report.

**Comment by 1dot75cm** [comment]
Finished, building.

**Comment by 1dot75cm** [comment]
Please review https://github.com/FZUG/repo/commit/9e50eac5794581ffca4324108756cb5a6bded958 . Thanks @sztsian

**Comment by 1dot75cm** [comment]
已加入 FZUG， 有时间请测试一下

**Comment by sztsian** [comment]
Thanks.
Close as FIXED without test.
