### ISSUE TITLE
镜像网站国际化/本地化？

### ISSUE THREAD

**Issue by alick** [FZUG/repo#67]
要不要做国际化与本地化？现在的页面有点中英文混杂。

**Comment by Endle** [comment]
我的倾向是把四个F的阐释删掉，比如

> Freedom represents dedication to free software and content.

其他的内容也没什么吧

**Comment by alick** [comment]
有这一句话吗？我指的是 https://repo.fdzh.org/#

**Comment by Endle** [comment]
> 有这一句话吗？我指的是 https://repo.fdzh.org/#

抱歉，我误会了，以为你说的是 https://www.fdzh.org/

**Comment by alick** [comment]
@FZUG/repo Any ideas?

**Comment by ghost** [comment]
请问没有家里没有网路，可以把整个fedora fzhg打包进16gu盘吗？我只有一个16g u盘

**Comment by alick** [comment]
请勿在本主题下开启无关话题，有问题请开新 issue 发问。


Regards,
Alick

**Comment by alick** [comment]
ping @1dot75cm

**Comment by alick** [comment]
打算放弃国际化，只做中文页面
