### ISSUE TITLE
烦请把atom 编辑器添加到fzug源中。

### ISSUE THREAD

**Issue by ak47sss** [FZUG/repo#68]
fedora 23 使用dnf 下载atom编辑器速度太慢。已经启用helber-atom 源。
但下载速度经常20-30K.速度过慢。已经对dnf.conf配置过。不管用。
烦请把atom编辑器添加到fzug源中。。。
另外 google源很好用。赞。

**Comment by 1dot75cm** [comment]
atom 在源里，源中的版本从 https://copr.fedorainfracloud.org/coprs/mosquito/atom/ 拷贝。

目前，repo.fdzh.org 带宽资源有限。会尝试启用 CDN，缓存大文件。

**Comment by 1dot75cm** [comment]
已启用CDN，现在应该没问题了。

```
$ wget https://repo.fdzh.org/FZUG/free/23/x86_64/atom-1.4.3-1.git164201e.fc23.x86_64.rpm
atom-1.4.3-1.git164201e. 100%[==================================>]  62.10M  1.46MB/s
```
