### ISSUE TITLE
镜像网站“回到顶部”实现

### ISSUE THREAD

**Issue by alick** [FZUG/repo#69]
现在的“回到顶部”功能有一些问题：
1. 声音完全没有必要
2. 背景颜色和底部背景色太接近，所以滚动到底部时几乎不可见。
3. 使用的 elevator.js CDN 不支持 HTTPS，（@1dot75cm 最近给网站加了 HTTPS，）使得 HTTPS 页面混有 HTTP 内容，Firefox 等浏览器会默认拦截 HTTP 内容。

**Comment by 1dot75cm** [comment]
1. 好的，已去掉声音， 这样就不存在非 HTTPS 的内容了。（已解决）
2. 有时间修改
3. （已解决）

**Comment by alick** [comment]
:+1:

**Comment by Endle** [comment]
Has this bug been fixed?

**Comment by alick** [comment]
还差一个：
- [ ] 背景颜色和底部背景色太接近，所以滚动到底部时几乎不可见。

**Comment by 1dot75cm** [comment]
Fixed, close issue.
