### ISSUE TITLE
google-chrome 的源更名

### ISSUE THREAD

**Issue by Endle** [FZUG/repo#7]
现在，社区的 chrome 源命名为 google-chrome
http://repo.fdzh.org/chrome/google-chrome.repo
如果一个人既有官方的google-chrome源，又有fzug的镜像，会不会导致混淆？
可否改名为 fzug-chrome-mirror 之类的？

**Comment by 1dot75cm** [comment]
嗯嗯，官方的 rpm 包在安装后会覆盖 google-chrome.repo，确实需要重命名。

**Comment by 1dot75cm** [comment]
感谢建议，已修正
http://repo.fdzh.org/chrome/google-chrome_fzug.repo

**Comment by alick** [comment]
google-chrome 源名字中不应该出现 fzug

**Comment by 1dot75cm** [comment]
噢噢，和 google-chrome 不一样就行。我改下。

**Comment by justfordev123** [comment]
why 404 ??

**Comment by alick** [comment]
@CendyRe no 404 to me

**Comment by alick** [comment]
google-chrome repo文件名中不应该出现 fzug

**Comment by tvvocold** [comment]
@1dot75cm 
再改下吧。

**Comment by 1dot75cm** [comment]
http://repo.fdzh.org/chrome/google-chrome-mirrors.repo

**Comment by alick** [comment]
Thanks! Remember to fix README as well.

2015-07-06 17:36 GMT+08:00 1dot75cm notifications@github.com:
