### ISSUE TITLE
Wiki 页面编辑请求

### ISSUE THREAD

**Issue by Endle** [FZUG/repo#70]
https://github.com/FZUG/repo/wiki/chrome 上，导入 repo 的命令
`wget http://repo.fdzh.org/chrome/google-chrome-mirrors.repo -P /etc/yum.repos.d/  # Fedora/RHEL`
建议替换成 `sudo dnf config-manager --add-repo=http://repo.fdzh.org/chrome/google-chrome-mirrors.repo`

**Comment by Endle** [comment]
我刚才这么做了，发现这么做的话会从 google 的服务器上下载一个 key，可能会有障碍
不过，如果直接用 wget 的话，貌似也需要下载这个key

**Comment by alick** [comment]
你编辑不了吗？这个key应该就是 repo 文件里  gpgkey 指定的那个吧？

**Comment by Endle** [comment]
恩，我编辑不了。
说的就是gpgkey。它指向了google的服务器

**Comment by alick** [comment]
请再尝试一下。

我取消了只有 push 权限的人才能编辑维基的限制（应该没有必要，真正有恶意编辑也可以revert）

gpgkey 这样的行为应该没问题。

**Comment by Endle** [comment]
这样的话，第一次从镜像下载还是要连google的服务器
我们要不要把key也镜像掉？

在 2016年2月17日 上午8:17，Alick Zhao notifications@github.com写道：

> 请再尝试一下。
> 
> 我取消了只有 push 权限的人才能编辑维基的限制（应该没有必要，真正有恶意编辑也可以revert）
> 
> gpgkey 这样的行为应该没问题。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FZUG/repo/issues/70#issuecomment-184937110.

## 

Have a nice day!
Zhenbo Li

**Comment by alick** [comment]
没看到过类似的做法。镜像 key 需要保证 key 的 integrity

2016-02-16 19:07 GMT-06:00 Zhenbo Li notifications@github.com:

> 这样的话，第一次从镜像下载还是要连google的服务器
> 我们要不要把key也镜像掉？
> 
> 在 2016年2月17日 上午8:17，Alick Zhao notifications@github.com写道：
> 
> > 请再尝试一下。
> > 
> > 我取消了只有 push 权限的人才能编辑维基的限制（应该没有必要，真正有恶意编辑也可以revert）
> > 
> > gpgkey 这样的行为应该没问题。
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/FZUG/repo/issues/70#issuecomment-184937110.
> 
> ## 
> 
> Have a nice day!
> Zhenbo Li
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FZUG/repo/issues/70#issuecomment-184957963.

## 

Regards,
Alick

**Comment by 1dot75cm** [comment]
key已经镜像了，google-chrome-mirror.repo的key已经指向 repo.fdzh.org。

**Comment by alick** [comment]
务必指向HTTPS链接，避免中间被替换。

**Comment by 1dot75cm** [comment]
囧，脚本里的地址没改， 执行的时候又覆盖原来的 repo 了。
现在好了。

**Comment by alick** [comment]
关闭issue？

**Comment by 1dot75cm** [comment]
好的

@Endle 可以帮助完善 Wiki，刚为 chrome 添加了一点信息。
