### ISSUE TITLE
可以打fcitx-googlepinyin的包吗？

### ISSUE THREAD

**Issue by ghost** [FZUG/repo#71]
能翻墙后，fcitx-cloudpinyin+fcitx-googlepinyin比sogoupinyin好用多了，没有面板崩溃问题、没有资源占用问题。但是fedora下没有fcitx-googlepinyin的包。以前FZUG好像有个人打的包，现在建立社区了，反而源里没有了，能不能把fcitx-googlepinyin、libgooglepinyin的包放上来？openSUSE的源里有包，但是用着Fedora，却上openSUSE找包，还是觉得有点不方便～可否考虑一下～

**Comment by 1dot75cm** [comment]
可以考虑

**Comment by 1dot75cm** [comment]
经过调试， fcitx-cloudpinyin 可以不用翻直接使用 Google 云拼音。
fcitx-googlepinyin 已打包，但不知如何测试。设置里可以开启 Google 拼音。 @SeAL80s

**Comment by 1dot75cm** [comment]
ping @SeAL80s

**Comment by ghost** [comment]
fcitx-googlepinyin的包装不上，装完googlepinyin没有。还是去opensuse找包装，发现fzug的包版本低...
fcitx-googlepinyin-0.1.6-7.5.x86_64.rpm  libgooglepinyin0-0.1.2-11.6.x86_64.rpm  这两个是opensuse里的包，你可以和fzug里的包比较一下

**Comment by 1dot75cm** [comment]
@SeAL80s  已修复该错误。 请添加 [testing](https://repo.fdzh.org/FZUG/testing/) 源，并安装 `fcitx-googlepinyin-0.1.6-3.git6536e18.fc23.x86_64.rpm`。

**Comment by Endle** [comment]
> @SeAL80s 已修复该错误。 请添加 testing 源，并安装 fcitx-googlepinyin-0.1.6-3.git6536e18.fc23.x86_64.rpm。  

`[MIRROR] fcitx-googlepinyin-0.1.6-3.git6536e18.fc23.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: b97b843164370037511d31130934f282736dc891740f8747564a51c1ea3669a3(sha256)  Expected: 8835827da2f8c757237c26580528ba503901077e70f26479b6792fad28b1d078(sha256)`

是缓存的问题？

**Comment by 1dot75cm** [comment]
删除缓存看看 @Endle 

```
$ sudo rm -rf /var/cache/dnf/fzug*
```

**Comment by Endle** [comment]
> 删除缓存看看 @Endle

还是有一样的问题
我去 https://repo.fdzh.org/FZUG/testing/23/x86_64/fcitx-googlepinyin-0.1.6-3.git6536e18.fc23.x86_64.rpm 手动下载，得到的sha1sum是`b97b843164370037511d31130934f282736dc891740f8747564a51c1ea3669a3`

安装后可以正常使用，但还是不明白问题出在哪里

**Comment by 1dot75cm** [comment]
CDN的问题，刚给 fcitx-googlepinyin 改名，现在应该好了 @Endle
