### ISSUE TITLE
使用 yaourt 安装软件提醒“所需的密钥从密钥环中丢失”

### ISSUE THREAD

**Issue by HougeLangley** [FZUG/repo#73]
`[houge@localhost ~]$ yaourt -Sdd telegram-qt-git

==> 从 AUR 下载 telegram-qt-git 的 PKGBUILD 文件
x .SRCINFO
x PKGBUILD

There's an error in the cmake invocation: missing the leading "$" in _gitname to read the variable value

telegram-qt-git r439.3409c3f-1  (2015-08-14 22:25)
（Unsupported 中的包：潜在危险）
==> 编辑 PKGBUILD ？ [Y/n]("A" 忽略)
==> ----------------------------
==> n

==> telegram-qt-git 依赖关系：
- zlib （软件包已找到）
- cmake （软件包已找到） [makedepend]
- git （软件包已找到） [makedepend]

==> 继续构建 telegram-qt-git ？[Y/n]
==> ---------------------------
==> y

==> 构建和安装软件包
==> 为 telegram-qt-git 安装或者是构建缺失的依赖关系：
正在查找软件包冲突...

软件包 (3) cmake-3.4.3-1  git-2.7.2-2  zlib-1.2.8-4

全部安装大小：  53.39 MiB

:: 进行安装吗？ [Y/n] y
(3/3) 正在检查密钥环里的密钥                                                                                                    [##############################################################################] 100%
正在下载所需的密钥......
错误：key "7F2D434B9741E8AC" could not be looked up remotely
错误：所需的密钥从密钥环中丢失
错误：无法提交处理 (未预期的错误)
发生错误，没有软件包被更新。
==> 重新构建 telegram-qt-git ?[y/N]
==> ---------------------------
==> 
`

**Comment by 1dot75cm** [comment]
Disable check package sign

```
$ vim /etc/pacman.conf
...
#SigLevel = Required DatabaseOptional
SigLevel = Never
...
```

Or import key

```
$ sudo pacman-key --init
$ sudo pacman-key -r 7F2D434B9741E8AC
```

https://wiki.archlinux.org/index.php/Pacman/Package_signing

**Comment by HougeLangley** [comment]
谢谢。

**Comment by alick** [comment]
关闭，已解决。
