### ISSUE TITLE
dnf update 升级失败

### ISSUE THREAD

**Issue by evolighting** [FZUG/repo#75]
google chrome 和 atom 都提示
已google chrome 为例
[MIRROR] google-chrome-stable-49.0.2623.87-1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 4251648 but expected size is: 48455059
[FAILED] google-chrome-stable-49.0.2623.87-1.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download google-chrome-stable-49.0.2623.87-1.x86_64.rpm: All mirrors were tried

虽然我安装chrome只是为了它自带的flash player....
因为直接用源里的那个替换插件的话会有问题，还是要自己编译插件然后丢到firefox里去....

**Comment by evolighting** [comment]
另外我能直接在浏览器里下载到那个包...
网络没有问题...

**Comment by sztsian** [comment]
ack.
我在安装shadowsocks-qt5-2.6.1-1.gitba70fd1.fc23.x86_64时遇到的同样问题。也是在浏览器中可以下载，但是dnf不能。
@1dot75cm pls check

**Comment by 1dot75cm** [comment]
Google Chrome 因为未同步完成，就被CDN 镜像了，所以 dnf 提示 size 不对无法安装。目前的解决办法是，同步脚本下载至其他位置，再拷贝至 DocumentRoot。

atom 刚刚更新了，dnf 安装没出现问题。如果出现 Content-Length 段的大小不对，应该是您所在区域的 CDN 镜像有问题（七牛的锅，没找到解决方案）。

shadowsocks-qt5 刚刚测试了，未发现问题。 另外，白天网速很慢，可能是这个问题导致的。

一个悲剧的消息， chrome deb/rpm i386 的包已经没有了。 （已找到部分旧版本 RPM 包，有兴趣可以试试）

**Comment by 1dot75cm** [comment]
应该解决该问题了，有问题再开。

**Comment by umikachen** [comment]
[MIRROR] google-chrome-stable-50.0.2661.75-1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 14049280 but expected size is: 48426351
[FAILED] google-chrome-stable-50.0.2661.75-1.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

刚才更新时，重现了本帖中的问题

**Comment by 1dot75cm** [comment]
刚刚检查了已同步 rpm 的大小，其他的没问题， stable 未下载完（下载速度很慢）。
现在已经可以了，请手动下载。 @umikachen

[google-chrome-stable-50.0.2661.75-1.0.x86_64.rpm](https://repo.fdzh.org/chrome/rpm/x86_64/google-chrome-stable-50.0.2661.75-1.0.x86_64.rpm)
