### ISSUE TITLE
add repo-checker tool

### ISSUE THREAD

**Issue by 1dot75cm** [FZUG/repo#76]
https://github.com/1dot75cm/repo-checker 用于检查软件版本更新的工具，可否加入 FZUG？ 

@alick @sztsian

**Comment by sztsian** [comment]
+1 for repo-checker (with comments below)

> repo-checker 中的trans.py似乎是CAT（Computer Aided Translate）用的吧？
> 如果是，那么我主张把trans独立出来而不混杂在repo-checker中。

**Comment by sztsian** [comment]
@1dot75cm  pls also cc @cicku  when you request for new repo.

@cicku  ideas?

**Comment by 1dot75cm** [comment]
嗯 只添加 checker.py， 其他的删除。 另外，是 fork 还是新建库？

**Comment by sztsian** [comment]
等cicku的反馈，无异议后我会fork上述库到fzug.

**Comment by sztsian** [comment]
No objection received till now. I will clone your repo today.

**Comment by 1dot75cm** [comment]
Thanks.

**Comment by 1dot75cm** [comment]
![repo-checker with PyQt](https://files.gitter.im/1dot75cm/omGx/2016-12-29-09-06-21-_____.png)

最近开发了 repo-checker 的 GUI，代码在 [1dot75cm/repo-checker](https://github.com/1dot75cm/repo-checker)， 等搞好 setup.py, README.md 准备传到 PYPI 上。 ![](https://avatars0.githubusercontent.com/u/8544397?v=3&s=88)

到时候，就可以用 `pip install checker` 安装啦。 @sztsian

**Comment by sztsian** [comment]
赞！
如果需要在FZUG开一个新repo，可以直接reopen这个issue。如果不需要，这个issue就不必reopen了。
另外，建议同时打一个rpm包放在FZUG～

**Comment by 1dot75cm** [comment]
好的，谢谢，进度我在这里汇报。 @sztsian

**Comment by cicku** [comment]
我没意见

**Comment by 1dot75cm** [comment]
![https://files.gitter.im/1dot75cm/KWdU/2016-12-30-23-20-24-_____.png](https://files.gitter.im/1dot75cm/KWdU/2016-12-30-23-20-24-_____.png)
现在，差不多只要把原来那个命令行的改成使用 checker_ui.Checker 类，再写成模块就差不多了。
当前，是通过 XPath 规则解析发布页的时间，内部统一转成时间戳，进行对比的。不知道如何搞成支持多种匹配规则，要弄一个支持插件的么 @sztsian

**Comment by sztsian** [comment]
这个，你自己决定吧～我没有Python时间转换方面的经验。

**Comment by 1dot75cm** [comment]
已提交至 [PyPI/repo-checker](https://pypi.python.org/pypi/repo-checker), [1dot75cm/repo-checker](https://github.com/1dot75cm/repo-checker) @sztsian

**Comment by 1dot75cm** [comment]
`0.2.0`: 增加了插件功能，内置了许多项目网站的插件，见 [checker/backends](https://github.com/1dot75cm/repo-checker/tree/master/checker/backends)，允许用户在 `~/.repo-checker/backends/` 下面添加自定义插件。插件支持，`regex`, `xpath`, `json` 三种解析方式，可以很容易的定义自己的插件。 

如果没问题，可以 fork 了。@sztsian

**Comment by sztsian** [comment]
刚发现去年3月已经fork过了。参见该[comment](https://github.com/FZUG/repo/issues/76#issuecomment-199566798)。你是maintainer。

**Comment by 1dot75cm** [comment]
好吧， 我都没注意看 。 谢谢 @sztsian 
我把 URL 改成 FZUG 的。
