### ISSUE TITLE
请教下，centos 7不可以添加并使用该源？

### ISSUE THREAD

**Issue by foreverxyz** [FZUG/repo#78]
rt，centos 7可以使用该源吗？试着添加了，但是下载安装的时候总出现error 404 not found

**Comment by alick** [comment]
不能～没有支持～～抱歉

**Comment by 1dot75cm** [comment]
可以添加fc21的源试试， 但因为人力有限，不能支持 el7。您可以选择由 spec 文件构建适用于 el7 的rpm 包，或直接迁移到 Fedora (添加fedora 源可以无缝从el7 升级，或全新安装)。 最后，感谢您的支持。
