### ISSUE TITLE
Theme of fcitx-pinyin input bar changed to Ubuntu Kylin if sougoupinyin installed

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#80]
Theme of fcitx-pinyin input bar changed to Ubuntu Kylin if sougoupinyin installed. And the background color of changing input method changes to dark as well.
Environment:
Fedora 23 x86_64 with XFCE.
LANG=en_US.utf8

Steps to reproduce:
1. Add the FZUG Nonfree repo
2. sudo dnf install sogoupinyin -y
3. Add Sogou Pinyin to fcitx
4. Right click on fcitx applet, restart fcitx.
5. Switch to Sogou Pinyin and wait until the fcitx menu is replaced by Sogou Pinyin style
6. Switch to Pinyin.

Ways to change it back:
The only way I found to change everything back is, to uninstall sogoupinyin 😣

**Comment by 1dot75cm** [comment]
> - [fcitx-qimpanel](https://github.com/sogoupinyin/fcitx-qimpanel), 简单说就是 QML 写了一个类似 kimpanel 和 fcitx 4.8.3 之后 KDE 下那个托盘界面的界面，多出来的部分是支持皮肤。
> 
> 注：搜狗拼音 Linux 的主题是使用的自己开发的皮肤引擎 (能否直接使用 Windows 下的搜狗皮肤目前我还没有测试)，而非 qimpanel 的这个。 而 qimpanel 的皮肤引擎现在也不支持 fcitx 的原生皮肤。总结下来就是现在有三种皮肤：
> - fcitx 原生 (如 openSUSE 的默认皮肤),
> - qimpanel 皮肤 (装了搜狗拼音 Linux 后去使用 Sunpinyin, 你就会发现只能使用 qimpanel 自带的那几套 Ubuntu Kylin 的皮肤),
> - 搜狗拼音 Linux 皮肤.

摘自： https://forum.suse.org.cn/viewtopic.php?t=2426

目前，要使用 Fcitx 原生皮肤，只能杀死 sogou-qimpanel 进程。 @sztsian 
PS： [forum.suse.org.cn](https://forum.suse.org.cn) 搞的非常不错啊。

Update 16.3.31: 上游应提供选项，在切换至其他输入法时，可选禁用 `sogou-qimpanel`

**Comment by alick** [comment]
@1dot75cm 报告给上游了吗？有 bug 链接没？

**Comment by sztsian** [comment]
我记得与Aron提过。anyway, 先关闭这个了。

**Comment by qins** [comment]
what if we uninstall sogou-qimpanel
