### ISSUE TITLE
深度音乐播放器内存不断消耗

### ISSUE THREAD

**Issue by hanqing0521** [FZUG/repo#83]
深度音乐播放器不断的消耗内存，越用内存消耗越大，最后能干爆内存

**Comment by 1dot75cm** [comment]
確實有內存溢出的問題， 不知道最新的版本改進沒有。@hanqing0521

**Comment by sztsian** [comment]
I think this should be closed as of UPSTREAM BUG

**Comment by 1dot75cm** [comment]
Yes, It's upstream bug. @sztsian

**Comment by sztsian** [comment]
由于系上游bug，关闭此Issue。 @hanqing0521 在上游修复后如果该问题还存在，可以reopen

**Comment by alick** [comment]
应该请用户或者替用户向上游汇报 bug，并把 bug 链接附在这里。

**Comment by 1dot75cm** [comment]
我测试一下最新 commit，看看有没有问题。再向上游汇报 bug。@alick

**Comment by XuShaohua** [comment]
@1dot75cm @alick @hanqing0521 这个是个bug, 有个临时修复的方法, 建议先合并到rpm包里, https://bbs.deepin.org/forum.php?mod=viewthread&tid=39708&page=1

下个版本会正式修复这个问题. 抱歉

**Comment by alick** [comment]
@1dot75cm ping?

**Comment by 1dot75cm** [comment]
上游已经使用 QWidget, C++ 重写了 dmusic，应该会解决内存泄漏的问题。但是 3.0 的 dmusic 好像没有了 2.0 的百度音乐/网易音乐的插件功能，只能播放本地音乐了。@alick

**Comment by alick** [comment]
@1dot75cm 那打包最新版测试下？assign给你了。

**Comment by sztsian** [comment]
这个包已经在 RPMFusion 了。由于依赖原因现在只在 Rawhide。我先关闭这个问题。随后进入 Fedora 29 之后如还有问题可以在 RPMFusion Bugzilla 报 bug
