### ISSUE TITLE
test nvidia 364.12 driver

### ISSUE THREAD

**Issue by 1dot75cm** [FZUG/repo#84]
[NVIDIA 364.12 Beta](http://phoronix.com/scan.php?page=news_item&px=NVIDIA-364.12-Linux) 驱动带来了大量更新，支持 Wayland/Mir, DRM KMS，支持 PRIME 双显卡切换(之前官方驱动只能使用独显) ，详情见 [Changelog_364.12](http://www.nvidia.com/drivers/results/100577) [Changelog_364.15](http://www.nvidia.com/drivers/results/101729) [Changelog_364.19](http://www.nvidia.com/drivers/results/101818)。

Supported Products:
- 900/900M Series
- 800M Series
- 700/700M Series
- 600/600M Series
- 500/500M Series
- 400/400M Series

Software Requirements:
- Fedora 23 x86_64
- Linux kernel 2.6.18+  (`cat /proc/version`)
- XFree86 4.0.1+  (`XFree86 -version`)
- X.Org  1.0 -  1.18  (`Xorg -version`)
- Kernel modutils  2.1.121+  (`insmod --version`)
- glibc 2.0+  (`ls /lib/libc.so.* > 6`)
- libvdpau 0.2+  (`pkg-config --modversion vdpau`)

Need to test:
- [ ] DRM KMS: See [kms.html](http://download.nvidia.com/XFree86/Linux-x86_64/364.12/README/kms.html)
- [ ] Optimus, PRIME: See [optimus.html](http://download.nvidia.com/XFree86/Linux-x86_64/364.12/README/optimus.html) , [randr14.html](http://download.nvidia.com/XFree86/Linux-x86_64/364.12/README/randr14.html) , [Arch wiki](https://wiki.archlinux.org/index.php/NVIDIA_Optimus)
- [ ] Check 3D: `$ glxinfo | grep NVIDIA`
- [ ] Wayland: See [here](http://phoronix.com/scan.php?page=news_item&px=NVIDIA-Wayland-Discussion)

Installation steps:
1. add FZUG nonfree repository
2. Install gcc and kernel headers  
   `$ sudo dnf install gcc "kernel-devel-uname-r == $(uname -r)"`
3. Install akmod-nvidia  
   `$ sudo dnf install akmod-nvidia`
4. Install VDPAU support  
   `$ sudo dnf install vdpauinfo libva-vdpau-driver libva-utils mesa-vdpau-drivers`
5. Build nvidia kernel module  
   `$ sudo akmods`
6. Setting Optimus(xorg.conf, require `xorg-x11-server-Xorg`) and output source for Dispaly Manager  

```
$ sudo vim /etc/X11/xorg.conf
Section "Module"
    Load "modesetting"
EndSection
Section "Device"
    Identifier  "nvidia"
    Driver      "nvidia"
    BusID       "PCI:1:0:0"    # lspci | grep 3D (Change 01:00.0 to 1:0:0)
    Option      "AllowEmptyInitialConfiguration"
    Option      "NoLogo" "true"
EndSection
$ sudo vim /usr/share/gdm/greeter/autostart/display_setup.desktop
[Desktop Entry]
Type=Application
Name=Display setup
Exec=sh -c "xrandr --setprovideroutputsource modesetting NVIDIA-0; xrandr --auto"
NoDisplay=true
X-GNOME-AutoRestart=true
$ reboot
```
1. Test driver, run games  
   `$ glxinfo | grep direct; glxgears; glmark2`
2. Uninstall nvidia driver  
   `$ sudo dnf remove akmod-nvidia xorg-x11-drv-nvidia`

如果您认为测试会损害您的计算机或导致任何数据丢失，请不要进行测试。

**Comment by alick** [comment]
关闭，已过时。
