### ISSUE TITLE
Conflicts with file from package atom-1.6.2-2.fc23.x86_64

### ISSUE THREAD

**Issue by german-rios-gonzalez** [FZUG/repo#85]
Hello, I want to try your copr but I have this response (1) because I have installed the Atom code editor from helber

(1) Error: Transaction check error:
  file /usr/bin/apm from install of nodejs-atom-package-manager-1.9.1-2.git24807ff.fc23.x86_64 conflicts with file from package atom-1.6.2-2.fc23.x86_64

Can you please give me some advise to work around this?

**Comment by gbraad** [comment]
TL; dr: Simple answer, you have to decide which to use... But you can't have both.

Packages from different repository, providing same software in a dissimilar packaging can conflict. As you can se here, apm is provided by the atom package, while in the other packages it is split.

**Comment by helber** [comment]
Hi, here on my copr i don't split this package yet, and apm (Atom Package Manager) still part of atom.
Please use just one copr.
About apm my suggestion is use 
Name:    atom-package-manager
istead:
Name:    nodejs-atom-package-manager
The reason is the same as on:
https://bugzilla.redhat.com/show_bug.cgi?id=1132661

**Comment by german-rios-gonzalez** [comment]
oh! I see, it is so sad obviously I want to have both packages, thanks for the explanations.

pd: I'm sorry for my english, is not my native language.

**Comment by paulcarroty** [comment]
I recommend to use all packages from this repo: https://copr.fedorainfracloud.org/coprs/mosquito/atom/

@helber builds is too much painful to use because none of modern Fedora releases use the Node 0.10 and Atom package manager doesn't work by default.

**Comment by german-rios-gonzalez** [comment]
@paulcarroty Thanks mate! I didn't aware that I could install atom from that repository
