### ISSUE TITLE
youdao-dict 不能用了

### ISSUE THREAD

**Issue by sunznx** [FZUG/repo#89]
RT

**Comment by sunznx** [comment]
dnf update -y 之后就不能用了，不知道哪里冲突了，看源里面版本都没更新过，不知道哪里有问题

**Comment by 1dot75cm** [comment]
上游也一直没更新过。 刚刚看了一下，是由于 Qt 已更新至 5.6.0，而 PyQt 5.5.1 还未完全支持 5.6.0。临时解决办法是 **降级 `qt5-qtbase` 至 5.5.0 版本** 即可。

**Comment by sunznx** [comment]
ok 了

**Comment by juteman** [comment]
我的也是，看来要降级。。。。。

**Comment by sztsian** [comment]
Close as FIXED. Thanks for your report.

**Comment by sunznx** [comment]
现在fedora24了，youdao-dict 又不能用了，这次降不了级

**Comment by han190** [comment]
同上，更性24以后不能用了，貌似还是qt的问题。

**Comment by xinmeng1** [comment]
哪个大神可以解决呢?

**Comment by sunznx** [comment]
每天 dnf update 一次，好失望啊，几个月了 - -

**Comment by redapple0204** [comment]
解决办法请看下面的Comments

https://aur.archlinux.org/packages/youdao-dict/

**Comment by alick** [comment]
@redapple0204 你是指 https://paste.xinu.at/a0GW/ 的patch吗？ @1dot75cm  也许可以试一试。

**Comment by sztsian** [comment]
看了下，当前的做法是解包Deb然后转换为RPM。但根据有道词典的版权信息，Deb包只能在Ubuntu及其衍生版中依样使用，不能做修改。所以不太好解决。
查看其他的许可协议，发现.tar.gz版中除了数据文件之外都是GPLv3许可，因此打算改造这个RPM使其使用tar.gz版有道词典。之后再尝试打上述补丁。

**Comment by 1dot75cm** [comment]
`tar.gz` 包中没有以下两个文件，虽然好像不影响什么功能（影响托盘样式 GTK or Qt） @sztsian 
```
/usr/share/youdao-dict/indicator-youdao.py
/usr/share/dbus-1/services/com.youdao.indicator.service
```

该补丁可以修复该问题。@alick @sunznx @juteman @han190 @xinmeng1 @redapple0204

archlinuxcn bbs discuss: http://bbs.archlinuxcn.org/viewtopic.php?id=4261
