### ISSUE TITLE
搜狗拼音依赖的opencc能否更新？

### ISSUE THREAD

**Issue by hitzhangjie** [FZUG/repo#9]
搜狗拼音依赖的opencc能否更新到最新的版本呢？

**Comment by sztsian** [comment]
Hi, [OpenCC](https://admin.fedoraproject.org/pkgdb/package/opencc/)是 Fedora 官方的软件包，包维护者负责更新软件包的事宜。

**Comment by alick** [comment]
到 bugzilla.redhat.com 上提交 fedora opencc 的 bug 吧

**Comment by 1dot75cm** [comment]
opencc 1.0.2 是最新的，官方一般不会打包 commit，只打包 Tag。
此 repo 中的包与官方兼容，如果官方更新了 release 会自动替代本源的包。
如有需要，可以打包 commit，但需要更多测试 不保证稳定。
所以，还是建议到 bugzilla 上提交申请。
