### ISSUE TITLE
chrome deb release文件的问题

### ISSUE THREAD

**Issue by xiaoxiyao** [FZUG/repo#90]
无法下载 https://repo.fdzh.org/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

release文件可以下载,但是里面只有amd64的信息,没有i386的相关信息,导致更新的时候出现这个问题,不知道该怎么解决

**Comment by xiaoxiyao** [comment]
暂时找到一个解决方法,修改google-chrome.list如下

```
deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
deb [arch=amd64] https://repo.fdzh.org/chrome/deb/ stable main
```

**Comment by 1dot75cm** [comment]
Google 已不提供 i386 的二进制包，因为源里未删除的 i386 信息导致这个问题？@xiaoxiyao

**Comment by xiaoxiyao** [comment]
应该是这个问题，具体的我也不太清楚，有其他的解决方法么 @1dot75cm

**Comment by 1dot75cm** [comment]
已删除 i386 信息， 请测试。 @xiaoxiyao

**Comment by xiaoxiyao** [comment]
不行，还是会出错，貌似纯64位的源都会有这个问题，dl.google.com也是。只能修改 google-chrome.list 了 @1dot75cm
