### ISSUE TITLE
Atom install conflicts with official Node.js V5 Repository

### ISSUE THREAD

**Issue by andyrichardson** [FZUG/repo#91]
The 'Official' Node.js V5 Repository is hosted by _nodesource_ and advertised on nodejs.org [here](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora). 

```
file /usr/lib/node_modules/npm/package.json from install of npm-1.3.6-8.fc23.noarch conflicts with file from package nodejs-5.10.1-1nodesource.fc23.x86_64
# errors continue
```

Installation log: [err.log.txt](https://github.com/FZUG/repo/files/232597/err.log.txt)

**Comment by 1dot75cm** [comment]
I try to fix it. It seems to work normally. Thanks report. @andyrichardson 
https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/180315/

```
$ curl --silent --location https://rpm.nodesource.com/setup_5.x | bash -
$ sudo dnf copr enable mosquito/atom
$ sudo dnf install atom
$ apm -v
apm  1.9.2
npm  3.8.6
node 0.10.42
python 2.7.10
git 2.5.0
```

**Comment by andyrichardson** [comment]
This issue was caused not by this repository but by a broken dependencies in the nodejs-devel rpm provided by nodesource.

https://github.com/nodesource/distributions/issues/328
