### ISSUE TITLE
Failed to synchronize cache for repo 'fzug-free'，禁用

### ISSUE THREAD

**Issue by wmzy** [FZUG/repo#92]
``` bash
repo: using cache for: fzug-nonfree
not found deltainfo for: FZUG fc23 - Nonfree
not found updateinfo for: FZUG fc23 - Nonfree
Cannot download 'http://repo.fdzh.org/FZUG/free/23/x86_64/': Yum repo downloading error: Downloading error(s): repodata/16b14c2d86198231865be4bc26d3c1ba02370ec58c5068560f2cf06f47f02fd2-filelists.xml.gz - Cannot download, all mirrors were already tried without success; repodata/2bb6c72ca7aea7a02992e3aeba4498c103a5fac9a0443484b4932082ddc8ca96-comps-fzug.xml.gz - Cannot download, all mirrors were already tried without success.
Failed to synchronize cache for repo 'fzug-free'，禁用。
```

chrome下载filelists.xml.gz半截也会失败。
![image](https://cloud.githubusercontent.com/assets/5526525/14907186/b6467496-0d8a-11e6-8b8d-0a9b325a27ef.png)

**Comment by 1dot75cm** [comment]
刚刚放宽了服务器连接限制。现在可以了吗？ @wmzy

**Comment by wmzy** [comment]
@1dot75cm 还是不行。浏览器可以下载，但是要等好久。
![image](https://cloud.githubusercontent.com/assets/5526525/14907401/10e4217a-0d8e-11e6-8490-a5221a13b746.png)

**Comment by 1dot75cm** [comment]
关闭了限制 @wmzy

**Comment by wmzy** [comment]
@1dot75cm 没问题了

**Comment by 1dot75cm** [comment]
每 IP 连接数限制为 10，如果有问题请报告。 目前未看到错误日志。 @wmzy

**Comment by a5corpii** [comment]
我这边报同样的错误，`Failed to synchronize cache for repo 'fzug-nonfree'，禁用。`
而 Testing 和 Free 都是可用的。
前天用手机做热点试了，不行，以为是同一IP人数太多；昨天早上6点多连热点也不行，我怀疑不是连接数的问题了；今天一早连了路由还是不行。

**Comment by alick** [comment]
@erstern 您用的是 Fedora 26 吗？是不是 #270

**Comment by a5corpii** [comment]
@alick 是 Fedora 25，我也是因为 26 缓存失败解决不了才用 25 的，开始还以为是 26 的 BUG 什么的。之前家里的广电网用 25 没有问题，现在用的是联通，装机的当天，所有源都是可以的，不知道为什么过了两天突然就不行了。

**Comment by alick** [comment]
@erstern 我相信您遇到的问题和这里已关闭的 #92 不一样。我会新开一个针对 F25 nonfree 的 issue，请到那里讨论。

**Comment by alick** [comment]
@erstern 请到 #271 跟进 F25 nonfree 仓库被禁用的问题。
