### ISSUE TITLE
installing vivaldi-snapshot issues

### ISSUE THREAD

**Issue by breezegrowing** [FZUG/repo#95]
warning: /var/cache/dnf/vivaldi-08f7590bc52acb6d/packages/vivaldi-snapshot-1.0.403.15-1.i386.rpm: Header V4 RSA/SHA1 Signature, key ID 7b8b44a1: NOKEY
Curl error (51): SSL peer certificate or SSH remote key was not OK for https://repo.vivaldi.com/archive/linux_signing_key.pub [Unable to communicate securely with peer: requested domain name does not match the server's certificate.]

any solutions?

**Comment by 1dot75cm** [comment]
@breezegrowing please use following settings:

```
$ vim /etc/yum.repos.d/vivaldi.repo
[vivaldi]
name=Vivaldi Browser
#baseurl=http://repos.vivaldi.com/archive/rpm/$basearch
#gpgkey=http://repos.vivaldi.com/archive/linux_signing_key.pub
baseurl=https://repo.fdzh.org/vivaldi/rpm/$basearch
gpgkey=https://repo.fdzh.org/vivaldi/linux_signing_key.pub
gpgcheck=1
enabled=1
skip_if_unavailable=1
```

**Comment by alick** [comment]
Server SSL certificate issue. It's best to notify the upstream the issue and let them to fix their SSL configuration.

In @1dot75cm 's walkaround, HTTPS is replaced by plain HTTP. Use at your own risk.

**Comment by 1dot75cm** [comment]
The upstream also use HTTP instead of HTTPS.  @alick 

```
$ curl -I --insecure https://repos.vivaldi.com/archive/linux_signing_key.pub
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: http://repos.vivaldi.com/archive/linux_signing_key.pub
Connection: close
```

**Comment by 1dot75cm** [comment]
`repo.vivaldi.com` is a CDN mirror site. `repos.vivaldi.com` is a original site. CDN is not easy to support HTTPs. 

> Server SSL certificate issue. It's best to notify the upstream the issue and let them to fix their SSL configuration.

We need to notify the upstream the issue. @alick

**Comment by sztsian** [comment]
Is this fixed by switching to http protocol?  @breezegrowing

**Comment by alick** [comment]
Closing as vivaldi is not hosted by FZUG.
