### ISSUE TITLE
Is it reasonable to send build log to Chinese list?

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#99]
如题。我觉得将编译日志发送到中文邮件列表有些不妥唉。邮件列表本为用户交流的地方，这样子搞得机器人发的邮件比人发的邮件都多了。
大家的意见呢？

我觉得可以创建一个google group,专门用来收buildlog，需要的人自己订阅googlegroup就好了嘛

**Comment by 1dot75cm** [comment]
听大家的意见，如果觉得不妥 发到其他地方也好。

**Comment by ghost** [comment]
> 我觉得可以创建一个google group,专门用来收buildlog，需要的人自己订阅googlegroup就好了嘛

同意，创建 FZUG packaging 这种式样的，专门收 build log ，这样挺好。的确邮件列表是用户交流的地方。我昨天点开 maillist 的 archive 一看，看到的基本都是 build log

**Comment by sztsian** [comment]
fzug-builds@googlegroups.com

@nrechn 话说你的邮箱是nrechn 还是neilgechn？

@1dot75cm 以及 fedorabot已经是成员了。

**Comment by ghost** [comment]
> @nrechn 话说你的邮箱是nrechn 还是neilgechn？

@sztsian 都是我的邮箱。_nrechn_ 是后注册的，为了和我的用户名对上号。所以最好标记 _nrechn_  为我的邮箱。

**Comment by sztsian** [comment]
@nrechn ok，为了防止spam，更改了你的评论。已经将你加入该list

**Comment by sztsian** [comment]
似乎buildlog已经开始发送至上述列表了。所以这个issue可以关闭了。
